import { describe, expect, it } from 'vitest';
import {
  generateAiRobotsTxt,
  generateMcpServerConfig,
  repairJson,
  validateJsonLines,
  validateLlmsTxt,
  validateMcpJsonConfig,
} from './high-opportunity-tool-helpers';

describe('high opportunity shared helpers', () => {
  it('repairs conservative malformed JSON syntax', () => {
    const result = repairJson(`{
      // generated by an assistant
      name: 'Ada',
      "skills": ["math", "software",],
    }`);

    expect(result.valid).toBe(true);
    expect(result.output).toBe('{\n  "name": "Ada",\n  "skills": [\n    "math",\n    "software"\n  ]\n}');
    expect(result.fixes).toEqual([
      'Removed JavaScript-style comments',
      'Quoted unquoted object keys',
      'Converted single-quoted strings',
      'Removed trailing commas',
    ]);
  });

  it('reports unrepaired JSON without inventing values', () => {
    const result = repairJson('{ "name": "Ada", "missing": }');
    expect(result.valid).toBe(false);
    expect(result.output).toBe('');
    expect(result.error).toContain('Unexpected token');
  });

  it('validates JSON Lines and reports invalid line numbers', () => {
    const result = validateJsonLines('{"id":1}\n{"id":2}\nnot json\n\n[1,2,3]');
    expect(result.valid).toBe(false);
    expect(result.validLines).toBe(3);
    expect(result.invalidLines).toEqual([{ line: 3, message: expect.stringContaining('Unexpected') }]);
    expect(result.normalized).toBe('{"id":1}\n{"id":2}\n[1,2,3]');
  });

  it('validates llms.txt structure and links', () => {
    const result = validateLlmsTxt(`# Example Docs

> Short description.

## Docs
- [API](https://example.com/api)
- Missing link`);

    expect(result.title).toBe('Example Docs');
    expect(result.links).toBe(1);
    expect(result.issues).toContain('Line 7 list item should use Markdown link syntax.');
    expect(result.warnings).toEqual([]);
  });

  it('generates AI crawler robots.txt policy blocks', () => {
    const output = generateAiRobotsTxt({
      policy: 'block-training',
      sitemapUrl: 'https://example.com/sitemap.xml',
      extraAgents: ['ExampleBot'],
    });

    expect(output).toContain('User-agent: GPTBot');
    expect(output).toContain('User-agent: ClaudeBot');
    expect(output).toContain('User-agent: Google-Extended');
    expect(output).toContain('User-agent: PerplexityBot');
    expect(output).toContain('User-agent: ExampleBot');
    expect(output).toContain('Disallow: /');
    expect(output).toContain('Sitemap: https://example.com/sitemap.xml');
  });

  it('validates MCP JSON configs with server shape warnings', () => {
    const result = validateMcpJsonConfig(JSON.stringify({
      mcpServers: {
        filesystem: { args: '--bad' },
        github: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-github'], env: { GITHUB_TOKEN: 'token' } },
      },
    }));

    expect(result.validJson).toBe(true);
    expect(result.serverCount).toBe(2);
    expect(result.errors).toContain('filesystem.command is required.');
    expect(result.errors).toContain('filesystem.args must be an array when provided.');
    expect(result.warnings).toContain('github.env includes a concrete value; prefer environment placeholders for shared configs.');
  });

  it('generates MCP server config JSON for client presets', () => {
    const output = generateMcpServerConfig({
      client: 'claude',
      serverName: 'filesystem',
      command: 'npx',
      argsText: '-y @modelcontextprotocol/server-filesystem /Users/me/project',
      envText: 'DEBUG=false',
    });

    expect(JSON.parse(output)).toEqual({
      mcpServers: {
        filesystem: {
          command: 'npx',
          args: ['-y', '@modelcontextprotocol/server-filesystem', '/Users/me/project'],
          env: { DEBUG: 'false' },
        },
      },
    });
  });
});
