import { defaultLocale, type Locale } from './i18n';

export const siteInfoPageSlugs = ['privacy', 'terms', 'contact'] as const;
export type SiteInfoPageSlug = (typeof siteInfoPageSlugs)[number];

export interface SiteInfoPageCopy {
  title: string;
  description: string;
  eyebrow: string;
  updated: string;
  sections: Array<{
    title: string;
    paragraphs: string[];
  }>;
  primaryLink: {
    href: string;
    label: string;
  };
  secondaryLink: {
    href: string;
    label: string;
  };
}

const siteInfoPagesByLocale = {
  en: {
    privacy: {
      title: 'Privacy Policy',
      description: 'How U2Tool handles browser-based tool usage, optional diagnostics, and contact information.',
      eyebrow: 'Platform trust',
      updated: 'Updated May 8, 2026',
      sections: [
        {
          title: 'Browser-first processing',
          paragraphs: [
            'U2Tool is designed so most tools run directly in your browser. Text, files, images, and generated outputs normally stay on your device unless a specific tool clearly needs a network request.',
            'We do not ask you to create an account to use the public tool catalog, and we do not sell personal information.',
          ],
        },
        {
          title: 'Operational data',
          paragraphs: [
            'Like most websites, hosting providers may process basic request data such as IP address, user agent, URL, referrer, and timestamps for security, abuse prevention, debugging, and traffic reliability.',
            'If you contact us at contact@u2tool.com, we use the information you provide only to respond to your message and improve the service.',
          ],
        },
        {
          title: 'Third-party services',
          paragraphs: [
            'Some tools may call a public API when that is essential to the feature, such as lookup or validation workflows. When a tool depends on an external service, avoid entering secrets or sensitive personal data.',
            'We may update this policy as the product changes. Material changes will be reflected on this page.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Browse tools' },
      secondaryLink: { href: '/contact', label: 'Contact U2Tool' },
    },
    terms: {
      title: 'Terms of Service',
      description: 'The basic terms for using U2Tool online utilities, generated outputs, and public website content.',
      eyebrow: 'Service terms',
      updated: 'Updated May 8, 2026',
      sections: [
        {
          title: 'Use of the service',
          paragraphs: [
            'U2Tool provides free online utilities for formatting, converting, generating, validating, and inspecting data. You are responsible for how you use the tools and any output they create.',
            'Do not use the service to attack systems, bypass access controls, violate laws, or process data that you are not allowed to handle.',
          ],
        },
        {
          title: 'No professional advice',
          paragraphs: [
            'Tool output is provided for convenience and may contain mistakes. Review important output before relying on it in production, legal, financial, medical, or security-sensitive contexts.',
            'Templates generated by legal, policy, or business tools are starting points and should be reviewed by a qualified professional before use.',
          ],
        },
        {
          title: 'Availability and changes',
          paragraphs: [
            'We may add, change, disable, or remove tools as the product evolves. The website is provided as-is without a guarantee that every tool will always be available or error-free.',
            'Continued use of U2Tool after updates to these terms means you accept the updated terms.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Browse tools' },
      secondaryLink: { href: '/privacy', label: 'Privacy Policy' },
    },
    contact: {
      title: 'Contact U2Tool',
      description: 'Reach U2Tool for product feedback, bug reports, indexing questions, and partnership requests.',
      eyebrow: 'Support',
      updated: 'Current contact channel',
      sections: [
        {
          title: 'Email',
          paragraphs: [
            'For support, bug reports, content questions, or partnership requests, email contact@u2tool.com.',
            'Include the tool URL, your browser, the exact input shape if it is safe to share, and what you expected to happen. Please do not send passwords, private keys, tokens, or sensitive files.',
          ],
        },
        {
          title: 'Indexing and SEO requests',
          paragraphs: [
            'If you are reporting a broken URL, redirect issue, or search result problem, include the affected URL and where you found it.',
            'We prioritize issues that affect active tools, localized pages, sitemaps, structured data, and browser-side privacy expectations.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Browse tools' },
      secondaryLink: { href: '/privacy', label: 'Privacy Policy' },
    },
  },
  zh: {
    privacy: {
      title: '隐私政策',
      description: '了解 U2Tool 如何处理浏览器端工具使用、可选诊断数据和联系信息。',
      eyebrow: '平台信任',
      updated: '2026 年 5 月 8 日更新',
      sections: [
        {
          title: '浏览器优先处理',
          paragraphs: [
            'U2Tool 的多数工具会直接在你的浏览器中运行。文本、文件、图片和生成结果通常保留在你的设备上，除非某个工具明确需要网络请求才能完成任务。',
            '使用公开工具目录不需要注册账户，我们也不会出售个人信息。',
          ],
        },
        {
          title: '运营数据',
          paragraphs: [
            '与大多数网站一样，托管服务可能会处理 IP 地址、用户代理、URL、来源页面和时间戳等基础请求数据，用于安全、防滥用、调试和流量稳定性。',
            '如果你通过 contact@u2tool.com 联系我们，我们只会使用你提供的信息回复消息并改进服务。',
          ],
        },
        {
          title: '第三方服务',
          paragraphs: [
            '部分工具在功能必须依赖外部服务时可能会调用公共 API，例如查询或验证流程。使用依赖外部服务的工具时，请避免输入密钥或敏感个人数据。',
            '我们可能会随着产品变化更新本政策。重要变更会反映在本页面。',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: '浏览工具' },
      secondaryLink: { href: '/contact', label: '联系 U2Tool' },
    },
    terms: {
      title: '服务条款',
      description: '使用 U2Tool 在线工具、生成结果和公开网站内容时适用的基本条款。',
      eyebrow: '服务条款',
      updated: '2026 年 5 月 8 日更新',
      sections: [
        {
          title: '服务使用',
          paragraphs: [
            'U2Tool 提供免费的在线工具，用于格式化、转换、生成、验证和检查数据。你需要自行负责工具使用方式以及工具生成的任何结果。',
            '请勿使用本服务攻击系统、绕过访问控制、违反法律，或处理你无权处理的数据。',
          ],
        },
        {
          title: '不构成专业建议',
          paragraphs: [
            '工具输出仅为便利而提供，可能包含错误。将输出用于生产、法律、财务、医疗或安全敏感场景前，请先自行核查。',
            '法律、政策或业务类工具生成的模板只是起点，使用前应由合格专业人士审核。',
          ],
        },
        {
          title: '可用性与变更',
          paragraphs: [
            '随着产品演进，我们可能添加、调整、停用或移除工具。本网站按现状提供，不保证每个工具始终可用或完全无误。',
            '这些条款更新后继续使用 U2Tool，即表示你接受更新后的条款。',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: '浏览工具' },
      secondaryLink: { href: '/privacy', label: '隐私政策' },
    },
    contact: {
      title: '联系 U2Tool',
      description: '向 U2Tool 发送产品反馈、错误报告、索引问题和合作请求。',
      eyebrow: '支持',
      updated: '当前联系渠道',
      sections: [
        {
          title: '电子邮件',
          paragraphs: [
            '如需支持、报告错误、咨询内容问题或提出合作请求，请发送邮件至 contact@u2tool.com。',
            '请附上工具 URL、浏览器、在安全前提下可分享的输入形态，以及你期望发生的结果。请不要发送密码、私钥、令牌或敏感文件。',
          ],
        },
        {
          title: '索引与 SEO 请求',
          paragraphs: [
            '如果你要报告损坏 URL、重定向问题或搜索结果问题，请提供受影响的 URL 以及你发现它的位置。',
            '我们会优先处理影响活跃工具、本地化页面、站点地图、结构化数据和浏览器端隐私预期的问题。',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: '浏览工具' },
      secondaryLink: { href: '/privacy', label: '隐私政策' },
    },
  },
  ja: {
    privacy: {
      title: 'プライバシーポリシー',
      description: 'U2Tool がブラウザ内ツールの利用、任意の診断データ、問い合わせ情報をどのように扱うかを説明します。',
      eyebrow: 'プラットフォームの信頼',
      updated: '2026年5月8日更新',
      sections: [
        {
          title: 'ブラウザ優先の処理',
          paragraphs: [
            'U2Tool の多くのツールはブラウザ内で直接動作するよう設計されています。特定の機能でネットワーク通信が必要な場合を除き、テキスト、ファイル、画像、生成結果は通常あなたの端末に残ります。',
            '公開ツールカタログを利用するためにアカウント作成を求めることはなく、個人情報を販売することもありません。',
          ],
        },
        {
          title: '運用データ',
          paragraphs: [
            '多くのウェブサイトと同様に、ホスティング事業者は IP アドレス、ユーザーエージェント、URL、参照元、タイムスタンプなどの基本的なリクエスト情報を、安全対策、不正利用防止、デバッグ、安定運用のために処理する場合があります。',
            'contact@u2tool.com へ連絡した場合、提供された情報は返信とサービス改善のためにのみ使用します。',
          ],
        },
        {
          title: '第三者サービス',
          paragraphs: [
            '検索や検証など、機能に不可欠な場合は一部のツールが公開 API を呼び出すことがあります。外部サービスに依存するツールでは、秘密情報や機微な個人データを入力しないでください。',
            '製品の変更に合わせて本ポリシーを更新することがあります。重要な変更はこのページに反映されます。',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'ツールを見る' },
      secondaryLink: { href: '/contact', label: 'U2Tool に連絡' },
    },
    terms: {
      title: '利用規約',
      description: 'U2Tool のオンラインユーティリティ、生成結果、公開サイトコンテンツを利用するための基本条件です。',
      eyebrow: 'サービス条件',
      updated: '2026年5月8日更新',
      sections: [
        {
          title: 'サービスの利用',
          paragraphs: [
            'U2Tool は、データの整形、変換、生成、検証、確認のための無料オンラインユーティリティを提供します。ツールの使い方と生成される出力の利用については利用者が責任を負います。',
            'システムへの攻撃、アクセス制御の回避、法令違反、または取り扱う権限のないデータ処理に本サービスを使用しないでください。',
          ],
        },
        {
          title: '専門的助言ではありません',
          paragraphs: [
            'ツールの出力は利便性のために提供され、誤りを含む場合があります。重要な出力を本番、法務、財務、医療、セキュリティ上重要な場面で利用する前に確認してください。',
            '法律、ポリシー、ビジネス関連ツールが生成するテンプレートは出発点であり、使用前に資格ある専門家の確認を受けてください。',
          ],
        },
        {
          title: '可用性と変更',
          paragraphs: [
            '製品の進化に合わせて、ツールの追加、変更、無効化、削除を行う場合があります。本サイトは現状有姿で提供され、すべてのツールが常に利用可能または無誤りであることを保証しません。',
            '本規約の更新後も U2Tool の利用を継続する場合、更新後の規約に同意したものとみなされます。',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'ツールを見る' },
      secondaryLink: { href: '/privacy', label: 'プライバシーポリシー' },
    },
    contact: {
      title: 'U2Tool へのお問い合わせ',
      description: '製品フィードバック、不具合報告、インデックス関連の質問、提携依頼を U2Tool に送信できます。',
      eyebrow: 'サポート',
      updated: '現在の連絡先',
      sections: [
        {
          title: 'メール',
          paragraphs: [
            'サポート、不具合報告、コンテンツに関する質問、提携依頼は contact@u2tool.com までメールでお送りください。',
            'ツール URL、利用ブラウザ、安全に共有できる入力の形、期待した動作を含めてください。パスワード、秘密鍵、トークン、機密ファイルは送らないでください。',
          ],
        },
        {
          title: 'インデックスと SEO の依頼',
          paragraphs: [
            '壊れた URL、リダイレクト、検索結果の問題を報告する場合は、対象 URL と見つけた場所を含めてください。',
            '稼働中のツール、ローカライズページ、サイトマップ、構造化データ、ブラウザ側のプライバシー期待に影響する問題を優先します。',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'ツールを見る' },
      secondaryLink: { href: '/privacy', label: 'プライバシーポリシー' },
    },
  },
  ko: {
    privacy: {
      title: '개인정보 처리방침',
      description: 'U2Tool이 브라우저 기반 도구 사용, 선택적 진단 데이터, 문의 정보를 처리하는 방식을 설명합니다.',
      eyebrow: '플랫폼 신뢰',
      updated: '2026년 5월 8일 업데이트',
      sections: [
        {
          title: '브라우저 우선 처리',
          paragraphs: [
            'U2Tool은 대부분의 도구가 브라우저에서 직접 실행되도록 설계되어 있습니다. 특정 도구가 명확하게 네트워크 요청을 필요로 하지 않는 한 텍스트, 파일, 이미지, 생성 결과는 일반적으로 사용자의 기기에 남습니다.',
            '공개 도구 카탈로그를 사용하기 위해 계정 생성을 요구하지 않으며 개인 정보를 판매하지 않습니다.',
          ],
        },
        {
          title: '운영 데이터',
          paragraphs: [
            '대부분의 웹사이트처럼 호스팅 제공업체는 보안, 악용 방지, 디버깅, 트래픽 안정성을 위해 IP 주소, 사용자 에이전트, URL, 리퍼러, 타임스탬프 같은 기본 요청 데이터를 처리할 수 있습니다.',
            'contact@u2tool.com 으로 연락하면 제공한 정보는 답변과 서비스 개선을 위해서만 사용됩니다.',
          ],
        },
        {
          title: '제3자 서비스',
          paragraphs: [
            '일부 도구는 조회나 검증처럼 기능에 필수적인 경우 공개 API를 호출할 수 있습니다. 외부 서비스에 의존하는 도구에서는 비밀 정보나 민감한 개인 데이터를 입력하지 마세요.',
            '제품 변경에 따라 이 정책을 업데이트할 수 있으며 중요한 변경 사항은 이 페이지에 반영됩니다.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: '도구 둘러보기' },
      secondaryLink: { href: '/contact', label: 'U2Tool 문의' },
    },
    terms: {
      title: '서비스 약관',
      description: 'U2Tool 온라인 유틸리티, 생성 결과, 공개 웹사이트 콘텐츠 사용에 적용되는 기본 약관입니다.',
      eyebrow: '서비스 약관',
      updated: '2026년 5월 8일 업데이트',
      sections: [
        {
          title: '서비스 이용',
          paragraphs: [
            'U2Tool은 데이터 형식화, 변환, 생성, 검증, 검사를 위한 무료 온라인 유틸리티를 제공합니다. 도구 사용 방식과 생성된 출력의 사용에 대한 책임은 사용자에게 있습니다.',
            '시스템 공격, 접근 제어 우회, 법률 위반, 또는 처리 권한이 없는 데이터 취급에 서비스를 사용하지 마세요.',
          ],
        },
        {
          title: '전문적 조언이 아닙니다',
          paragraphs: [
            '도구 출력은 편의를 위해 제공되며 오류가 있을 수 있습니다. 프로덕션, 법률, 재무, 의료, 보안상 민감한 상황에서 중요한 출력에 의존하기 전에 검토하세요.',
            '법률, 정책, 비즈니스 도구가 생성한 템플릿은 출발점이며 사용 전에 자격 있는 전문가의 검토를 받아야 합니다.',
          ],
        },
        {
          title: '가용성과 변경',
          paragraphs: [
            '제품이 발전함에 따라 도구를 추가, 변경, 비활성화 또는 제거할 수 있습니다. 웹사이트는 있는 그대로 제공되며 모든 도구가 항상 사용 가능하거나 오류가 없음을 보장하지 않습니다.',
            '약관 업데이트 후 U2Tool을 계속 사용하면 업데이트된 약관에 동의한 것으로 간주됩니다.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: '도구 둘러보기' },
      secondaryLink: { href: '/privacy', label: '개인정보 처리방침' },
    },
    contact: {
      title: 'U2Tool 문의',
      description: '제품 피드백, 버그 신고, 색인 관련 질문, 제휴 요청을 U2Tool에 보낼 수 있습니다.',
      eyebrow: '지원',
      updated: '현재 문의 채널',
      sections: [
        {
          title: '이메일',
          paragraphs: [
            '지원, 버그 신고, 콘텐츠 질문, 제휴 요청은 contact@u2tool.com 으로 이메일을 보내주세요.',
            '도구 URL, 브라우저, 안전하게 공유할 수 있는 정확한 입력 형태, 기대한 결과를 포함해 주세요. 비밀번호, 개인 키, 토큰, 민감한 파일은 보내지 마세요.',
          ],
        },
        {
          title: '색인 및 SEO 요청',
          paragraphs: [
            '깨진 URL, 리디렉션 문제, 검색 결과 문제를 신고할 때는 영향을 받는 URL과 발견한 위치를 포함해 주세요.',
            '활성 도구, 로컬라이즈된 페이지, 사이트맵, 구조화 데이터, 브라우저 측 개인정보 기대에 영향을 주는 문제를 우선 처리합니다.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: '도구 둘러보기' },
      secondaryLink: { href: '/privacy', label: '개인정보 처리방침' },
    },
  },
  es: {
    privacy: {
      title: 'Política de privacidad',
      description: 'Cómo U2Tool maneja el uso de herramientas en el navegador, diagnósticos opcionales e información de contacto.',
      eyebrow: 'Confianza de la plataforma',
      updated: 'Actualizado el 8 de mayo de 2026',
      sections: [
        {
          title: 'Procesamiento primero en el navegador',
          paragraphs: [
            'U2Tool está diseñado para que la mayoría de las herramientas se ejecuten directamente en tu navegador. Los textos, archivos, imágenes y resultados generados normalmente permanecen en tu dispositivo salvo que una herramienta necesite claramente una solicitud de red.',
            'No pedimos crear una cuenta para usar el catálogo público de herramientas y no vendemos información personal.',
          ],
        },
        {
          title: 'Datos operativos',
          paragraphs: [
            'Como la mayoría de los sitios web, los proveedores de alojamiento pueden procesar datos básicos de solicitud como dirección IP, agente de usuario, URL, referente y marcas de tiempo para seguridad, prevención de abuso, depuración y fiabilidad del tráfico.',
            'Si nos escribes a contact@u2tool.com, usamos la información que proporciones solo para responder tu mensaje y mejorar el servicio.',
          ],
        },
        {
          title: 'Servicios de terceros',
          paragraphs: [
            'Algunas herramientas pueden llamar a una API pública cuando sea esencial para la función, por ejemplo en flujos de búsqueda o validación. Si una herramienta depende de un servicio externo, evita introducir secretos o datos personales sensibles.',
            'Podemos actualizar esta política a medida que el producto cambie. Los cambios importantes se reflejarán en esta página.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Explorar herramientas' },
      secondaryLink: { href: '/contact', label: 'Contactar con U2Tool' },
    },
    terms: {
      title: 'Términos del servicio',
      description: 'Los términos básicos para usar las utilidades en línea, los resultados generados y el contenido público de U2Tool.',
      eyebrow: 'Términos del servicio',
      updated: 'Actualizado el 8 de mayo de 2026',
      sections: [
        {
          title: 'Uso del servicio',
          paragraphs: [
            'U2Tool ofrece utilidades gratuitas para formatear, convertir, generar, validar e inspeccionar datos. Eres responsable de cómo usas las herramientas y de cualquier resultado que creen.',
            'No uses el servicio para atacar sistemas, eludir controles de acceso, infringir leyes o procesar datos que no estás autorizado a manejar.',
          ],
        },
        {
          title: 'Sin asesoramiento profesional',
          paragraphs: [
            'La salida de las herramientas se ofrece por conveniencia y puede contener errores. Revisa los resultados importantes antes de depender de ellos en contextos de producción, legales, financieros, médicos o sensibles para la seguridad.',
            'Las plantillas generadas por herramientas legales, de políticas o de negocio son puntos de partida y deben ser revisadas por un profesional cualificado antes de usarse.',
          ],
        },
        {
          title: 'Disponibilidad y cambios',
          paragraphs: [
            'Podemos añadir, cambiar, desactivar o eliminar herramientas a medida que el producto evolucione. El sitio se proporciona tal cual, sin garantía de que cada herramienta esté siempre disponible o libre de errores.',
            'El uso continuado de U2Tool después de actualizar estos términos significa que aceptas los términos actualizados.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Explorar herramientas' },
      secondaryLink: { href: '/privacy', label: 'Política de privacidad' },
    },
    contact: {
      title: 'Contactar con U2Tool',
      description: 'Comunícate con U2Tool para comentarios de producto, informes de errores, preguntas de indexación y solicitudes de colaboración.',
      eyebrow: 'Soporte',
      updated: 'Canal de contacto actual',
      sections: [
        {
          title: 'Correo electrónico',
          paragraphs: [
            'Para soporte, informes de errores, preguntas de contenido o solicitudes de colaboración, escribe a contact@u2tool.com.',
            'Incluye la URL de la herramienta, tu navegador, la forma exacta de la entrada si es seguro compartirla y lo que esperabas que ocurriera. No envíes contraseñas, claves privadas, tokens ni archivos sensibles.',
          ],
        },
        {
          title: 'Solicitudes de indexación y SEO',
          paragraphs: [
            'Si informas de una URL rota, un problema de redirección o un resultado de búsqueda incorrecto, incluye la URL afectada y dónde la encontraste.',
            'Priorizamos los problemas que afectan a herramientas activas, páginas localizadas, sitemaps, datos estructurados y expectativas de privacidad en el navegador.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Explorar herramientas' },
      secondaryLink: { href: '/privacy', label: 'Política de privacidad' },
    },
  },
  pt: {
    privacy: {
      title: 'Política de privacidade',
      description: 'Como o U2Tool lida com o uso de ferramentas no navegador, diagnósticos opcionais e informações de contato.',
      eyebrow: 'Confiança da plataforma',
      updated: 'Atualizado em 8 de maio de 2026',
      sections: [
        {
          title: 'Processamento primeiro no navegador',
          paragraphs: [
            'O U2Tool foi criado para que a maioria das ferramentas rode diretamente no seu navegador. Textos, arquivos, imagens e resultados gerados normalmente ficam no seu dispositivo, a menos que uma ferramenta precise claramente de uma solicitação de rede.',
            'Não pedimos que você crie uma conta para usar o catálogo público de ferramentas e não vendemos informações pessoais.',
          ],
        },
        {
          title: 'Dados operacionais',
          paragraphs: [
            'Como a maioria dos sites, provedores de hospedagem podem processar dados básicos de solicitação, como endereço IP, agente do usuário, URL, referenciador e horários, para segurança, prevenção de abuso, depuração e confiabilidade do tráfego.',
            'Se você entrar em contato por contact@u2tool.com, usamos as informações fornecidas apenas para responder à mensagem e melhorar o serviço.',
          ],
        },
        {
          title: 'Serviços de terceiros',
          paragraphs: [
            'Algumas ferramentas podem chamar uma API pública quando isso é essencial para o recurso, como fluxos de consulta ou validação. Quando uma ferramenta depende de serviço externo, evite inserir segredos ou dados pessoais sensíveis.',
            'Podemos atualizar esta política conforme o produto muda. Alterações relevantes serão refletidas nesta página.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Explorar ferramentas' },
      secondaryLink: { href: '/contact', label: 'Contatar o U2Tool' },
    },
    terms: {
      title: 'Termos de serviço',
      description: 'Os termos básicos para usar as utilidades online, resultados gerados e conteúdo público do U2Tool.',
      eyebrow: 'Termos do serviço',
      updated: 'Atualizado em 8 de maio de 2026',
      sections: [
        {
          title: 'Uso do serviço',
          paragraphs: [
            'O U2Tool fornece utilidades online gratuitas para formatar, converter, gerar, validar e inspecionar dados. Você é responsável por como usa as ferramentas e por qualquer saída criada por elas.',
            'Não use o serviço para atacar sistemas, contornar controles de acesso, violar leis ou processar dados que você não tem permissão para manipular.',
          ],
        },
        {
          title: 'Sem aconselhamento profissional',
          paragraphs: [
            'A saída das ferramentas é fornecida por conveniência e pode conter erros. Revise resultados importantes antes de confiar neles em contextos de produção, jurídicos, financeiros, médicos ou sensíveis à segurança.',
            'Modelos gerados por ferramentas jurídicas, de política ou de negócios são pontos de partida e devem ser revisados por um profissional qualificado antes do uso.',
          ],
        },
        {
          title: 'Disponibilidade e mudanças',
          paragraphs: [
            'Podemos adicionar, alterar, desativar ou remover ferramentas conforme o produto evolui. O site é fornecido no estado em que se encontra, sem garantia de que cada ferramenta estará sempre disponível ou livre de erros.',
            'O uso contínuo do U2Tool após atualizações destes termos significa que você aceita os termos atualizados.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Explorar ferramentas' },
      secondaryLink: { href: '/privacy', label: 'Política de privacidade' },
    },
    contact: {
      title: 'Contatar o U2Tool',
      description: 'Fale com o U2Tool para feedback de produto, relatórios de erro, perguntas de indexação e parcerias.',
      eyebrow: 'Suporte',
      updated: 'Canal de contato atual',
      sections: [
        {
          title: 'E-mail',
          paragraphs: [
            'Para suporte, relatórios de erro, perguntas de conteúdo ou pedidos de parceria, envie e-mail para contact@u2tool.com.',
            'Inclua a URL da ferramenta, seu navegador, o formato exato da entrada se for seguro compartilhar e o que você esperava que acontecesse. Não envie senhas, chaves privadas, tokens ou arquivos sensíveis.',
          ],
        },
        {
          title: 'Solicitações de indexação e SEO',
          paragraphs: [
            'Se estiver relatando uma URL quebrada, problema de redirecionamento ou resultado de busca incorreto, inclua a URL afetada e onde a encontrou.',
            'Priorizamos problemas que afetam ferramentas ativas, páginas localizadas, sitemaps, dados estruturados e expectativas de privacidade no navegador.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Explorar ferramentas' },
      secondaryLink: { href: '/privacy', label: 'Política de privacidade' },
    },
  },
  fr: {
    privacy: {
      title: 'Politique de confidentialité',
      description: 'Comment U2Tool traite l’usage des outils dans le navigateur, les diagnostics facultatifs et les informations de contact.',
      eyebrow: 'Confiance de la plateforme',
      updated: 'Mis à jour le 8 mai 2026',
      sections: [
        {
          title: 'Traitement prioritaire dans le navigateur',
          paragraphs: [
            'U2Tool est conçu pour que la plupart des outils s’exécutent directement dans votre navigateur. Les textes, fichiers, images et résultats générés restent normalement sur votre appareil, sauf si un outil a clairement besoin d’une requête réseau.',
            'Nous ne demandons pas de créer un compte pour utiliser le catalogue public d’outils et nous ne vendons pas d’informations personnelles.',
          ],
        },
        {
          title: 'Données opérationnelles',
          paragraphs: [
            'Comme la plupart des sites web, les fournisseurs d’hébergement peuvent traiter des données de requête de base comme l’adresse IP, l’agent utilisateur, l’URL, le référent et les horodatages pour la sécurité, la prévention des abus, le débogage et la fiabilité du trafic.',
            'Si vous nous contactez à contact@u2tool.com, nous utilisons les informations fournies uniquement pour répondre à votre message et améliorer le service.',
          ],
        },
        {
          title: 'Services tiers',
          paragraphs: [
            'Certains outils peuvent appeler une API publique lorsque cela est essentiel à la fonctionnalité, par exemple pour une recherche ou une validation. Lorsqu’un outil dépend d’un service externe, évitez de saisir des secrets ou des données personnelles sensibles.',
            'Nous pouvons mettre à jour cette politique à mesure que le produit évolue. Les changements importants seront indiqués sur cette page.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Parcourir les outils' },
      secondaryLink: { href: '/contact', label: 'Contacter U2Tool' },
    },
    terms: {
      title: 'Conditions d’utilisation',
      description: 'Les conditions de base pour utiliser les utilitaires en ligne, les résultats générés et le contenu public de U2Tool.',
      eyebrow: 'Conditions du service',
      updated: 'Mis à jour le 8 mai 2026',
      sections: [
        {
          title: 'Utilisation du service',
          paragraphs: [
            'U2Tool fournit des utilitaires en ligne gratuits pour formater, convertir, générer, valider et inspecter des données. Vous êtes responsable de votre utilisation des outils et de toute sortie qu’ils créent.',
            'N’utilisez pas le service pour attaquer des systèmes, contourner des contrôles d’accès, enfreindre la loi ou traiter des données que vous n’êtes pas autorisé à manipuler.',
          ],
        },
        {
          title: 'Aucun conseil professionnel',
          paragraphs: [
            'Les résultats des outils sont fournis par commodité et peuvent contenir des erreurs. Vérifiez les sorties importantes avant de vous y fier en production ou dans des contextes juridiques, financiers, médicaux ou sensibles à la sécurité.',
            'Les modèles générés par les outils juridiques, de politique ou de gestion sont des points de départ et doivent être examinés par un professionnel qualifié avant utilisation.',
          ],
        },
        {
          title: 'Disponibilité et changements',
          paragraphs: [
            'Nous pouvons ajouter, modifier, désactiver ou supprimer des outils à mesure que le produit évolue. Le site est fourni tel quel, sans garantie que chaque outil soit toujours disponible ou exempt d’erreurs.',
            'Continuer à utiliser U2Tool après la mise à jour de ces conditions signifie que vous acceptez les conditions mises à jour.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Parcourir les outils' },
      secondaryLink: { href: '/privacy', label: 'Politique de confidentialité' },
    },
    contact: {
      title: 'Contacter U2Tool',
      description: 'Contactez U2Tool pour des retours produit, des rapports de bug, des questions d’indexation et des demandes de partenariat.',
      eyebrow: 'Support',
      updated: 'Canal de contact actuel',
      sections: [
        {
          title: 'E-mail',
          paragraphs: [
            'Pour le support, les rapports de bug, les questions de contenu ou les demandes de partenariat, envoyez un e-mail à contact@u2tool.com.',
            'Incluez l’URL de l’outil, votre navigateur, la forme exacte de l’entrée si elle peut être partagée en sécurité, et ce que vous attendiez. N’envoyez pas de mots de passe, clés privées, jetons ou fichiers sensibles.',
          ],
        },
        {
          title: 'Demandes d’indexation et SEO',
          paragraphs: [
            'Si vous signalez une URL cassée, un problème de redirection ou un résultat de recherche incorrect, incluez l’URL concernée et l’endroit où vous l’avez trouvée.',
            'Nous priorisons les problèmes qui touchent les outils actifs, les pages localisées, les sitemaps, les données structurées et les attentes de confidentialité côté navigateur.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Parcourir les outils' },
      secondaryLink: { href: '/privacy', label: 'Politique de confidentialité' },
    },
  },
  de: {
    privacy: {
      title: 'Datenschutzerklärung',
      description: 'Wie U2Tool browserbasierte Tool-Nutzung, optionale Diagnosedaten und Kontaktinformationen verarbeitet.',
      eyebrow: 'Plattformvertrauen',
      updated: 'Aktualisiert am 8. Mai 2026',
      sections: [
        {
          title: 'Browser zuerst',
          paragraphs: [
            'U2Tool ist so entwickelt, dass die meisten Tools direkt in Ihrem Browser laufen. Texte, Dateien, Bilder und erzeugte Ergebnisse bleiben normalerweise auf Ihrem Gerät, außer ein bestimmtes Tool benötigt eindeutig eine Netzwerkanfrage.',
            'Für den öffentlichen Tool-Katalog verlangen wir kein Konto und wir verkaufen keine personenbezogenen Informationen.',
          ],
        },
        {
          title: 'Betriebsdaten',
          paragraphs: [
            'Wie die meisten Websites können Hosting-Anbieter grundlegende Anfrageinformationen wie IP-Adresse, User-Agent, URL, Referrer und Zeitstempel für Sicherheit, Missbrauchsprävention, Debugging und verlässlichen Traffic verarbeiten.',
            'Wenn Sie uns unter contact@u2tool.com kontaktieren, verwenden wir die bereitgestellten Informationen nur zur Beantwortung Ihrer Nachricht und zur Verbesserung des Dienstes.',
          ],
        },
        {
          title: 'Dienste Dritter',
          paragraphs: [
            'Einige Tools können eine öffentliche API aufrufen, wenn dies für die Funktion wesentlich ist, etwa bei Such- oder Validierungsabläufen. Wenn ein Tool von einem externen Dienst abhängt, geben Sie keine Geheimnisse oder sensiblen personenbezogenen Daten ein.',
            'Wir können diese Richtlinie aktualisieren, wenn sich das Produkt ändert. Wesentliche Änderungen werden auf dieser Seite dargestellt.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Tools durchsuchen' },
      secondaryLink: { href: '/contact', label: 'U2Tool kontaktieren' },
    },
    terms: {
      title: 'Nutzungsbedingungen',
      description: 'Die grundlegenden Bedingungen für Online-Utilities, generierte Ergebnisse und öffentliche Website-Inhalte von U2Tool.',
      eyebrow: 'Servicebedingungen',
      updated: 'Aktualisiert am 8. Mai 2026',
      sections: [
        {
          title: 'Nutzung des Dienstes',
          paragraphs: [
            'U2Tool stellt kostenlose Online-Utilities zum Formatieren, Konvertieren, Generieren, Validieren und Prüfen von Daten bereit. Sie sind dafür verantwortlich, wie Sie die Tools und ihre Ausgaben verwenden.',
            'Verwenden Sie den Dienst nicht, um Systeme anzugreifen, Zugriffskontrollen zu umgehen, Gesetze zu verletzen oder Daten zu verarbeiten, für die Sie keine Berechtigung haben.',
          ],
        },
        {
          title: 'Keine professionelle Beratung',
          paragraphs: [
            'Tool-Ausgaben werden zur Vereinfachung bereitgestellt und können Fehler enthalten. Prüfen Sie wichtige Ausgaben, bevor Sie sich in Produktions-, Rechts-, Finanz-, Medizin- oder sicherheitsrelevanten Kontexten darauf verlassen.',
            'Vorlagen aus Rechts-, Policy- oder Business-Tools sind Ausgangspunkte und sollten vor der Nutzung von einer qualifizierten Fachperson geprüft werden.',
          ],
        },
        {
          title: 'Verfügbarkeit und Änderungen',
          paragraphs: [
            'Wir können Tools hinzufügen, ändern, deaktivieren oder entfernen, wenn sich das Produkt weiterentwickelt. Die Website wird wie besehen bereitgestellt, ohne Garantie, dass jedes Tool jederzeit verfügbar oder fehlerfrei ist.',
            'Die weitere Nutzung von U2Tool nach Aktualisierungen dieser Bedingungen bedeutet, dass Sie die aktualisierten Bedingungen akzeptieren.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Tools durchsuchen' },
      secondaryLink: { href: '/privacy', label: 'Datenschutzerklärung' },
    },
    contact: {
      title: 'U2Tool kontaktieren',
      description: 'Kontaktieren Sie U2Tool für Produktfeedback, Fehlerberichte, Indexierungsfragen und Partnerschaftsanfragen.',
      eyebrow: 'Support',
      updated: 'Aktueller Kontaktkanal',
      sections: [
        {
          title: 'E-Mail',
          paragraphs: [
            'Für Support, Fehlerberichte, Inhaltsfragen oder Partnerschaftsanfragen schreiben Sie an contact@u2tool.com.',
            'Fügen Sie die Tool-URL, Ihren Browser, die genaue Eingabeform, sofern sie sicher teilbar ist, und das erwartete Verhalten hinzu. Senden Sie keine Passwörter, privaten Schlüssel, Tokens oder sensiblen Dateien.',
          ],
        },
        {
          title: 'Indexierungs- und SEO-Anfragen',
          paragraphs: [
            'Wenn Sie eine defekte URL, ein Redirect-Problem oder ein Suchergebnisproblem melden, nennen Sie die betroffene URL und wo Sie sie gefunden haben.',
            'Wir priorisieren Probleme, die aktive Tools, lokalisierte Seiten, Sitemaps, strukturierte Daten und browserseitige Datenschutz-Erwartungen betreffen.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Tools durchsuchen' },
      secondaryLink: { href: '/privacy', label: 'Datenschutzerklärung' },
    },
  },
  ru: {
    privacy: {
      title: 'Политика конфиденциальности',
      description: 'Как U2Tool обрабатывает использование инструментов в браузере, необязательные диагностические данные и контактную информацию.',
      eyebrow: 'Доверие к платформе',
      updated: 'Обновлено 8 мая 2026 г.',
      sections: [
        {
          title: 'Обработка сначала в браузере',
          paragraphs: [
            'U2Tool устроен так, чтобы большинство инструментов работало прямо в вашем браузере. Тексты, файлы, изображения и созданные результаты обычно остаются на вашем устройстве, если конкретному инструменту явно не нужен сетевой запрос.',
            'Мы не требуем создавать учетную запись для использования публичного каталога инструментов и не продаем персональную информацию.',
          ],
        },
        {
          title: 'Операционные данные',
          paragraphs: [
            'Как и большинство сайтов, хостинг-провайдеры могут обрабатывать базовые данные запроса, такие как IP-адрес, user agent, URL, источник перехода и временные метки, для безопасности, предотвращения злоупотреблений, отладки и надежности трафика.',
            'Если вы пишете нам на contact@u2tool.com, мы используем предоставленную информацию только для ответа на сообщение и улучшения сервиса.',
          ],
        },
        {
          title: 'Сторонние сервисы',
          paragraphs: [
            'Некоторые инструменты могут обращаться к публичному API, когда это необходимо для функции, например для поиска или проверки. Если инструмент зависит от внешнего сервиса, не вводите секреты или чувствительные персональные данные.',
            'Мы можем обновлять эту политику по мере изменения продукта. Существенные изменения будут отражены на этой странице.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Открыть инструменты' },
      secondaryLink: { href: '/contact', label: 'Связаться с U2Tool' },
    },
    terms: {
      title: 'Условия использования',
      description: 'Основные условия использования онлайн-утилит U2Tool, созданных результатов и публичного контента сайта.',
      eyebrow: 'Условия сервиса',
      updated: 'Обновлено 8 мая 2026 г.',
      sections: [
        {
          title: 'Использование сервиса',
          paragraphs: [
            'U2Tool предоставляет бесплатные онлайн-утилиты для форматирования, конвертации, генерации, проверки и анализа данных. Вы отвечаете за то, как используете инструменты и любые созданные ими результаты.',
            'Не используйте сервис для атак на системы, обхода контроля доступа, нарушения законов или обработки данных, с которыми вам нельзя работать.',
          ],
        },
        {
          title: 'Не является профессиональной консультацией',
          paragraphs: [
            'Результаты инструментов предоставляются для удобства и могут содержать ошибки. Проверяйте важные результаты перед использованием в производстве, юридических, финансовых, медицинских или чувствительных к безопасности ситуациях.',
            'Шаблоны, созданные юридическими, политическими или бизнес-инструментами, являются отправной точкой и должны быть проверены квалифицированным специалистом перед использованием.',
          ],
        },
        {
          title: 'Доступность и изменения',
          paragraphs: [
            'Мы можем добавлять, изменять, отключать или удалять инструменты по мере развития продукта. Сайт предоставляется как есть, без гарантии, что каждый инструмент всегда будет доступен или свободен от ошибок.',
            'Продолжение использования U2Tool после обновления этих условий означает согласие с обновленными условиями.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Открыть инструменты' },
      secondaryLink: { href: '/privacy', label: 'Политика конфиденциальности' },
    },
    contact: {
      title: 'Связаться с U2Tool',
      description: 'Напишите U2Tool с отзывом о продукте, отчетом об ошибке, вопросом об индексации или предложением партнерства.',
      eyebrow: 'Поддержка',
      updated: 'Текущий канал связи',
      sections: [
        {
          title: 'Электронная почта',
          paragraphs: [
            'Для поддержки, отчетов об ошибках, вопросов по контенту или предложений партнерства напишите на contact@u2tool.com.',
            'Укажите URL инструмента, браузер, точную форму ввода, если ею безопасно поделиться, и ожидаемый результат. Не отправляйте пароли, приватные ключи, токены или чувствительные файлы.',
          ],
        },
        {
          title: 'Запросы по индексации и SEO',
          paragraphs: [
            'Если вы сообщаете о сломанном URL, проблеме редиректа или результате поиска, укажите затронутый URL и где вы его нашли.',
            'Мы в первую очередь рассматриваем проблемы, влияющие на активные инструменты, локализованные страницы, карты сайта, структурированные данные и ожидания приватности в браузере.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'Открыть инструменты' },
      secondaryLink: { href: '/privacy', label: 'Политика конфиденциальности' },
    },
  },
  ar: {
    privacy: {
      title: 'سياسة الخصوصية',
      description: 'كيف يتعامل U2Tool مع استخدام الأدوات داخل المتصفح وبيانات التشخيص الاختيارية ومعلومات التواصل.',
      eyebrow: 'ثقة المنصة',
      updated: 'تم التحديث في 8 مايو 2026',
      sections: [
        {
          title: 'المعالجة داخل المتصفح أولا',
          paragraphs: [
            'صمم U2Tool بحيث تعمل معظم الأدوات مباشرة داخل متصفحك. تبقى النصوص والملفات والصور والمخرجات عادة على جهازك ما لم تكن أداة محددة تحتاج بوضوح إلى طلب عبر الشبكة.',
            'لا نطلب إنشاء حساب لاستخدام كتالوج الأدوات العام، ولا نبيع المعلومات الشخصية.',
          ],
        },
        {
          title: 'بيانات التشغيل',
          paragraphs: [
            'مثل معظم المواقع، قد يعالج مزودو الاستضافة بيانات طلب أساسية مثل عنوان IP ووكيل المستخدم والرابط والمصدر والطوابع الزمنية لأغراض الأمان ومنع إساءة الاستخدام وتصحيح الأخطاء وموثوقية الزيارات.',
            'إذا تواصلت معنا عبر contact@u2tool.com، نستخدم المعلومات التي تقدمها فقط للرد على رسالتك وتحسين الخدمة.',
          ],
        },
        {
          title: 'خدمات الطرف الثالث',
          paragraphs: [
            'قد تستدعي بعض الأدوات واجهة API عامة عندما يكون ذلك ضروريا للميزة، مثل مسارات البحث أو التحقق. عندما تعتمد أداة على خدمة خارجية، تجنب إدخال الأسرار أو البيانات الشخصية الحساسة.',
            'قد نحدث هذه السياسة مع تغير المنتج. ستظهر التغييرات المهمة على هذه الصفحة.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'تصفح الأدوات' },
      secondaryLink: { href: '/contact', label: 'التواصل مع U2Tool' },
    },
    terms: {
      title: 'شروط الخدمة',
      description: 'الشروط الأساسية لاستخدام أدوات U2Tool عبر الإنترنت والمخرجات المنشأة ومحتوى الموقع العام.',
      eyebrow: 'شروط الخدمة',
      updated: 'تم التحديث في 8 مايو 2026',
      sections: [
        {
          title: 'استخدام الخدمة',
          paragraphs: [
            'يوفر U2Tool أدوات مجانية عبر الإنترنت لتنسيق البيانات وتحويلها وإنشائها والتحقق منها وفحصها. أنت مسؤول عن طريقة استخدام الأدوات وعن أي مخرجات تنشئها.',
            'لا تستخدم الخدمة لمهاجمة الأنظمة أو تجاوز ضوابط الوصول أو مخالفة القوانين أو معالجة بيانات لا يحق لك التعامل معها.',
          ],
        },
        {
          title: 'ليست نصيحة مهنية',
          paragraphs: [
            'تقدم مخرجات الأدوات لغرض التسهيل وقد تحتوي على أخطاء. راجع المخرجات المهمة قبل الاعتماد عليها في الإنتاج أو السياقات القانونية أو المالية أو الطبية أو الحساسة أمنيا.',
            'القوالب التي تنشئها أدوات قانونية أو سياسات أو أعمال هي نقطة بداية ويجب أن يراجعها مختص مؤهل قبل الاستخدام.',
          ],
        },
        {
          title: 'التوفر والتغييرات',
          paragraphs: [
            'قد نضيف أدوات أو نغيرها أو نعطلها أو نزيلها مع تطور المنتج. يقدم الموقع كما هو دون ضمان أن تكون كل أداة متاحة دائما أو خالية من الأخطاء.',
            'يعني استمرار استخدام U2Tool بعد تحديث هذه الشروط أنك تقبل الشروط المحدثة.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'تصفح الأدوات' },
      secondaryLink: { href: '/privacy', label: 'سياسة الخصوصية' },
    },
    contact: {
      title: 'التواصل مع U2Tool',
      description: 'تواصل مع U2Tool لآراء المنتج وتقارير الأخطاء وأسئلة الفهرسة وطلبات الشراكة.',
      eyebrow: 'الدعم',
      updated: 'قناة التواصل الحالية',
      sections: [
        {
          title: 'البريد الإلكتروني',
          paragraphs: [
            'للدعم أو تقارير الأخطاء أو أسئلة المحتوى أو طلبات الشراكة، أرسل بريدا إلى contact@u2tool.com.',
            'أرفق رابط الأداة والمتصفح وشكل الإدخال الدقيق إذا كان آمنا للمشاركة وما كنت تتوقع حدوثه. لا ترسل كلمات مرور أو مفاتيح خاصة أو رموز وصول أو ملفات حساسة.',
          ],
        },
        {
          title: 'طلبات الفهرسة و SEO',
          paragraphs: [
            'إذا كنت تبلغ عن رابط معطل أو مشكلة إعادة توجيه أو مشكلة في نتيجة بحث، فأرفق الرابط المتأثر والمكان الذي وجدته فيه.',
            'نعطي الأولوية للمشكلات التي تؤثر في الأدوات النشطة والصفحات المحلية وخرائط الموقع والبيانات المنظمة وتوقعات الخصوصية داخل المتصفح.',
          ],
        },
      ],
      primaryLink: { href: '/tools', label: 'تصفح الأدوات' },
      secondaryLink: { href: '/privacy', label: 'سياسة الخصوصية' },
    },
  },
} satisfies Record<Locale, Record<SiteInfoPageSlug, SiteInfoPageCopy>>;

export function getSiteInfoPageCopy(slug: SiteInfoPageSlug, locale: Locale = defaultLocale): SiteInfoPageCopy {
  return siteInfoPagesByLocale[locale]?.[slug] ?? siteInfoPagesByLocale[defaultLocale][slug];
}
