export const siteInfoPageSlugs = ['privacy', 'terms', 'contact'] as const;
export type SiteInfoPageSlug = (typeof siteInfoPageSlugs)[number];

export interface SiteInfoPageCopy {
  title: string;
  description: string;
  eyebrow: string;
  updated: string;
  sections: Array<{
    title: string;
    paragraphs: string[];
  }>;
  primaryLink: {
    href: string;
    label: string;
  };
  secondaryLink: {
    href: string;
    label: string;
  };
}

const siteInfoPages: Record<SiteInfoPageSlug, SiteInfoPageCopy> = {
  privacy: {
    title: 'Privacy Policy',
    description: 'How U2Tool handles browser-based tool usage, optional diagnostics, and contact information.',
    eyebrow: 'Platform trust',
    updated: 'Updated May 8, 2026',
    sections: [
      {
        title: 'Browser-first processing',
        paragraphs: [
          'U2Tool is designed so most tools run directly in your browser. Text, files, images, and generated outputs normally stay on your device unless a specific tool clearly needs a network request.',
          'We do not ask you to create an account to use the public tool catalog, and we do not sell personal information.',
        ],
      },
      {
        title: 'Operational data',
        paragraphs: [
          'Like most websites, hosting providers may process basic request data such as IP address, user agent, URL, referrer, and timestamps for security, abuse prevention, debugging, and traffic reliability.',
          'If you contact us at contact@u2tool.com, we use the information you provide only to respond to your message and improve the service.',
        ],
      },
      {
        title: 'Third-party services',
        paragraphs: [
          'Some tools may call a public API when that is essential to the feature, such as lookup or validation workflows. When a tool depends on an external service, avoid entering secrets or sensitive personal data.',
          'We may update this policy as the product changes. Material changes will be reflected on this page.',
        ],
      },
    ],
    primaryLink: { href: '/tools', label: 'Browse tools' },
    secondaryLink: { href: '/contact', label: 'Contact U2Tool' },
  },
  terms: {
    title: 'Terms of Service',
    description: 'The basic terms for using U2Tool online utilities, generated outputs, and public website content.',
    eyebrow: 'Service terms',
    updated: 'Updated May 8, 2026',
    sections: [
      {
        title: 'Use of the service',
        paragraphs: [
          'U2Tool provides free online utilities for formatting, converting, generating, validating, and inspecting data. You are responsible for how you use the tools and any output they create.',
          'Do not use the service to attack systems, bypass access controls, violate laws, or process data that you are not allowed to handle.',
        ],
      },
      {
        title: 'No professional advice',
        paragraphs: [
          'Tool output is provided for convenience and may contain mistakes. Review important output before relying on it in production, legal, financial, medical, or security-sensitive contexts.',
          'Templates generated by legal, policy, or business tools are starting points and should be reviewed by a qualified professional before use.',
        ],
      },
      {
        title: 'Availability and changes',
        paragraphs: [
          'We may add, change, disable, or remove tools as the product evolves. The website is provided as-is without a guarantee that every tool will always be available or error-free.',
          'Continued use of U2Tool after updates to these terms means you accept the updated terms.',
        ],
      },
    ],
    primaryLink: { href: '/tools', label: 'Browse tools' },
    secondaryLink: { href: '/privacy', label: 'Privacy Policy' },
  },
  contact: {
    title: 'Contact U2Tool',
    description: 'Reach U2Tool for product feedback, bug reports, indexing questions, and partnership requests.',
    eyebrow: 'Support',
    updated: 'Current contact channel',
    sections: [
      {
        title: 'Email',
        paragraphs: [
          'For support, bug reports, content questions, or partnership requests, email contact@u2tool.com.',
          'Include the tool URL, your browser, the exact input shape if it is safe to share, and what you expected to happen. Please do not send passwords, private keys, tokens, or sensitive files.',
        ],
      },
      {
        title: 'Indexing and SEO requests',
        paragraphs: [
          'If you are reporting a broken URL, redirect issue, or search result problem, include the affected URL and where you found it.',
          'We prioritize issues that affect active tools, localized pages, sitemaps, structured data, and browser-side privacy expectations.',
        ],
      },
    ],
    primaryLink: { href: '/tools', label: 'Browse tools' },
    secondaryLink: { href: '/privacy', label: 'Privacy Policy' },
  },
};

export function getSiteInfoPageCopy(slug: SiteInfoPageSlug): SiteInfoPageCopy {
  return siteInfoPages[slug];
}
