import * as echarts from 'echarts/core';
import {
  BarChart,
  BoxplotChart,
  CandlestickChart,
  CustomChart,
  FunnelChart,
  GaugeChart,
  GraphChart,
  HeatmapChart,
  LineChart,
  ParallelChart,
  PictorialBarChart,
  PieChart,
  RadarChart,
  SankeyChart,
  ScatterChart,
  SunburstChart,
  ThemeRiverChart,
  TreeChart,
  TreemapChart,
} from 'echarts/charts';
import {
  AriaComponent,
  AxisPointerComponent,
  CalendarComponent,
  DataZoomComponent,
  DataZoomInsideComponent,
  DataZoomSliderComponent,
  DatasetComponent,
  GraphicComponent,
  GridComponent,
  LegendComponent,
  MarkAreaComponent,
  MarkLineComponent,
  MarkPointComponent,
  ParallelComponent,
  PolarComponent,
  RadarComponent,
  SingleAxisComponent,
  TitleComponent,
  TooltipComponent,
  TransformComponent,
  VisualMapComponent,
} from 'echarts/components';
import { LabelLayout } from 'echarts/features';
import { CanvasRenderer } from 'echarts/renderers';

echarts.use([
  AriaComponent,
  AxisPointerComponent,
  BarChart,
  BoxplotChart,
  CalendarComponent,
  CandlestickChart,
  CanvasRenderer,
  CustomChart,
  DataZoomComponent,
  DataZoomInsideComponent,
  DataZoomSliderComponent,
  DatasetComponent,
  FunnelChart,
  GaugeChart,
  GraphicComponent,
  GraphChart,
  GridComponent,
  HeatmapChart,
  LabelLayout,
  LegendComponent,
  LineChart,
  MarkAreaComponent,
  MarkLineComponent,
  MarkPointComponent,
  ParallelChart,
  ParallelComponent,
  PictorialBarChart,
  PieChart,
  PolarComponent,
  RadarChart,
  RadarComponent,
  SankeyChart,
  ScatterChart,
  SingleAxisComponent,
  SunburstChart,
  ThemeRiverChart,
  TitleComponent,
  TooltipComponent,
  TransformComponent,
  TreeChart,
  TreemapChart,
  VisualMapComponent,
]);

export default echarts;
