// AUTO-GENERATED - Do not edit manually
// Generated by scripts/generate-ai-discovery-aliases.ts

export const GENERATED_DISCOVERY_ALIASES: Record<string, string[]> = {
  "ai-robots-txt-generator": [
    "ai crawler robots txt",
    "ai robots.txt generator",
    "block ai crawlers robots.txt",
    "gptbot robots.txt generator"
  ],
  "ai-token-calculator": [
    "ai token cost calculator",
    "claude token cost calculator",
    "llm token cost calculator",
    "openai token calculator"
  ],
  "har-file-viewer": [
    "har analyzer",
    "har file viewer",
    "har viewer online",
    "http archive viewer"
  ],
  "json-repair": [
    "fix json online",
    "json fixer",
    "json repair tool",
    "repair malformed json"
  ],
  "jsonl-validator": [
    "json lines validator",
    "jsonl checker",
    "jsonl validator",
    "ndjson validator"
  ],
  "llms-txt-validator": [
    "llms txt checker",
    "llms.txt checker",
    "llms.txt format validator",
    "llms.txt validator"
  ],
  "mcp-json-validator": [
    "mcp config validator",
    "mcp json checker",
    "mcp json validator",
    "model context protocol config validator"
  ],
  "mcp-server-config-generator": [
    "claude mcp config generator",
    "cursor mcp json generator",
    "mcp config generator",
    "mcp server config generator"
  ],
  "world-cup-2026-bracket-predictor": [
    "2026 world cup bracket",
    "fifa world cup 2026 predictor",
    "world cup 2026 bracket predictor",
    "world cup bracket maker"
  ]
};
