export const commonPasswords = [
  '123456',
  '123456789',
  '12345678',
  'password',
  'qwerty',
  'abc123',
  '111111',
  '123123',
  'admin',
  'letmein',
  'welcome',
  'monkey',
  'dragon',
  'iloveyou',
  'password1',
  'password123',
  'qwerty123',
  'football',
  'baseball',
  'login',
  'princess',
  'solo',
  'starwars',
  'trustno1',
];

export const commonTypos: Record<string, string> = {
  'gamil.com': 'gmail.com',
  'gmial.com': 'gmail.com',
  'gmail.co': 'gmail.com',
  'gmail.con': 'gmail.com',
  'hotmial.com': 'hotmail.com',
  'hotmil.com': 'hotmail.com',
  'hotmail.co': 'hotmail.com',
  'outlok.com': 'outlook.com',
  'outloo.com': 'outlook.com',
  'outlook.co': 'outlook.com',
  'yaho.com': 'yahoo.com',
  'yahoo.co': 'yahoo.com',
  'icloud.co': 'icloud.com',
  'protonmial.com': 'protonmail.com',
  'proton.me.co': 'proton.me',
};

export const disposableDomains = [
  '10minutemail.com',
  '20minutemail.com',
  'guerrillamail.com',
  'mailinator.com',
  'tempmail.com',
  'temp-mail.org',
  'throwawaymail.com',
  'trashmail.com',
  'yopmail.com',
  'getnada.com',
  'maildrop.cc',
  'sharklasers.com',
];

export const freeProviders = [
  'gmail.com',
  'yahoo.com',
  'hotmail.com',
  'outlook.com',
  'icloud.com',
  'proton.me',
  'protonmail.com',
  'aol.com',
  'live.com',
  'msn.com',
  'mail.com',
  'gmx.com',
  'zoho.com',
  'yandex.com',
  'fastmail.com',
];
