'use client';

import { useState } from 'react';
import { useTranslations } from 'next-intl';

interface Template {
  id: string;
  name: string;
  content: string;
}

const TEMPLATES: Template[] = [
  {
    id: 'node',
    name: 'Node.js',
    content: `# Dependencies
node_modules/
package-lock.json
yarn.lock
pnpm-lock.yaml

# Build output
dist/
build/
.next/
out/

# Environment
.env
.env.local
.env.*.local

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Testing
coverage/
.nyc_output/

# Cache
.cache/
.parcel-cache/
.turbo/`,
  },
  {
    id: 'python',
    name: 'Python',
    content: `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Virtual environments
venv/
env/
.venv/
.env/

# Distribution / packaging
dist/
build/
*.egg-info/
*.egg

# IDE
.idea/
.vscode/
*.swp
*.swo

# Environment
.env
.env.local

# Testing
.pytest_cache/
.coverage
htmlcov/
.tox/

# Jupyter
.ipynb_checkpoints/

# OS
.DS_Store
Thumbs.db

# Logs
*.log`,
  },
  {
    id: 'java',
    name: 'Java',
    content: `# Compiled class files
*.class

# Package files
*.jar
*.war
*.ear
*.zip
*.tar.gz
*.rar

# Build directories
target/
build/
out/

# IDE
.idea/
*.iml
.vscode/
.project
.classpath
.settings/

# Gradle
.gradle/
gradle-app.setting
!gradle-wrapper.jar

# Maven
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties

# Logs
*.log

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'go',
    name: 'Go',
    content: `# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of the go coverage tool
*.out

# Build directory
/bin/
/build/

# Dependency directories
/vendor/

# IDE
.idea/
.vscode/
*.swp
*.swo

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'rust',
    name: 'Rust',
    content: `# Generated by Cargo
/target/
Cargo.lock

# IDE
.idea/
.vscode/
*.swp
*.swo

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db`,
  },
  {
    id: 'react',
    name: 'React',
    content: `# Dependencies
node_modules/
package-lock.json
yarn.lock

# Build
build/
dist/

# Environment
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Testing
coverage/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*`,
  },
  {
    id: 'vue',
    name: 'Vue.js',
    content: `# Dependencies
node_modules/
package-lock.json
yarn.lock

# Build
dist/
.nuxt/
.output/

# Environment
.env
.env.local
.env.*.local

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Testing
coverage/`,
  },
  {
    id: 'macos',
    name: 'macOS',
    content: `.DS_Store
.AppleDouble
.LSOverride
._*
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent`,
  },
  {
    id: 'windows',
    name: 'Windows',
    content: `Thumbs.db
ehthumbs.db
Desktop.ini
$RECYCLE.BIN/
*.cab
*.msi
*.msm
*.msp
*.lnk`,
  },
  {
    id: 'linux',
    name: 'Linux',
    content: `*~
.fuse_hidden*
.directory
.Trash-*
.nfs*`,
  },
];

export default function GitignoreGenerator() {
  const t = useTranslations('tools.gitignore');
  const [selectedTemplates, setSelectedTemplates] = useState<string[]>([]);
  const [customContent, setCustomContent] = useState('');
  const [output, setOutput] = useState('');

  const toggleTemplate = (id: string) => {
    setSelectedTemplates((prev) =>
      prev.includes(id) ? prev.filter((t) => t !== id) : [...prev, id]
    );
  };

  const generate = () => {
    const parts: string[] = [];

    for (const id of selectedTemplates) {
      const template = TEMPLATES.find((t) => t.id === id);
      if (template) {
        parts.push(`# ${template.name}\n${template.content}`);
      }
    }

    if (customContent.trim()) {
      parts.push(`# Custom\n${customContent.trim()}`);
    }

    setOutput(parts.join('\n\n'));
  };

  const copyOutput = () => {
    navigator.clipboard.writeText(output);
  };

  const downloadOutput = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = '.gitignore';
    link.click();
    URL.revokeObjectURL(url);
  };

  const clearAll = () => {
    setSelectedTemplates([]);
    setCustomContent('');
    setOutput('');
  };

  const categories = [
    { name: t('languages'), ids: ['node', 'python', 'java', 'go', 'rust'] },
    { name: t('frameworks'), ids: ['react', 'vue'] },
    { name: t('os'), ids: ['macos', 'windows', 'linux'] },
  ];

  return (
    <div className="space-y-6">
      {/* Template Selection */}
      <div className="space-y-4">
        {categories.map((category) => (
          <div key={category.name}>
            <label className="text-sm font-medium text-gray-700 dark:text-gray-300 block mb-2">{category.name}</label>
            <div className="flex flex-wrap gap-2">
              {category.ids.map((id) => {
                const template = TEMPLATES.find((t) => t.id === id);
                if (!template) return null;
                return (
                  <button
                    key={id}
                    onClick={() => toggleTemplate(id)}
                    className={`px-3 py-1.5 rounded text-sm ${
                      selectedTemplates.includes(id)
                        ? 'bg-blue-600 text-white'
                        : 'bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600'
                    }`}
                  >
                    {template.name}
                  </button>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Custom Content */}
      <div>
        <label className="text-sm font-medium text-gray-700 dark:text-gray-300 block mb-2">{t('custom')}</label>
        <textarea
          value={customContent}
          onChange={(e) => setCustomContent(e.target.value)}
          placeholder={t('customPlaceholder')}
          className="w-full h-32 bg-gray-100 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4 font-mono text-sm text-gray-900 dark:text-gray-100 resize-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
      </div>

      {/* Actions */}
      <div className="flex justify-center gap-4">
        <button
          onClick={generate}
          disabled={selectedTemplates.length === 0 && !customContent.trim()}
          className="px-6 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 dark:disabled:bg-gray-600 disabled:cursor-not-allowed rounded-lg font-medium text-white"
        >
          {t('generate')}
        </button>
        <button
          onClick={clearAll}
          className="px-6 py-2 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 rounded-lg font-medium text-gray-900 dark:text-gray-100"
        >
          {t('clear')}
        </button>
      </div>

      {/* Output */}
      {output && (
        <div>
          <div className="flex justify-between items-center mb-2">
            <label className="text-sm font-medium text-gray-700 dark:text-gray-300">.gitignore</label>
            <div className="flex gap-2">
              <button
                onClick={copyOutput}
                className="px-2 py-1 bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 rounded text-xs text-gray-900 dark:text-gray-100"
              >
                {t('copy')}
              </button>
              <button
                onClick={downloadOutput}
                className="px-2 py-1 bg-green-600 hover:bg-green-700 rounded text-xs text-white"
              >
                {t('download')}
              </button>
            </div>
          </div>
          <textarea
            value={output}
            readOnly
            className="w-full h-96 bg-gray-100 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4 font-mono text-sm text-gray-900 dark:text-gray-100 resize-none"
          />
        </div>
      )}
    </div>
  );
}
