'use client';

import dynamic from 'next/dynamic';

// Dynamically import tool components
const TOOL_COMPONENTS_MAP: Record<string, React.ComponentType> = {
  'json-formatter': dynamic(() => import('./JsonFormatter')),
  'base64': dynamic(() => import('./Base64')),
  'uuid-generator': dynamic(() => import('./UuidGenerator')),
  'url-encoder': dynamic(() => import('./UrlEncoder')),
  'password-generator': dynamic(() => import('./PasswordGenerator')),
  'hash-generator': dynamic(() => import('./HashGenerator')),
  'qr-generator': dynamic(() => import('./QrGenerator')),
  'color-converter': dynamic(() => import('./ColorConverter')),
  'timestamp-converter': dynamic(() => import('./TimestampConverter')),
  'word-counter': dynamic(() => import('./WordCounter')),
  'case-converter': dynamic(() => import('./CaseConverter')),
  'html-encoder': dynamic(() => import('./HtmlEncoder')),
  'markdown-preview': dynamic(() => import('./MarkdownPreview')),
  'lorem-ipsum': dynamic(() => import('./LoremIpsum')),
  'regex-tester': dynamic(() => import('./RegexTester')),
  // New tools
  'jwt-decoder': dynamic(() => import('./JwtDecoder')),
  'diff-checker': dynamic(() => import('./DiffChecker')),
  'json-to-csv': dynamic(() => import('./JsonToCsv')),
  'image-to-base64': dynamic(() => import('./ImageToBase64')),
  'cron-generator': dynamic(() => import('./CronGenerator')),
  'text-to-slug': dynamic(() => import('./TextToSlug')),
  'number-base-converter': dynamic(() => import('./NumberBaseConverter')),
  'json-path-tester': dynamic(() => import('./JsonPathTester')),
  // Batch 2 tools
  'xml-formatter': dynamic(() => import('./XmlFormatter')),
  'chinese-converter': dynamic(() => import('./ChineseConverter')),
  'unit-converter': dynamic(() => import('./UnitConverter')),
  'gradient-generator': dynamic(() => import('./GradientGenerator')),
  'unicode-converter': dynamic(() => import('./UnicodeConverter')),
  // Batch 3 tools
  'code-minifier': dynamic(() => import('./CodeMinifier')),
  'sql-formatter': dynamic(() => import('./SqlFormatter')),
  'pinyin-converter': dynamic(() => import('./PinyinConverter')),
  'color-picker': dynamic(() => import('./ColorPicker')),
  'aspect-ratio': dynamic(() => import('./AspectRatioCalculator')),
  // Batch 4 tools
  'css-beautifier': dynamic(() => import('./CssBeautifier')),
  'js-beautifier': dynamic(() => import('./JsBeautifier')),
  'html-preview': dynamic(() => import('./HtmlPreview')),
  'ip-lookup': dynamic(() => import('./IpLookup')),
  'morse-code': dynamic(() => import('./MorseCode')),
  // Batch 5 tools
  'random-generator': dynamic(() => import('./RandomGenerator')),
  'text-reverser': dynamic(() => import('./TextReverser')),
  'line-counter': dynamic(() => import('./LineCounter')),
  'string-escape': dynamic(() => import('./StringEscape')),
  'yaml-json': dynamic(() => import('./YamlJson')),
  // Batch 6 tools
  'date-calculator': dynamic(() => import('./DateCalculator')),
  'text-deduplicator': dynamic(() => import('./TextDeduplicator')),
  'color-blender': dynamic(() => import('./ColorBlender')),
  'json-sorter': dynamic(() => import('./JsonSorter')),
  'placeholder-image': dynamic(() => import('./PlaceholderImage')),
  // Batch 7 tools
  'text-encryption': dynamic(() => import('./TextEncryption')),
  'file-hash': dynamic(() => import('./FileHash')),
  'html-table-generator': dynamic(() => import('./HtmlTableGenerator')),
  'json-schema-validator': dynamic(() => import('./JsonSchemaValidator')),
  'regex-patterns': dynamic(() => import('./RegexPatterns')),
  // Batch 8 tools
  'byte-counter': dynamic(() => import('./ByteCounter')),
  'json-to-typescript': dynamic(() => import('./JsonToTypescript')),
  'svg-optimizer': dynamic(() => import('./SvgOptimizer')),
  'text-to-binary': dynamic(() => import('./TextToBinary')),
  'markdown-to-html': dynamic(() => import('./MarkdownToHtml')),
  // Batch 9 tools
  'html-minifier': dynamic(() => import('./HtmlMinifier')),
  'json-diff': dynamic(() => import('./JsonDiff')),
  'base32': dynamic(() => import('./Base32')),
  'epoch-converter': dynamic(() => import('./EpochConverter')),
  'css-unit-converter': dynamic(() => import('./CssUnitConverter')),
  // Batch 10 tools
  'text-statistics': dynamic(() => import('./TextStatistics')),
  'hex-editor': dynamic(() => import('./HexEditor')),
  'color-palette': dynamic(() => import('./ColorPalette')),
  'http-status': dynamic(() => import('./HttpStatus')),
  'json-to-yaml': dynamic(() => import('./JsonToYaml')),
  'data-uri': dynamic(() => import('./DataUri')),
  'text-compare': dynamic(() => import('./TextCompare')),
  'json-to-go': dynamic(() => import('./JsonToGo')),
  'html-to-jsx': dynamic(() => import('./HtmlToJsx')),
  'chmod-calculator': dynamic(() => import('./ChmodCalculator')),
  // Batch 11 tools
  'barcode-generator': dynamic(() => import('./BarcodeGenerator')),
  'text-to-speech': dynamic(() => import('./TextToSpeech')),
  'url-parser': dynamic(() => import('./UrlParser')),
  'json-to-xml': dynamic(() => import('./JsonToXml')),
  'text-wrapper': dynamic(() => import('./TextWrapper')),
  'csv-to-json': dynamic(() => import('./CsvToJson')),
  'html-entity': dynamic(() => import('./HtmlEntityConverter')),
  'number-formatter': dynamic(() => import('./NumberFormatter')),
  // Batch 12 - Security Tools
  'hmac-generator': dynamic(() => import('./HmacGenerator')),
  'password-strength': dynamic(() => import('./PasswordStrength')),
  'totp-generator': dynamic(() => import('./TotpGenerator')),
  // Batch 13 - Network Tools
  'user-agent-parser': dynamic(() => import('./UserAgentParser')),
  'cidr-calculator': dynamic(() => import('./CidrCalculator')),
  'http-header-parser': dynamic(() => import('./HttpHeaderParser')),
  // Batch 14 - Math Tools
  'percentage-calculator': dynamic(() => import('./PercentageCalculator')),
  'statistics-calculator': dynamic(() => import('./StatisticsCalculator')),
  'scientific-calculator': dynamic(() => import('./ScientificCalculator')),
  // Batch 15 - Text Tools
  'text-sorter': dynamic(() => import('./TextSorter')),
  'text-extractor': dynamic(() => import('./TextExtractor')),
  'emoji-picker': dynamic(() => import('./EmojiPicker')),
  // Batch 16 - Converter Tools
  'json-to-sql': dynamic(() => import('./JsonToSql')),
  'toml-json': dynamic(() => import('./TomlJson')),
  'json-to-java': dynamic(() => import('./JsonToJava')),
  'json-to-python': dynamic(() => import('./JsonToPython')),
  'json-to-kotlin': dynamic(() => import('./JsonToKotlin')),
  // Batch 17 - Image Tools
  'image-compressor': dynamic(() => import('./ImageCompressor')),
  'image-converter': dynamic(() => import('./ImageConverter')),
  'favicon-generator': dynamic(() => import('./FaviconGenerator')),
  'image-cropper': dynamic(() => import('./ImageCropper')),
  // Batch 18 - Development Tools
  'gitignore-generator': dynamic(() => import('./GitignoreGenerator')),
  'docker-compose-generator': dynamic(() => import('./DockerComposeGenerator')),
  'package-json-generator': dynamic(() => import('./PackageJsonGenerator')),
  // Batch 19 - New Popular Tools
  'json-minifier': dynamic(() => import('./JsonMinifier')),
  'timezone-converter': dynamic(() => import('./TimezoneConverter')),
  'color-contrast-checker': dynamic(() => import('./ColorContrastChecker')),
  'markdown-table-generator': dynamic(() => import('./MarkdownTableGenerator')),
  'base58': dynamic(() => import('./Base58')),
  // Batch 20 - SEO & Development Tools
  'meta-tag-generator': dynamic(() => import('./MetaTagGenerator')),
  'robots-txt-generator': dynamic(() => import('./RobotsTxtGenerator')),
  'opengraph-preview': dynamic(() => import('./OpenGraphPreview')),
  'css-grid-generator': dynamic(() => import('./CssGridGenerator')),
  'css-flexbox-generator': dynamic(() => import('./CssFlexboxGenerator')),
  'jwt-generator': dynamic(() => import('./JwtGenerator')),
  'cron-explainer': dynamic(() => import('./CronExplainer')),
  'json-to-graphql': dynamic(() => import('./JsonToGraphql')),
  'sql-to-mongo': dynamic(() => import('./SqlToMongo')),
  // Batch 21 - Code & CSS Tools
  'json-to-csharp': dynamic(() => import('./JsonToCsharp')),
  'json-to-rust': dynamic(() => import('./JsonToRust')),
  'json-to-swift': dynamic(() => import('./JsonToSwift')),
  'css-minifier': dynamic(() => import('./CssMinifier')),
  'js-minifier': dynamic(() => import('./JsMinifier')),
  'box-shadow-generator': dynamic(() => import('./BoxShadowGenerator')),
  'border-radius-generator': dynamic(() => import('./BorderRadiusGenerator')),
  'text-to-ascii-art': dynamic(() => import('./TextToAsciiArt')),
  // Batch 22 - Utility Tools
  'color-shades-generator': dynamic(() => import('./ColorShadesGenerator')),
  'json-flattener': dynamic(() => import('./JsonFlattener')),
  'base85': dynamic(() => import('./Base85')),
  'html-to-markdown': dynamic(() => import('./HtmlToMarkdown')),
  'regex-generator': dynamic(() => import('./RegexGenerator')),
  'url-shortener-preview': dynamic(() => import('./UrlShortenerPreview')),
  // Batch 23 - More Utility Tools
  'json-viewer': dynamic(() => import('./JsonViewer')),
  'xml-to-json': dynamic(() => import('./XmlToJson')),
  'ip-address-generator': dynamic(() => import('./IpAddressGenerator')),
  'css-gradient-text': dynamic(() => import('./CssGradientText')),
  'sitemap-generator': dynamic(() => import('./SitemapGenerator')),
  // Batch 24 - Advanced Tools
  'json-to-php': dynamic(() => import('./JsonToPhp')),
  'css-filter-generator': dynamic(() => import('./CssFilterGenerator')),
  'text-diff-patch': dynamic(() => import('./TextDiffPatch')),
  'encoding-detector': dynamic(() => import('./EncodingDetector')),
  // Batch 25 - More Tools
  'css-clip-path-generator': dynamic(() => import('./CssClipPathGenerator')),
  'uuid-validator': dynamic(() => import('./UuidValidator')),
  'text-hash-comparator': dynamic(() => import('./TextHashComparator')),
  'json-path-finder': dynamic(() => import('./JsonPathFinder')),
  'canvas-drawing': dynamic(() => import('./CanvasDrawing')),
  // Batch 26 - New Tools
  'json-escape': dynamic(() => import('./JsonEscape')),
  'css-animation-generator': dynamic(() => import('./CssAnimationGenerator')),
  'text-case-counter': dynamic(() => import('./TextCaseCounter')),
  'dns-lookup': dynamic(() => import('./DnsLookup')),
  'image-resizer': dynamic(() => import('./ImageResizer')),
  // Batch 27 - Popular Overseas Tools
  'ssl-checker': dynamic(() => import('./SslChecker')),
  'whois-lookup': dynamic(() => import('./WhoisLookup')),
  'port-reference': dynamic(() => import('./PortScanner')),
  'privacy-policy-generator': dynamic(() => import('./PrivacyPolicyGenerator')),
  'terms-generator': dynamic(() => import('./TermsGenerator')),
  'cookie-policy-generator': dynamic(() => import('./CookiePolicyGenerator')),
  'json-to-tsv': dynamic(() => import('./JsonToTsv')),
  'csv-viewer': dynamic(() => import('./CsvViewer')),
  'htaccess-generator': dynamic(() => import('./HtaccessGenerator')),
  'nginx-config-generator': dynamic(() => import('./NginxConfigGenerator')),
  'curl-converter': dynamic(() => import('./CurlConverter')),
  'reading-time-calculator': dynamic(() => import('./ReadingTimeCalculator')),
  // Batch 28 - New Popular Tools
  'open-graph-generator': dynamic(() => import('./OpenGraphGenerator')),
  'twitter-card-generator': dynamic(() => import('./TwitterCardGenerator')),
  'mime-type-lookup': dynamic(() => import('./MimeTypeLookup')),
  'http-status-codes': dynamic(() => import('./HttpStatusCodes')),
  'string-obfuscator': dynamic(() => import('./StringObfuscator')),
  'text-cleaner': dynamic(() => import('./TextCleaner')),
  'list-randomizer': dynamic(() => import('./ListRandomizer')),
  'sql-generator': dynamic(() => import('./SqlGenerator')),
  // Batch 29 - New Tools from toolfk.com
  'htaccess-to-nginx': dynamic(() => import('./HtaccessToNginx')),
  'js-obfuscator': dynamic(() => import('./JsObfuscator')),
  'image-watermark': dynamic(() => import('./ImageWatermark')),
  'svg-to-image': dynamic(() => import('./SvgToImage')),
  'hex-base64-converter': dynamic(() => import('./HexBase64Converter')),
  // Batch 30 - More Tools
  'pdf-to-base64': dynamic(() => import('./PdfToBase64')),
  'audio-to-base64': dynamic(() => import('./AudioToBase64')),
  'video-to-base64': dynamic(() => import('./VideoToBase64')),
  'file-size-calculator': dynamic(() => import('./FileSizeCalculator')),
  'ascii-table': dynamic(() => import('./AsciiTable')),
  // Batch 31 - More Tools
  'text-to-hex': dynamic(() => import('./TextToHex')),
  'css-variables-generator': dynamic(() => import('./CssVariablesGenerator')),
  'lorem-picsum': dynamic(() => import('./LoremPicsum')),
  'regex-escape': dynamic(() => import('./RegexEscape')),
  'html-to-text': dynamic(() => import('./HtmlToText')),
  'binary-to-decimal': dynamic(() => import('./BinaryToDecimal')),
  'octal-converter': dynamic(() => import('./OctalConverter')),
  'text-to-nato': dynamic(() => import('./TextToNato')),
  'crc32-calculator': dynamic(() => import('./Crc32Calculator')),
  'mac-address-generator': dynamic(() => import('./MacAddressGenerator')),
  // Batch 32 - New Popular Tools (to reach 200)
  'ip-validator': dynamic(() => import('./IpValidator')),
  'json-merger': dynamic(() => import('./JsonMerger')),
  'text-template': dynamic(() => import('./TextTemplate')),
  'base-calculator': dynamic(() => import('./BaseCalculator')),
  'color-name-finder': dynamic(() => import('./ColorNameFinder')),
  'char-frequency': dynamic(() => import('./CharFrequency')),
  'json-to-dart': dynamic(() => import('./JsonToDart')),
  'sql-to-json': dynamic(() => import('./SqlToJson')),
  // Batch 33 - Chart Tools (数据图表工具)
  'bar-chart-generator': dynamic(() => import('./BarChartGenerator'), { ssr: false }),
  'line-chart-generator': dynamic(() => import('./LineChartGenerator'), { ssr: false }),
  'pie-chart-generator': dynamic(() => import('./PieChartGenerator'), { ssr: false }),
  'radar-chart-generator': dynamic(() => import('./RadarChartGenerator'), { ssr: false }),
  'scatter-chart-generator': dynamic(() => import('./ScatterChartGenerator'), { ssr: false }),
  'area-chart-generator': dynamic(() => import('./AreaChartGenerator'), { ssr: false }),
  'funnel-chart-generator': dynamic(() => import('./FunnelChartGenerator'), { ssr: false }),
  'gauge-chart-generator': dynamic(() => import('./GaugeChartGenerator'), { ssr: false }),
  'heatmap-chart-generator': dynamic(() => import('./HeatmapChartGenerator'), { ssr: false }),
  'treemap-chart-generator': dynamic(() => import('./TreemapChartGenerator'), { ssr: false }),
  // Batch 34 - New Chart Tools (新增图表工具)
  'doughnut-chart-generator': dynamic(() => import('./DoughnutChartGenerator'), { ssr: false }),
  'sankey-chart-generator': dynamic(() => import('./SankeyChartGenerator'), { ssr: false }),
  'sunburst-chart-generator': dynamic(() => import('./SunburstChartGenerator'), { ssr: false }),
  'candlestick-chart-generator': dynamic(() => import('./CandlestickChartGenerator'), { ssr: false }),
  'boxplot-chart-generator': dynamic(() => import('./BoxplotChartGenerator'), { ssr: false }),
  'wordcloud-generator': dynamic(() => import('./WordCloudGenerator'), { ssr: false }),
  'graph-chart-generator': dynamic(() => import('./GraphChartGenerator'), { ssr: false }),
  'calendar-heatmap-generator': dynamic(() => import('./CalendarHeatmapGenerator'), { ssr: false }),
  'polar-bar-chart-generator': dynamic(() => import('./PolarBarChartGenerator'), { ssr: false }),
  'parallel-chart-generator': dynamic(() => import('./ParallelChartGenerator'), { ssr: false }),
  'bubble-chart-generator': dynamic(() => import('./BubbleChartGenerator'), { ssr: false }),
  'tree-chart-generator': dynamic(() => import('./TreeChartGenerator'), { ssr: false }),
  'theme-river-generator': dynamic(() => import('./ThemeRiverGenerator'), { ssr: false }),
  'gantt-chart-generator': dynamic(() => import('./GanttChartGenerator'), { ssr: false }),
  'venn-diagram-generator': dynamic(() => import('./VennDiagramGenerator'), { ssr: false }),
  'timeline-chart-generator': dynamic(() => import('./TimelineChartGenerator'), { ssr: false }),
  // Batch 35 - New Chart Tools from 67tool.com (新增图表工具)
  'nightingale-rose-chart-generator': dynamic(() => import('./NightingaleRoseChartGenerator'), { ssr: false }),
  'grouped-bar-chart-generator': dynamic(() => import('./GroupedBarChartGenerator'), { ssr: false }),
  'stacked-bar-chart-generator': dynamic(() => import('./StackedBarChartGenerator'), { ssr: false }),
  'grouped-line-chart-generator': dynamic(() => import('./GroupedLineChartGenerator'), { ssr: false }),
  'step-line-chart-generator': dynamic(() => import('./StepLineChartGenerator'), { ssr: false }),
  'waterfall-chart-generator': dynamic(() => import('./WaterfallChartGenerator'), { ssr: false }),
  'stacked-area-chart-generator': dynamic(() => import('./StackedAreaChartGenerator'), { ssr: false }),
  'positive-negative-bar-chart-generator': dynamic(() => import('./PositiveNegativeBarChartGenerator'), { ssr: false }),
  // Batch 36 - New Chart Tools (新增图表工具)
  'percentage-stacked-bar-chart-generator': dynamic(() => import('./PercentageStackedBarChartGenerator'), { ssr: false }),
  'mixed-chart-generator': dynamic(() => import('./MixedChartGenerator'), { ssr: false }),
  'ring-progress-chart-generator': dynamic(() => import('./RingProgressChartGenerator'), { ssr: false }),
  'liquid-fill-chart-generator': dynamic(() => import('./LiquidFillChartGenerator'), { ssr: false }),
  'multi-ring-chart-generator': dynamic(() => import('./MultiRingChartGenerator'), { ssr: false }),
  'half-doughnut-chart-generator': dynamic(() => import('./HalfDoughnutChartGenerator'), { ssr: false }),
  'nested-pie-chart-generator': dynamic(() => import('./NestedPieChartGenerator'), { ssr: false }),
  'pictorial-bar-chart-generator': dynamic(() => import('./PictorialBarChartGenerator'), { ssr: false }),
  // Batch 37 - New Popular Tools (热门低竞争工具)
  'env-parser': dynamic(() => import('./EnvParser')),
  'json-schema-generator': dynamic(() => import('./JsonSchemaGenerator')),
  'time-calculator': dynamic(() => import('./TimeCalculator')),
  'batch-timestamp-converter': dynamic(() => import('./BatchTimestampConverter')),
  'regex-visualizer': dynamic(() => import('./RegexVisualizer')),
  'crontab-calendar': dynamic(() => import('./CrontabCalendar')),
  'fake-data-generator': dynamic(() => import('./FakeDataGenerator')),
  // Batch 38 - Image Tools (图像工具)
  'image-collage': dynamic(() => import('./ImageCollage')),
  'image-splitter': dynamic(() => import('./ImageSplitter')),
  'image-rounder': dynamic(() => import('./ImageRounder')),
  'image-border': dynamic(() => import('./ImageBorder')),
  'image-flip-rotate': dynamic(() => import('./ImageFlipRotate')),
  'image-adjustment': dynamic(() => import('./ImageAdjustment')),
  'image-frosted-glass': dynamic(() => import('./ImageFrostedGlass')),
  'image-to-ico': dynamic(() => import('./ImageToIco')),
  'gif-maker': dynamic(() => import('./GifMaker'), { ssr: false }),
  'gif-splitter': dynamic(() => import('./GifSplitter'), { ssr: false }),
  'gif-compressor': dynamic(() => import('./GifCompressor'), { ssr: false }),
  'image-to-webp': dynamic(() => import('./ImageToWebp')),
  'exif-viewer': dynamic(() => import('./ExifViewer')),
  'color-extractor': dynamic(() => import('./ColorExtractor')),
  // Batch 39 - Office Tools (办公工具)
  'invoice-generator': dynamic(() => import('./InvoiceGenerator')),
  'resume-builder': dynamic(() => import('./ResumeBuilder')),
  'signature-pad': dynamic(() => import('./SignaturePad')),
  'pomodoro-timer': dynamic(() => import('./PomodoroTimer')),
  'meeting-notes': dynamic(() => import('./MeetingNotes')),
  'business-days-calculator': dynamic(() => import('./BusinessDaysCalculator')),
  'salary-calculator': dynamic(() => import('./SalaryCalculator')),
  // Batch 40 - Excel & PDF Tools (Excel 和 PDF 工具)
  'excel-to-json': dynamic(() => import('./ExcelToJson')),
  'json-to-excel': dynamic(() => import('./JsonToExcel')),
  'excel-viewer': dynamic(() => import('./ExcelViewer')),
  'excel-merger': dynamic(() => import('./ExcelMerger')),
  'pdf-to-image': dynamic(() => import('./PdfToImage'), { ssr: false }),
  'image-to-pdf': dynamic(() => import('./ImageToPdf'), { ssr: false }),
  'pdf-merger': dynamic(() => import('./PdfMerger'), { ssr: false }),
  'pdf-splitter': dynamic(() => import('./PdfSplitter'), { ssr: false }),
  'pdf-compressor': dynamic(() => import('./PdfCompressor'), { ssr: false }),
  'pdf-rotator': dynamic(() => import('./PdfRotator'), { ssr: false }),
  // Batch 41 - New Utility Tools (新实用工具)
  'markdown-editor': dynamic(() => import('./MarkdownEditor')),
  'world-clock': dynamic(() => import('./WorldClock')),
  'stopwatch': dynamic(() => import('./Stopwatch')),
  'countdown-timer': dynamic(() => import('./CountdownTimer')),
  'note-pad': dynamic(() => import('./NotePad')),
  // Batch 42 - Document Converter Tools
  'pdf-to-text': dynamic(() => import('./PdfToText')),
  'word-to-txt': dynamic(() => import('./WordToTxt')),
  'word-to-html': dynamic(() => import('./WordToHtml')),
  'excel-to-csv': dynamic(() => import('./ExcelToCsv')),
  'csv-to-excel': dynamic(() => import('./CsvToExcel')),
  // Batch 43 - Popular Calculator Tools (热门计算器工具)
  'loan-calculator': dynamic(() => import('./LoanCalculator')),
  'bmi-calculator': dynamic(() => import('./BmiCalculator')),
  'age-calculator': dynamic(() => import('./AgeCalculator')),
  'tip-calculator': dynamic(() => import('./TipCalculator')),
  'discount-calculator': dynamic(() => import('./DiscountCalculator')),
  'compound-interest-calculator': dynamic(() => import('./CompoundInterestCalculator')),
  'binary-calculator': dynamic(() => import('./BinaryCalculator')),
  'hex-calculator': dynamic(() => import('./HexCalculator')),
  'ip-subnet-calculator': dynamic(() => import('./IpSubnetCalculator')),
  'aspect-ratio-calculator-enhanced': dynamic(() => import('./AspectRatioCalculatorEnhanced')),
  // Batch 44 - Text & Utility Tools (文本和实用工具)
  'chinese-lorem-ipsum': dynamic(() => import('./ChineseLoremIpsum')),
  'text-to-image': dynamic(() => import('./TextToImage')),
  'text-to-handwriting': dynamic(() => import('./TextToHandwriting')),
  'screen-resolution-tester': dynamic(() => import('./ScreenResolutionTester')),
  'keyboard-tester': dynamic(() => import('./KeyboardTester')),
  'typing-speed-test': dynamic(() => import('./TypingSpeedTest')),
  'morse-code-player': dynamic(() => import('./MorseCodePlayer')),
  // Batch 45 - Popular Tools Batch 3
  'currency-converter': dynamic(() => import('./CurrencyConverter')),
  'roi-calculator': dynamic(() => import('./RoiCalculator')),
  'mortgage-calculator': dynamic(() => import('./MortgageCalculator')),
  'tax-calculator': dynamic(() => import('./TaxCalculator')),
  // Health Tools
  'calorie-calculator': dynamic(() => import('./CalorieCalculator')),
  'water-intake-calculator': dynamic(() => import('./WaterIntakeCalculator')),
  'sleep-calculator': dynamic(() => import('./SleepCalculator')),
  'due-date-calculator': dynamic(() => import('./DueDateCalculator')),
  // Entertainment Tools
  'love-calculator': dynamic(() => import('./LoveCalculator')),
  'decision-wheel': dynamic(() => import('./DecisionWheel'), { ssr: false }),
  'name-generator': dynamic(() => import('./NameGenerator')),
  'random-picker': dynamic(() => import('./RandomPicker')),
  'coin-flipper': dynamic(() => import('./CoinFlipper')),
  'dice-roller': dynamic(() => import('./DiceRoller')),
  'team-generator': dynamic(() => import('./TeamGenerator')),
  // Daily Calculators
  'countdown-days-calculator': dynamic(() => import('./CountdownDaysCalculator')),
  'fuel-cost-calculator': dynamic(() => import('./FuelCostCalculator')),
  'electricity-cost-calculator': dynamic(() => import('./ElectricityCostCalculator')),
  'gpa-calculator': dynamic(() => import('./GpaCalculator')),
  'pace-calculator': dynamic(() => import('./PaceCalculator')),
  // Size Converters
  'shoe-size-converter': dynamic(() => import('./ShoeSizeConverter')),
  'ring-size-calculator': dynamic(() => import('./RingSizeCalculator')),
  'bra-size-calculator': dynamic(() => import('./BraSizeCalculator')),
  // Home Improvement
  'concrete-calculator': dynamic(() => import('./ConcreteCalculator')),
  'paint-calculator': dynamic(() => import('./PaintCalculator')),
  'tile-calculator': dynamic(() => import('./TileCalculator')),
  // Social Media Tools
  'instagram-font-generator': dynamic(() => import('./InstagramFontGenerator')),
  'social-media-size-guide': dynamic(() => import('./SocialMediaSizeGuide')),
  // SEO/Content Tools
  'keyword-density-checker': dynamic(() => import('./KeywordDensityChecker')),
  'text-summarizer': dynamic(() => import('./TextSummarizer')),
  'paraphrase-tool': dynamic(() => import('./ParaphraseTool')),
  // Development Tools
  'graphql-formatter': dynamic(() => import('./GraphqlFormatter')),
  'code-screenshot-generator': dynamic(() => import('./CodeScreenshotGenerator')),
  'number-system-converter': dynamic(() => import('./NumberSystemConverter')),
  'subnet-calculator-enhanced': dynamic(() => import('./SubnetCalculatorEnhanced')),
  // Batch 46 - European Popular Tools (欧洲热门工具)
  'iban-validator': dynamic(() => import('./IbanValidator')),
  'vat-calculator': dynamic(() => import('./VatCalculator')),
  'carbon-footprint-calculator': dynamic(() => import('./CarbonFootprintCalculator')),
  'gdpr-consent-generator': dynamic(() => import('./GdprConsentGenerator')),
  'metric-imperial-converter': dynamic(() => import('./MetricImperialConverter')),
  'bic-swift-lookup': dynamic(() => import('./BicSwiftLookup')),
  // Batch 47 - Global Popular Tools (全球热门工具)
  'email-validator': dynamic(() => import('./EmailValidator')),
  'phone-formatter': dynamic(() => import('./PhoneFormatter')),
  'credit-card-validator': dynamic(() => import('./CreditCardValidator')),
  'color-blindness-simulator': dynamic(() => import('./ColorBlindnessSimulator')),
  'aspect-ratio-resizer': dynamic(() => import('./AspectRatioResizer')),
  'markdown-to-pdf': dynamic(() => import('./MarkdownToPdf')),
  // Batch 48 - Popular Online Tools (热门在线工具)
  'speech-timer': dynamic(() => import('./SpeechTimer')),
  'habit-tracker': dynamic(() => import('./HabitTracker')),
  'flip-text': dynamic(() => import('./FlipText')),
  'strikethrough-text': dynamic(() => import('./StrikethroughText')),
  'small-text-generator': dynamic(() => import('./SmallTextGenerator')),
  'binary-to-text': dynamic(() => import('./BinaryToText')),
  'roman-numeral-converter': dynamic(() => import('./RomanNumeralConverter')),
  'fraction-calculator': dynamic(() => import('./FractionCalculator')),
  'percentage-change-calculator': dynamic(() => import('./PercentageChangeCalculator')),
  'random-color-generator': dynamic(() => import('./RandomColorGenerator')),
  // Batch 49 - Popular Word & Text Tools
  'anagram-solver': dynamic(() => import('./AnagramSolver')),
  'word-unscrambler': dynamic(() => import('./WordUnscrambler')),
  'text-to-pdf': dynamic(() => import('./TextToPdf')),
  'unit-price-calculator': dynamic(() => import('./UnitPriceCalculator')),
  'bionic-reading-converter': dynamic(() => import('./BionicReadingConverter')),
  'palindrome-checker': dynamic(() => import('./PalindromeChecker')),
  'character-map': dynamic(() => import('./CharacterMap')),
  'text-repeater': dynamic(() => import('./TextRepeater')),
  'fake-name-generator': dynamic(() => import('./FakeNameGenerator')),
  'invisible-character-generator': dynamic(() => import('./InvisibleCharacterGenerator')),
  // Batch 50 - Popular Overseas Developer Tools (海外热门开发工具)
  'json-to-proto': dynamic(() => import('./JsonToProto')),
  'svg-to-png': dynamic(() => import('./SvgToPng')),
  'webp-to-png': dynamic(() => import('./WebpToPng')),
  'png-to-svg': dynamic(() => import('./PngToSvg')),
  'html-to-pdf': dynamic(() => import('./HtmlToPdf')),
  'json-to-table': dynamic(() => import('./JsonToTable')),
  'yaml-validator': dynamic(() => import('./YamlValidator')),
  'xml-validator': dynamic(() => import('./XmlValidator')),
  'css-to-tailwind': dynamic(() => import('./CssToTailwind')),
  'tailwind-to-css': dynamic(() => import('./TailwindToCss')),
  'svg-editor': dynamic(() => import('./SvgEditor')),
  'json-to-form': dynamic(() => import('./JsonToForm')),
  'api-tester': dynamic(() => import('./ApiTester')),
  'jwt-debugger': dynamic(() => import('./JwtDebugger')),
  'csp-generator': dynamic(() => import('./CspGenerator')),
  'sri-hash-generator': dynamic(() => import('./SriHashGenerator')),
  'cors-tester': dynamic(() => import('./CorsTester')),
  'json-to-zod': dynamic(() => import('./JsonToZod')),
  'typescript-to-json': dynamic(() => import('./TypescriptToJson')),
  'markdown-to-slides': dynamic(() => import('./MarkdownToSlides')),
};

export default function ToolWrapper({ slug }: { slug: string }) {
  const ToolComponent = TOOL_COMPONENTS_MAP[slug];

  if (!ToolComponent) {
    return <div className="text-center text-gray-600 dark:text-gray-300">Tool not found: {slug}</div>;
  }

  return <ToolComponent />;
}
