'use client';

import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';
import ToolSkeleton, { getSkeletonVariant, SkeletonVariant } from './ToolSkeleton';

/**
 * 创建带骨架屏加载的工具动态导入
 * 
 * @param importFn - 动态导入函数
 * @param variant - 骨架屏变体类型
 * @param ssr - 是否启用服务端渲染（默认 true）
 */
function createToolImport(
  importFn: () => Promise<{ default: ComponentType }>,
  variant: SkeletonVariant = 'default',
  ssr: boolean = true
): ComponentType {
  return dynamic(importFn, {
    loading: () => <ToolSkeleton variant={variant} />,
    ssr,
  });
}



// Dynamically import tool components with loading skeletons
// Dynamically import tool components with loading skeletons
export const TOOL_COMPONENTS_MAP: Record<string, ComponentType> = {
  // Encoding & Decoding
  'json-formatter': createToolImport(() => import('./JsonFormatter'), 'editor'),
  'base64': createToolImport(() => import('./Base64'), 'converter'),
  'uuid-generator': createToolImport(() => import('./UuidGenerator'), 'generator'),
  'url-encoder': createToolImport(() => import('./UrlEncoder'), 'converter'),
  'password-generator': createToolImport(() => import('./PasswordGenerator'), 'generator'),
  'hash-generator': createToolImport(() => import('./HashGenerator'), 'converter'),
  'qr-generator': createToolImport(() => import('./QrGenerator'), 'generator'),
  'color-converter': createToolImport(() => import('./ColorConverter'), 'converter'),
  'timestamp-converter': createToolImport(() => import('./TimestampConverter'), 'converter'),
  'word-counter': createToolImport(() => import('./WordCounter'), 'editor'),
  'case-converter': createToolImport(() => import('./CaseConverter'), 'converter'),
  'html-encoder': createToolImport(() => import('./HtmlEncoder'), 'converter'),
  'markdown-preview': createToolImport(() => import('./MarkdownPreview'), 'editor'),
  'lorem-ipsum': createToolImport(() => import('./LoremIpsum'), 'generator'),
  'regex-tester': createToolImport(() => import('./RegexTester'), 'editor'),
  // New tools
  'jwt-decoder': createToolImport(() => import('./JwtDecoder'), 'converter'),
  'diff-checker': createToolImport(() => import('./DiffChecker'), 'editor'),
  'json-to-csv': createToolImport(() => import('./JsonToCsv'), 'converter'),
  'image-to-base64': createToolImport(() => import('./ImageToBase64'), 'default'),
  'cron-generator': createToolImport(() => import('./CronGenerator'), 'generator'),
  'text-to-slug': createToolImport(() => import('./TextToSlug'), 'converter'),
  'number-base-converter': createToolImport(() => import('./NumberBaseConverter'), 'converter'),
  'json-path-tester': createToolImport(() => import('./JsonPathTester'), 'editor'),
  // Batch 2 tools
  'xml-formatter': createToolImport(() => import('./XmlFormatter'), 'editor'),
  'chinese-converter': createToolImport(() => import('./ChineseConverter'), 'converter'),
  'unit-converter': createToolImport(() => import('./UnitConverter'), 'converter'),
  'gradient-generator': createToolImport(() => import('./GradientGenerator'), 'generator'),
  'unicode-converter': createToolImport(() => import('./UnicodeConverter'), 'converter'),
  // Batch 3 tools
  'code-minifier': createToolImport(() => import('./CodeMinifier'), 'editor'),
  'sql-formatter': createToolImport(() => import('./SqlFormatter'), 'editor'),
  'pinyin-converter': createToolImport(() => import('./PinyinConverter'), 'converter'),
  'color-picker': createToolImport(() => import('./ColorPicker'), 'generator'),
  'aspect-ratio': createToolImport(() => import('./AspectRatioCalculator'), 'generator'),
  // Batch 4 tools
  'css-beautifier': createToolImport(() => import('./CssBeautifier'), 'editor'),
  'js-beautifier': createToolImport(() => import('./JsBeautifier'), 'editor'),
  'html-preview': createToolImport(() => import('./HtmlPreview'), 'editor'),
  'ip-lookup': createToolImport(() => import('./IpLookup'), 'default'),
  'morse-code': createToolImport(() => import('./MorseCode'), 'converter'),
  // Batch 5 tools
  'random-generator': createToolImport(() => import('./RandomGenerator'), 'generator'),
  'text-reverser': createToolImport(() => import('./TextReverser'), 'converter'),
  'line-counter': createToolImport(() => import('./LineCounter'), 'editor'),
  'string-escape': createToolImport(() => import('./StringEscape'), 'converter'),
  'yaml-json': createToolImport(() => import('./YamlJson'), 'converter'),
  // Batch 6 tools
  'date-calculator': createToolImport(() => import('./DateCalculator'), 'generator'),
  'text-deduplicator': createToolImport(() => import('./TextDeduplicator'), 'editor'),
  'color-blender': createToolImport(() => import('./ColorBlender'), 'generator'),
  'json-sorter': createToolImport(() => import('./JsonSorter'), 'editor'),
  'placeholder-image': createToolImport(() => import('./PlaceholderImage'), 'generator'),
  // Batch 7 tools
  'text-encryption': createToolImport(() => import('./TextEncryption'), 'converter'),
  'file-hash': createToolImport(() => import('./FileHash'), 'converter'),
  'html-table-generator': createToolImport(() => import('./HtmlTableGenerator'), 'generator'),
  'json-schema-validator': createToolImport(() => import('./JsonSchemaValidator'), 'editor'),
  'regex-patterns': createToolImport(() => import('./RegexPatterns'), 'default'),
  // Batch 8 tools
  'byte-counter': createToolImport(() => import('./ByteCounter'), 'editor'),
  'json-to-typescript': createToolImport(() => import('./JsonToTypescript'), 'converter'),
  'svg-optimizer': createToolImport(() => import('./SvgOptimizer'), 'default'),
  'text-to-binary': createToolImport(() => import('./TextToBinary'), 'converter'),
  'markdown-to-html': createToolImport(() => import('./MarkdownToHtml'), 'converter'),
  // Batch 9 tools
  'html-minifier': createToolImport(() => import('./HtmlMinifier'), 'editor'),
  'json-diff': createToolImport(() => import('./JsonDiff'), 'editor'),
  'base32': createToolImport(() => import('./Base32'), 'converter'),
  'epoch-converter': createToolImport(() => import('./EpochConverter'), 'converter'),
  'css-unit-converter': createToolImport(() => import('./CssUnitConverter'), 'converter'),
  // Batch 10 tools
  'text-statistics': createToolImport(() => import('./TextStatistics'), 'editor'),
  'hex-editor': createToolImport(() => import('./HexEditor'), 'editor'),
  'color-palette': createToolImport(() => import('./ColorPalette'), 'generator'),
  'http-status': createToolImport(() => import('./HttpStatus'), 'default'),
  'json-to-yaml': createToolImport(() => import('./JsonToYaml'), 'converter'),
  'data-uri': createToolImport(() => import('./DataUri'), 'converter'),
  'text-compare': createToolImport(() => import('./TextCompare'), 'editor'),
  'json-to-go': createToolImport(() => import('./JsonToGo'), 'converter'),
  'html-to-jsx': createToolImport(() => import('./HtmlToJsx'), 'converter'),
  'chmod-calculator': createToolImport(() => import('./ChmodCalculator'), 'generator'),
  // Batch 11 tools
  'barcode-generator': createToolImport(() => import('./BarcodeGenerator'), 'generator'),
  'text-to-speech': createToolImport(() => import('./TextToSpeech'), 'editor'),
  'url-parser': createToolImport(() => import('./UrlParser'), 'default'),
  'json-to-xml': createToolImport(() => import('./JsonToXml'), 'converter'),
  'text-wrapper': createToolImport(() => import('./TextWrapper'), 'editor'),
  'csv-to-json': createToolImport(() => import('./CsvToJson'), 'converter'),
  'html-entity': createToolImport(() => import('./HtmlEntityConverter'), 'converter'),
  'number-formatter': createToolImport(() => import('./NumberFormatter'), 'converter'),
  // Batch 12 - Security Tools
  'hmac-generator': createToolImport(() => import('./HmacGenerator'), 'converter'),
  'password-strength': createToolImport(() => import('./PasswordStrength'), 'default'),
  'totp-generator': createToolImport(() => import('./TotpGenerator'), 'generator'),
  // Batch 13 - Network Tools
  'user-agent-parser': createToolImport(() => import('./UserAgentParser'), 'default'),
  'cidr-calculator': createToolImport(() => import('./CidrCalculator'), 'generator'),
  'http-header-parser': createToolImport(() => import('./HttpHeaderParser'), 'default'),
  // Batch 14 - Math Tools
  'percentage-calculator': createToolImport(() => import('./PercentageCalculator'), 'generator'),
  'statistics-calculator': createToolImport(() => import('./StatisticsCalculator'), 'generator'),
  'scientific-calculator': createToolImport(() => import('./ScientificCalculator'), 'generator'),
  // Batch 15 - Text Tools
  'text-sorter': createToolImport(() => import('./TextSorter'), 'editor'),
  'text-extractor': createToolImport(() => import('./TextExtractor'), 'editor'),
  'emoji-picker': createToolImport(() => import('./EmojiPicker'), 'default'),
  // Batch 16 - Converter Tools
  'json-to-sql': createToolImport(() => import('./JsonToSql'), 'converter'),
  'toml-json': createToolImport(() => import('./TomlJson'), 'converter'),
  'json-to-java': createToolImport(() => import('./JsonToJava'), 'converter'),
  'json-to-python': createToolImport(() => import('./JsonToPython'), 'converter'),
  'json-to-kotlin': createToolImport(() => import('./JsonToKotlin'), 'converter'),
  // Batch 17 - Image Tools
  'image-compressor': createToolImport(() => import('./ImageCompressor'), 'default'),
  'image-converter': createToolImport(() => import('./ImageConverter'), 'default'),
  'favicon-generator': createToolImport(() => import('./FaviconGenerator'), 'generator'),
  'image-cropper': createToolImport(() => import('./ImageCropper'), 'default'),
  // Batch 18 - Development Tools
  'gitignore-generator': createToolImport(() => import('./GitignoreGenerator'), 'generator'),
  'docker-compose-generator': createToolImport(() => import('./DockerComposeGenerator'), 'generator'),
  'package-json-generator': createToolImport(() => import('./PackageJsonGenerator'), 'generator'),
  // Batch 19 - New Popular Tools
  'json-minifier': createToolImport(() => import('./JsonMinifier'), 'editor'),
  'timezone-converter': createToolImport(() => import('./TimezoneConverter'), 'converter'),
  'color-contrast-checker': createToolImport(() => import('./ColorContrastChecker'), 'default'),
  'markdown-table-generator': createToolImport(() => import('./MarkdownTableGenerator'), 'generator'),
  'base58': createToolImport(() => import('./Base58'), 'converter'),
  // Batch 20 - SEO & Development Tools
  'meta-tag-generator': createToolImport(() => import('./MetaTagGenerator'), 'generator'),
  'robots-txt-generator': createToolImport(() => import('./RobotsTxtGenerator'), 'generator'),
  'opengraph-preview': createToolImport(() => import('./OpenGraphPreview'), 'default'),
  'css-grid-generator': createToolImport(() => import('./CssGridGenerator'), 'generator'),
  'css-flexbox-generator': createToolImport(() => import('./CssFlexboxGenerator'), 'generator'),
  'jwt-generator': createToolImport(() => import('./JwtGenerator'), 'generator'),
  'cron-explainer': createToolImport(() => import('./CronExplainer'), 'default'),
  'json-to-graphql': createToolImport(() => import('./JsonToGraphql'), 'converter'),
  'sql-to-mongo': createToolImport(() => import('./SqlToMongo'), 'converter'),
  // Batch 21 - Code & CSS Tools
  'json-to-csharp': createToolImport(() => import('./JsonToCsharp'), 'converter'),
  'json-to-rust': createToolImport(() => import('./JsonToRust'), 'converter'),
  'json-to-swift': createToolImport(() => import('./JsonToSwift'), 'converter'),
  'css-minifier': createToolImport(() => import('./CssMinifier'), 'editor'),
  'js-minifier': createToolImport(() => import('./JsMinifier'), 'editor'),
  'box-shadow-generator': createToolImport(() => import('./BoxShadowGenerator'), 'generator'),
  'border-radius-generator': createToolImport(() => import('./BorderRadiusGenerator'), 'generator'),
  'text-to-ascii-art': createToolImport(() => import('./TextToAsciiArt'), 'converter'),
  // Batch 22 - Utility Tools
  'color-shades-generator': createToolImport(() => import('./ColorShadesGenerator'), 'generator'),
  'json-flattener': createToolImport(() => import('./JsonFlattener'), 'converter'),
  'base85': createToolImport(() => import('./Base85'), 'converter'),
  'html-to-markdown': createToolImport(() => import('./HtmlToMarkdown'), 'converter'),
  'regex-generator': createToolImport(() => import('./RegexGenerator'), 'generator'),
  'url-shortener-preview': createToolImport(() => import('./UrlShortenerPreview'), 'default'),
  // Batch 23 - More Utility Tools
  'json-viewer': createToolImport(() => import('./JsonViewer'), 'editor'),
  'xml-to-json': createToolImport(() => import('./XmlToJson'), 'converter'),
  'ip-address-generator': createToolImport(() => import('./IpAddressGenerator'), 'generator'),
  'css-gradient-text': createToolImport(() => import('./CssGradientText'), 'generator'),
  'sitemap-generator': createToolImport(() => import('./SitemapGenerator'), 'generator'),
  // Batch 24 - Advanced Tools
  'json-to-php': createToolImport(() => import('./JsonToPhp'), 'converter'),
  'css-filter-generator': createToolImport(() => import('./CssFilterGenerator'), 'generator'),
  'text-diff-patch': createToolImport(() => import('./TextDiffPatch'), 'editor'),
  'encoding-detector': createToolImport(() => import('./EncodingDetector'), 'default'),
  // Batch 25 - More Tools
  'css-clip-path-generator': createToolImport(() => import('./CssClipPathGenerator'), 'generator'),
  'uuid-validator': createToolImport(() => import('./UuidValidator'), 'default'),
  'text-hash-comparator': createToolImport(() => import('./TextHashComparator'), 'converter'),
  'json-path-finder': createToolImport(() => import('./JsonPathFinder'), 'editor'),
  'canvas-drawing': createToolImport(() => import('./CanvasDrawing'), 'default'),
  // Batch 26 - New Tools
  'json-escape': createToolImport(() => import('./JsonEscape'), 'converter'),
  'css-animation-generator': createToolImport(() => import('./CssAnimationGenerator'), 'generator'),
  'text-case-counter': createToolImport(() => import('./TextCaseCounter'), 'editor'),
  'dns-lookup': createToolImport(() => import('./DnsLookup'), 'default'),
  'image-resizer': createToolImport(() => import('./ImageResizer'), 'default'),
  // Batch 27 - Popular Overseas Tools
  'ssl-checker': createToolImport(() => import('./SslChecker'), 'default'),
  'whois-lookup': createToolImport(() => import('./WhoisLookup'), 'default'),
  'port-reference': createToolImport(() => import('./PortScanner'), 'default'),
  'privacy-policy-generator': createToolImport(() => import('./PrivacyPolicyGenerator'), 'generator'),
  'terms-generator': createToolImport(() => import('./TermsGenerator'), 'generator'),
  'cookie-policy-generator': createToolImport(() => import('./CookiePolicyGenerator'), 'generator'),
  'json-to-tsv': createToolImport(() => import('./JsonToTsv'), 'converter'),
  'csv-viewer': createToolImport(() => import('./CsvViewer'), 'editor'),
  'htaccess-generator': createToolImport(() => import('./HtaccessGenerator'), 'generator'),
  'nginx-config-generator': createToolImport(() => import('./NginxConfigGenerator'), 'generator'),
  'curl-converter': createToolImport(() => import('./CurlConverter'), 'converter'),
  'reading-time-calculator': createToolImport(() => import('./ReadingTimeCalculator'), 'default'),
  // Batch 28 - New Popular Tools
  'open-graph-generator': createToolImport(() => import('./OpenGraphGenerator'), 'generator'),
  'twitter-card-generator': createToolImport(() => import('./TwitterCardGenerator'), 'generator'),
  'mime-type-lookup': createToolImport(() => import('./MimeTypeLookup'), 'default'),
  'http-status-codes': createToolImport(() => import('./HttpStatusCodes'), 'default'),
  'string-obfuscator': createToolImport(() => import('./StringObfuscator'), 'converter'),
  'text-cleaner': createToolImport(() => import('./TextCleaner'), 'editor'),
  'list-randomizer': createToolImport(() => import('./ListRandomizer'), 'editor'),
  'sql-generator': createToolImport(() => import('./SqlGenerator'), 'generator'),
  // Batch 29 - New Tools from toolfk.com
  'htaccess-to-nginx': createToolImport(() => import('./HtaccessToNginx'), 'converter'),
  'js-obfuscator': createToolImport(() => import('./JsObfuscator'), 'editor'),
  'image-watermark': createToolImport(() => import('./ImageWatermark'), 'default'),
  'svg-to-image': createToolImport(() => import('./SvgToImage'), 'default'),
  'hex-base64-converter': createToolImport(() => import('./HexBase64Converter'), 'converter'),
  // Batch 30 - More Tools
  'pdf-to-base64': createToolImport(() => import('./PdfToBase64'), 'converter'),
  'audio-to-base64': createToolImport(() => import('./AudioToBase64'), 'converter'),
  'video-to-base64': createToolImport(() => import('./VideoToBase64'), 'converter'),
  'file-size-calculator': createToolImport(() => import('./FileSizeCalculator'), 'generator'),
  'ascii-table': createToolImport(() => import('./AsciiTable'), 'default'),
  // Batch 31 - More Tools
  'text-to-hex': createToolImport(() => import('./TextToHex'), 'converter'),
  'css-variables-generator': createToolImport(() => import('./CssVariablesGenerator'), 'generator'),
  'lorem-picsum': createToolImport(() => import('./LoremPicsum'), 'generator'),
  'regex-escape': createToolImport(() => import('./RegexEscape'), 'converter'),
  'html-to-text': createToolImport(() => import('./HtmlToText'), 'converter'),
  'binary-to-decimal': createToolImport(() => import('./BinaryToDecimal'), 'converter'),
  'octal-converter': createToolImport(() => import('./OctalConverter'), 'converter'),
  'text-to-nato': createToolImport(() => import('./TextToNato'), 'converter'),
  'crc32-calculator': createToolImport(() => import('./Crc32Calculator'), 'generator'),
  'mac-address-generator': createToolImport(() => import('./MacAddressGenerator'), 'generator'),
  // Batch 32 - New Popular Tools (to reach 200)
  'ip-validator': createToolImport(() => import('./IpValidator'), 'default'),
  'json-merger': createToolImport(() => import('./JsonMerger'), 'converter'),
  'text-template': createToolImport(() => import('./TextTemplate'), 'editor'),
  'base-calculator': createToolImport(() => import('./BaseCalculator'), 'generator'),
  'color-name-finder': createToolImport(() => import('./ColorNameFinder'), 'default'),
  'char-frequency': createToolImport(() => import('./CharFrequency'), 'editor'),
  'json-to-dart': createToolImport(() => import('./JsonToDart'), 'converter'),
  'sql-to-json': createToolImport(() => import('./SqlToJson'), 'converter'),
  // Batch 33 - Chart Tools (数据图表工具) - SSR disabled for chart libraries
  'bar-chart-generator': createToolImport(() => import('./BarChartGenerator'), 'chart', false),
  'line-chart-generator': createToolImport(() => import('./LineChartGenerator'), 'chart', false),
  'pie-chart-generator': createToolImport(() => import('./PieChartGenerator'), 'chart', false),
  'radar-chart-generator': createToolImport(() => import('./RadarChartGenerator'), 'chart', false),
  'scatter-chart-generator': createToolImport(() => import('./ScatterChartGenerator'), 'chart', false),
  'area-chart-generator': createToolImport(() => import('./AreaChartGenerator'), 'chart', false),
  'funnel-chart-generator': createToolImport(() => import('./FunnelChartGenerator'), 'chart', false),
  'gauge-chart-generator': createToolImport(() => import('./GaugeChartGenerator'), 'chart', false),
  'heatmap-chart-generator': createToolImport(() => import('./HeatmapChartGenerator'), 'chart', false),
  'treemap-chart-generator': createToolImport(() => import('./TreemapChartGenerator'), 'chart', false),
  // Batch 34 - New Chart Tools (新增图表工具)
  'doughnut-chart-generator': createToolImport(() => import('./DoughnutChartGenerator'), 'chart', false),
  'sankey-chart-generator': createToolImport(() => import('./SankeyChartGenerator'), 'chart', false),
  'sunburst-chart-generator': createToolImport(() => import('./SunburstChartGenerator'), 'chart', false),
  'candlestick-chart-generator': createToolImport(() => import('./CandlestickChartGenerator'), 'chart', false),
  'boxplot-chart-generator': createToolImport(() => import('./BoxplotChartGenerator'), 'chart', false),
  'wordcloud-generator': createToolImport(() => import('./WordCloudGenerator'), 'chart', false),
  'graph-chart-generator': createToolImport(() => import('./GraphChartGenerator'), 'chart', false),
  'calendar-heatmap-generator': createToolImport(() => import('./CalendarHeatmapGenerator'), 'chart', false),
  'polar-bar-chart-generator': createToolImport(() => import('./PolarBarChartGenerator'), 'chart', false),
  'parallel-chart-generator': createToolImport(() => import('./ParallelChartGenerator'), 'chart', false),
  'bubble-chart-generator': createToolImport(() => import('./BubbleChartGenerator'), 'chart', false),
  'tree-chart-generator': createToolImport(() => import('./TreeChartGenerator'), 'chart', false),
  'theme-river-generator': createToolImport(() => import('./ThemeRiverGenerator'), 'chart', false),
  'gantt-chart-generator': createToolImport(() => import('./GanttChartGenerator'), 'chart', false),
  'venn-diagram-generator': createToolImport(() => import('./VennDiagramGenerator'), 'chart', false),
  'timeline-chart-generator': createToolImport(() => import('./TimelineChartGenerator'), 'chart', false),
  // Batch 35 - New Chart Tools from 67tool.com (新增图表工具)
  'nightingale-rose-chart-generator': createToolImport(() => import('./NightingaleRoseChartGenerator'), 'chart', false),
  'grouped-bar-chart-generator': createToolImport(() => import('./GroupedBarChartGenerator'), 'chart', false),
  'stacked-bar-chart-generator': createToolImport(() => import('./StackedBarChartGenerator'), 'chart', false),
  'grouped-line-chart-generator': createToolImport(() => import('./GroupedLineChartGenerator'), 'chart', false),
  'step-line-chart-generator': createToolImport(() => import('./StepLineChartGenerator'), 'chart', false),
  'waterfall-chart-generator': createToolImport(() => import('./WaterfallChartGenerator'), 'chart', false),
  'stacked-area-chart-generator': createToolImport(() => import('./StackedAreaChartGenerator'), 'chart', false),
  'positive-negative-bar-chart-generator': createToolImport(() => import('./PositiveNegativeBarChartGenerator'), 'chart', false),
  // Batch 36 - New Chart Tools (新增图表工具)
  'percentage-stacked-bar-chart-generator': createToolImport(() => import('./PercentageStackedBarChartGenerator'), 'chart', false),
  'mixed-chart-generator': createToolImport(() => import('./MixedChartGenerator'), 'chart', false),
  'ring-progress-chart-generator': createToolImport(() => import('./RingProgressChartGenerator'), 'chart', false),
  'liquid-fill-chart-generator': createToolImport(() => import('./LiquidFillChartGenerator'), 'chart', false),
  'multi-ring-chart-generator': createToolImport(() => import('./MultiRingChartGenerator'), 'chart', false),
  'half-doughnut-chart-generator': createToolImport(() => import('./HalfDoughnutChartGenerator'), 'chart', false),
  'nested-pie-chart-generator': createToolImport(() => import('./NestedPieChartGenerator'), 'chart', false),
  'pictorial-bar-chart-generator': createToolImport(() => import('./PictorialBarChartGenerator'), 'chart', false),
  // Batch 37 - New Popular Tools (热门低竞争工具)
  'env-parser': createToolImport(() => import('./EnvParser'), 'editor'),
  'json-schema-generator': createToolImport(() => import('./JsonSchemaGenerator'), 'generator'),
  'time-calculator': createToolImport(() => import('./TimeCalculator'), 'generator'),
  'batch-timestamp-converter': createToolImport(() => import('./BatchTimestampConverter'), 'converter'),
  'regex-visualizer': createToolImport(() => import('./RegexVisualizer'), 'editor'),
  'crontab-calendar': createToolImport(() => import('./CrontabCalendar'), 'default'),
  'fake-data-generator': createToolImport(() => import('./FakeDataGenerator'), 'generator'),
  // Batch 38 - Image Tools (图像工具)
  'image-collage': createToolImport(() => import('./ImageCollage'), 'default'),
  'image-splitter': createToolImport(() => import('./ImageSplitter'), 'default'),
  'image-rounder': createToolImport(() => import('./ImageRounder'), 'default'),
  'image-border': createToolImport(() => import('./ImageBorder'), 'default'),
  'image-flip-rotate': createToolImport(() => import('./ImageFlipRotate'), 'default'),
  'image-adjustment': createToolImport(() => import('./ImageAdjustment'), 'default'),
  'image-frosted-glass': createToolImport(() => import('./ImageFrostedGlass'), 'default'),
  'image-to-ico': createToolImport(() => import('./ImageToIco'), 'default'),
  'gif-maker': createToolImport(() => import('./GifMaker'), 'default', false),
  'gif-splitter': createToolImport(() => import('./GifSplitter'), 'default', false),
  'gif-compressor': createToolImport(() => import('./GifCompressor'), 'default', false),
  'image-to-webp': createToolImport(() => import('./ImageToWebp'), 'default'),
  'exif-viewer': createToolImport(() => import('./ExifViewer'), 'default'),
  'color-extractor': createToolImport(() => import('./ColorExtractor'), 'default'),
  // Batch 39 - Office Tools (办公工具)
  'invoice-generator': createToolImport(() => import('./InvoiceGenerator'), 'generator'),
  'resume-builder': createToolImport(() => import('./ResumeBuilder'), 'generator'),
  'signature-pad': createToolImport(() => import('./SignaturePad'), 'default'),
  'pomodoro-timer': createToolImport(() => import('./PomodoroTimer'), 'default'),
  'meeting-notes': createToolImport(() => import('./MeetingNotes'), 'editor'),
  'business-days-calculator': createToolImport(() => import('./BusinessDaysCalculator'), 'generator'),
  'salary-calculator': createToolImport(() => import('./SalaryCalculator'), 'generator'),
  // Batch 40 - Excel & PDF Tools (Excel 和 PDF 工具)
  'excel-to-json': createToolImport(() => import('./ExcelToJson'), 'converter'),
  'json-to-excel': createToolImport(() => import('./JsonToExcel'), 'converter'),
  'excel-viewer': createToolImport(() => import('./ExcelViewer'), 'editor'),
  'excel-merger': createToolImport(() => import('./ExcelMerger'), 'default'),
  'pdf-to-image': createToolImport(() => import('./PdfToImage'), 'default', false),
  'image-to-pdf': createToolImport(() => import('./ImageToPdf'), 'default', false),
  'pdf-merger': createToolImport(() => import('./PdfMerger'), 'default', false),
  'pdf-splitter': createToolImport(() => import('./PdfSplitter'), 'default', false),
  'pdf-compressor': createToolImport(() => import('./PdfCompressor'), 'default', false),
  'pdf-rotator': createToolImport(() => import('./PdfRotator'), 'default', false),
  // Batch 41 - New Utility Tools (新实用工具)
  'markdown-editor': createToolImport(() => import('./MarkdownEditor'), 'editor'),
  'world-clock': createToolImport(() => import('./WorldClock'), 'default'),
  'stopwatch': createToolImport(() => import('./Stopwatch'), 'default'),
  'countdown-timer': createToolImport(() => import('./CountdownTimer'), 'default'),
  'note-pad': createToolImport(() => import('./NotePad'), 'editor'),
  // Batch 42 - Document Converter Tools
  'pdf-to-text': createToolImport(() => import('./PdfToText'), 'converter'),
  'word-to-txt': createToolImport(() => import('./WordToTxt'), 'converter'),
  'word-to-html': createToolImport(() => import('./WordToHtml'), 'converter'),
  'excel-to-csv': createToolImport(() => import('./ExcelToCsv'), 'converter'),
  'csv-to-excel': createToolImport(() => import('./CsvToExcel'), 'converter'),
  // Batch 43 - Popular Calculator Tools (热门计算器工具)
  'loan-calculator': createToolImport(() => import('./LoanCalculator'), 'generator'),
  'bmi-calculator': createToolImport(() => import('./BmiCalculator'), 'generator'),
  'age-calculator': createToolImport(() => import('./AgeCalculator'), 'generator'),
  'tip-calculator': createToolImport(() => import('./TipCalculator'), 'generator'),
  'discount-calculator': createToolImport(() => import('./DiscountCalculator'), 'generator'),
  'compound-interest-calculator': createToolImport(() => import('./CompoundInterestCalculator'), 'generator'),
  'binary-calculator': createToolImport(() => import('./BinaryCalculator'), 'generator'),
  'hex-calculator': createToolImport(() => import('./HexCalculator'), 'generator'),
  'ip-subnet-calculator': createToolImport(() => import('./IpSubnetCalculator'), 'generator'),
  'aspect-ratio-calculator-enhanced': createToolImport(() => import('./AspectRatioCalculatorEnhanced'), 'generator'),
  // Batch 44 - Text & Utility Tools (文本和实用工具)
  'chinese-lorem-ipsum': createToolImport(() => import('./ChineseLoremIpsum'), 'generator'),
  'text-to-image': createToolImport(() => import('./TextToImage'), 'generator'),
  'text-to-handwriting': createToolImport(() => import('./TextToHandwriting'), 'generator'),
  'screen-resolution-tester': createToolImport(() => import('./ScreenResolutionTester'), 'default'),
  'keyboard-tester': createToolImport(() => import('./KeyboardTester'), 'default'),
  'typing-speed-test': createToolImport(() => import('./TypingSpeedTest'), 'default'),
  'morse-code-player': createToolImport(() => import('./MorseCodePlayer'), 'default'),
  // Batch 45 - Popular Tools Batch 3
  'currency-converter': createToolImport(() => import('./CurrencyConverter'), 'converter'),
  'roi-calculator': createToolImport(() => import('./RoiCalculator'), 'generator'),
  'mortgage-calculator': createToolImport(() => import('./MortgageCalculator'), 'generator'),
  'tax-calculator': createToolImport(() => import('./TaxCalculator'), 'generator'),
  // Health Tools
  'calorie-calculator': createToolImport(() => import('./CalorieCalculator'), 'generator'),
  'water-intake-calculator': createToolImport(() => import('./WaterIntakeCalculator'), 'generator'),
  'sleep-calculator': createToolImport(() => import('./SleepCalculator'), 'generator'),
  'due-date-calculator': createToolImport(() => import('./DueDateCalculator'), 'generator'),
  // Entertainment Tools
  'love-calculator': createToolImport(() => import('./LoveCalculator'), 'generator'),
  'decision-wheel': createToolImport(() => import('./DecisionWheel'), 'default', false),
  'name-generator': createToolImport(() => import('./NameGenerator'), 'generator'),
  'random-picker': createToolImport(() => import('./RandomPicker'), 'generator'),
  'coin-flipper': createToolImport(() => import('./CoinFlipper'), 'default'),
  'dice-roller': createToolImport(() => import('./DiceRoller'), 'default'),
  'team-generator': createToolImport(() => import('./TeamGenerator'), 'generator'),
  // Daily Calculators
  'countdown-days-calculator': createToolImport(() => import('./CountdownDaysCalculator'), 'generator'),
  'fuel-cost-calculator': createToolImport(() => import('./FuelCostCalculator'), 'generator'),
  'electricity-cost-calculator': createToolImport(() => import('./ElectricityCostCalculator'), 'generator'),
  'gpa-calculator': createToolImport(() => import('./GpaCalculator'), 'generator'),
  'pace-calculator': createToolImport(() => import('./PaceCalculator'), 'generator'),
  // Size Converters
  'shoe-size-converter': createToolImport(() => import('./ShoeSizeConverter'), 'converter'),
  'ring-size-calculator': createToolImport(() => import('./RingSizeCalculator'), 'generator'),
  'bra-size-calculator': createToolImport(() => import('./BraSizeCalculator'), 'generator'),
  // Home Improvement
  'concrete-calculator': createToolImport(() => import('./ConcreteCalculator'), 'generator'),
  'paint-calculator': createToolImport(() => import('./PaintCalculator'), 'generator'),
  'tile-calculator': createToolImport(() => import('./TileCalculator'), 'generator'),
  // Social Media Tools
  'instagram-font-generator': createToolImport(() => import('./InstagramFontGenerator'), 'generator'),
  'social-media-size-guide': createToolImport(() => import('./SocialMediaSizeGuide'), 'default'),
  // SEO/Content Tools
  'keyword-density-checker': createToolImport(() => import('./KeywordDensityChecker'), 'editor'),
  'text-summarizer': createToolImport(() => import('./TextSummarizer'), 'editor'),
  'paraphrase-tool': createToolImport(() => import('./ParaphraseTool'), 'editor'),
  // Development Tools
  'graphql-formatter': createToolImport(() => import('./GraphqlFormatter'), 'editor'),
  'code-screenshot-generator': createToolImport(() => import('./CodeScreenshotGenerator'), 'generator'),
  'number-system-converter': createToolImport(() => import('./NumberSystemConverter'), 'converter'),
  'subnet-calculator-enhanced': createToolImport(() => import('./SubnetCalculatorEnhanced'), 'generator'),
  // Batch 46 - European Popular Tools (欧洲热门工具)
  'iban-validator': createToolImport(() => import('./IbanValidator'), 'default'),
  'vat-calculator': createToolImport(() => import('./VatCalculator'), 'generator'),
  'carbon-footprint-calculator': createToolImport(() => import('./CarbonFootprintCalculator'), 'generator'),
  'gdpr-consent-generator': createToolImport(() => import('./GdprConsentGenerator'), 'generator'),
  'metric-imperial-converter': createToolImport(() => import('./MetricImperialConverter'), 'converter'),
  'bic-swift-lookup': createToolImport(() => import('./BicSwiftLookup'), 'default'),
  // Batch 47 - Global Popular Tools (全球热门工具)
  'email-validator': createToolImport(() => import('./EmailValidator'), 'default'),
  'phone-formatter': createToolImport(() => import('./PhoneFormatter'), 'converter'),
  'credit-card-validator': createToolImport(() => import('./CreditCardValidator'), 'default'),
  'color-blindness-simulator': createToolImport(() => import('./ColorBlindnessSimulator'), 'default'),
  'aspect-ratio-resizer': createToolImport(() => import('./AspectRatioResizer'), 'default'),
  'markdown-to-pdf': createToolImport(() => import('./MarkdownToPdf'), 'converter'),
  // Batch 48 - Popular Online Tools (热门在线工具)
  'speech-timer': createToolImport(() => import('./SpeechTimer'), 'default'),
  'habit-tracker': createToolImport(() => import('./HabitTracker'), 'default'),
  'flip-text': createToolImport(() => import('./FlipText'), 'converter'),
  'strikethrough-text': createToolImport(() => import('./StrikethroughText'), 'converter'),
  'small-text-generator': createToolImport(() => import('./SmallTextGenerator'), 'generator'),
  'binary-to-text': createToolImport(() => import('./BinaryToText'), 'converter'),
  'roman-numeral-converter': createToolImport(() => import('./RomanNumeralConverter'), 'converter'),
  'fraction-calculator': createToolImport(() => import('./FractionCalculator'), 'generator'),
  'percentage-change-calculator': createToolImport(() => import('./PercentageChangeCalculator'), 'generator'),
  'random-color-generator': createToolImport(() => import('./RandomColorGenerator'), 'generator'),
  // Batch 49 - Popular Word & Text Tools
  'anagram-solver': createToolImport(() => import('./AnagramSolver'), 'default'),
  'word-unscrambler': createToolImport(() => import('./WordUnscrambler'), 'default'),
  'text-to-pdf': createToolImport(() => import('./TextToPdf'), 'converter'),
  'unit-price-calculator': createToolImport(() => import('./UnitPriceCalculator'), 'generator'),
  'bionic-reading-converter': createToolImport(() => import('./BionicReadingConverter'), 'converter'),
  'palindrome-checker': createToolImport(() => import('./PalindromeChecker'), 'default'),
  'character-map': createToolImport(() => import('./CharacterMap'), 'default'),
  'text-repeater': createToolImport(() => import('./TextRepeater'), 'editor'),
  'fake-name-generator': createToolImport(() => import('./FakeNameGenerator'), 'generator'),
  'invisible-character-generator': createToolImport(() => import('./InvisibleCharacterGenerator'), 'generator'),
  // Batch 50 - Popular Overseas Developer Tools (海外热门开发工具)
  'json-to-proto': createToolImport(() => import('./JsonToProto'), 'converter'),
  'svg-to-png': createToolImport(() => import('./SvgToPng'), 'default'),
  'webp-to-png': createToolImport(() => import('./WebpToPng'), 'default'),
  'png-to-svg': createToolImport(() => import('./PngToSvg'), 'default'),
  'html-to-pdf': createToolImport(() => import('./HtmlToPdf'), 'converter'),
  'json-to-table': createToolImport(() => import('./JsonToTable'), 'converter'),
  'yaml-validator': createToolImport(() => import('./YamlValidator'), 'editor'),
  'xml-validator': createToolImport(() => import('./XmlValidator'), 'editor'),
  'css-to-tailwind': createToolImport(() => import('./CssToTailwind'), 'converter'),
  'tailwind-to-css': createToolImport(() => import('./TailwindToCss'), 'converter'),
  'svg-editor': createToolImport(() => import('./SvgEditor'), 'editor'),
  'json-to-form': createToolImport(() => import('./JsonToForm'), 'generator'),
  'api-tester': createToolImport(() => import('./ApiTester'), 'default'),
  'jwt-debugger': createToolImport(() => import('./JwtDebugger'), 'editor'),
  'csp-generator': createToolImport(() => import('./CspGenerator'), 'generator'),
  'sri-hash-generator': createToolImport(() => import('./SriHashGenerator'), 'generator'),
  'cors-tester': createToolImport(() => import('./CorsTester'), 'default'),
  'json-to-zod': createToolImport(() => import('./JsonToZod'), 'converter'),
  'typescript-to-json': createToolImport(() => import('./TypescriptToJson'), 'converter'),
  'markdown-to-slides': createToolImport(() => import('./MarkdownToSlides'), 'editor'),
  // Batch 53 - AI/Text Processing Tools (AI/文本处理工具)
  'ai-text-humanizer': createToolImport(() => import('./AiTextHumanizer'), 'editor'),
  'text-spinner': createToolImport(() => import('./TextSpinner'), 'editor'),
  'readability-checker': createToolImport(() => import('./ReadabilityChecker'), 'editor'),
  'grammar-checker': createToolImport(() => import('./GrammarChecker'), 'editor'),
  // Batch 53 - Code Formatters (代码格式化工具)
  'typescript-playground': createToolImport(() => import('./TypescriptPlayground'), 'editor', false),
  'python-formatter': createToolImport(() => import('./PythonFormatter'), 'editor'),
  'go-formatter': createToolImport(() => import('./GoFormatter'), 'editor'),
  'rust-formatter': createToolImport(() => import('./RustFormatter'), 'editor'),
  'yaml-formatter': createToolImport(() => import('./YamlFormatter'), 'editor'),
  // Batch 53 - CSS Design Tools (CSS 设计工具)
  'text-shadow-generator': createToolImport(() => import('./TextShadowGenerator'), 'generator'),
  'svg-pattern-generator': createToolImport(() => import('./SvgPatternGenerator'), 'generator'),
  'css-triangle-generator': createToolImport(() => import('./CssTriangleGenerator'), 'generator'),
  'aspect-ratio-box-generator': createToolImport(() => import('./AspectRatioBoxGenerator'), 'generator'),
  // Batch 53 - Calculators (计算器工具)
  'screen-time-calculator': createToolImport(() => import('./ScreenTimeCalculator'), 'generator'),
  'typing-time-calculator': createToolImport(() => import('./TypingTimeCalculator'), 'generator'),
  'download-time-calculator': createToolImport(() => import('./DownloadTimeCalculator'), 'generator'),
  // Batch 53 - Data Converters (数据转换工具)
  'ical-parser': createToolImport(() => import('./IcalParser'), 'converter'),
  'vcard-parser': createToolImport(() => import('./VcardParser'), 'converter'),
  // Batch 51 - Config Generators (配置生成器)
  'dockerfile-generator': createToolImport(() => import('./DockerfileGenerator'), 'generator'),
  'eslint-config-generator': createToolImport(() => import('./EslintConfigGenerator'), 'generator'),
  'prettier-config-generator': createToolImport(() => import('./PrettierConfigGenerator'), 'generator'),
  'tsconfig-generator': createToolImport(() => import('./TsconfigGenerator'), 'generator'),
  'editorconfig-generator': createToolImport(() => import('./EditorconfigGenerator'), 'generator'),
  // Batch 51 - Doc Generators (文档生成器)
  'github-readme-generator': createToolImport(() => import('./GithubReadmeGenerator'), 'generator'),
  'changelog-generator': createToolImport(() => import('./ChangelogGenerator'), 'generator'),
  'license-generator': createToolImport(() => import('./LicenseGenerator'), 'generator'),
  // Batch 51 - Cipher Tools (加密工具)
  'rot13-encoder': createToolImport(() => import('./Rot13Encoder'), 'converter'),
  'caesar-cipher': createToolImport(() => import('./CaesarCipher'), 'converter'),
  'vigenere-cipher': createToolImport(() => import('./VigenereCipher'), 'converter'),
  // Batch 51 - Checksum Tool (校验和工具)
  'checksum-verifier': createToolImport(() => import('./ChecksumVerifier'), 'default'),
  // Batch 51 - Finance Calculators (财务计算器)
  'inflation-calculator': createToolImport(() => import('./InflationCalculator'), 'generator'),
  'break-even-calculator': createToolImport(() => import('./BreakEvenCalculator'), 'generator'),
  'margin-calculator': createToolImport(() => import('./MarginCalculator'), 'generator'),
  'markup-calculator': createToolImport(() => import('./MarkupCalculator'), 'generator'),
  // Batch 51 - Social Tools (社交工具)
  'hashtag-generator': createToolImport(() => import('./HashtagGenerator'), 'generator'),
  'email-signature-generator': createToolImport(() => import('./EmailSignatureGenerator'), 'generator'),
  // Batch 52 - CSS Design Generators (CSS 设计生成器)
  'glassmorphism-generator': createToolImport(() => import('./GlassmorphismGenerator'), 'generator'),
  'neumorphism-generator': createToolImport(() => import('./NeumorphismGenerator'), 'generator'),
  'blob-generator': createToolImport(() => import('./BlobGenerator'), 'generator'),
  'wave-generator': createToolImport(() => import('./WaveGenerator'), 'generator'),
  'mesh-gradient-generator': createToolImport(() => import('./MeshGradientGenerator'), 'generator'),
  'noise-texture-generator': createToolImport(() => import('./NoiseTextureGenerator'), 'generator'),
  // Batch 52 - Developer Tools (开发者工具)
  'commit-message-generator': createToolImport(() => import('./CommitMessageGenerator'), 'generator'),
  // Batch 52 - Calculators (计算器)
  'bandwidth-calculator': createToolImport(() => import('./BandwidthCalculator'), 'generator'),
  'data-transfer-calculator': createToolImport(() => import('./DataTransferCalculator'), 'generator'),
  'pixel-density-calculator': createToolImport(() => import('./PixelDensityCalculator'), 'generator'),
  'dpi-calculator': createToolImport(() => import('./DpiCalculator'), 'generator'),

  // Batch 54 - Developer Tools - API and Network Tools (开发者工具 - API 和网络工具)
  'curl-to-code-generator': createToolImport(() => import('./CurlToCodeGenerator'), 'converter'),
  'http-status-code-reference': createToolImport(() => import('./HttpStatusCodeReference'), 'default'),
  'jwt-payload-decoder': createToolImport(() => import('./JwtPayloadDecoder'), 'converter'),
  'base64-image-converter': createToolImport(() => import('./Base64ImageConverter'), 'converter'),
  'url-query-string-parser': createToolImport(() => import('./UrlQueryStringParser'), 'converter'),
  'request-header-builder': createToolImport(() => import('./RequestHeaderBuilder'), 'generator'),
  'webhook-tester': createToolImport(() => import('./WebhookTester'), 'default'),
  'api-response-formatter': createToolImport(() => import('./ApiResponseFormatter'), 'editor'),

  // Batch 54 - Developer Tools - Code Conversion and Generation (开发者工具 - 代码转换和生成)
  'sql-to-mongodb-converter': createToolImport(() => import('./SqlToMongodbConverter'), 'converter'),
  'json-to-protobuf-converter': createToolImport(() => import('./JsonToProtobufConverter'), 'converter'),
  'regex-to-code-generator': createToolImport(() => import('./RegexToCodeGenerator'), 'generator'),
  'swagger-to-code-generator': createToolImport(() => import('./SwaggerToCodeGenerator'), 'generator'),
  'database-migration-generator': createToolImport(() => import('./DatabaseMigrationGenerator'), 'generator'),
  'environment-variables-generator': createToolImport(() => import('./EnvironmentVariablesGenerator'), 'generator'),
  'docker-compose-generator-advanced': createToolImport(() => import('./DockerComposeGeneratorAdvanced'), 'generator'),
  'kubernetes-manifest-generator': createToolImport(() => import('./KubernetesManifestGenerator'), 'generator'),

  // Batch 54 - Developer Tools - Code Analysis and Optimization (开发者工具 - 代码分析和优化)
  'code-complexity-analyzer': createToolImport(() => import('./CodeComplexityAnalyzer'), 'editor'),
  'dependency-vulnerability-checker': createToolImport(() => import('./DependencyVulnerabilityChecker'), 'default'),
  'performance-profiler': createToolImport(() => import('./PerformanceProfiler'), 'editor'),
  'memory-leak-detector': createToolImport(() => import('./MemoryLeakDetector'), 'editor'),
  'code-duplication-finder': createToolImport(() => import('./CodeDuplicationFinder'), 'editor'),
  'unused-imports-finder': createToolImport(() => import('./UnusedImportsFinder'), 'editor'),
  'dead-code-analyzer': createToolImport(() => import('./DeadCodeAnalyzer'), 'editor'),

  // Batch 54 - Developer Tools - Database Tools (开发者工具 - 数据库工具)
  'sql-query-optimizer': createToolImport(() => import('./SqlQueryOptimizer'), 'editor'),
  'database-schema-visualizer': createToolImport(() => import('./DatabaseSchemaVisualizer'), 'default'),
  'sql-injection-tester': createToolImport(() => import('./SqlInjectionTester'), 'editor'),
  'database-connection-tester': createToolImport(() => import('./DatabaseConnectionTester'), 'default'),
  'query-execution-planner': createToolImport(() => import('./QueryExecutionPlanner'), 'editor'),
  'database-backup-scheduler': createToolImport(() => import('./DatabaseBackupScheduler'), 'generator'),

  // Batch 54 - Developer Tools - Version Control Tools (开发者工具 - 版本控制工具)
  'git-commit-message-generator': createToolImport(() => import('./GitCommitMessageGenerator'), 'generator'),
  'git-branch-naming-validator': createToolImport(() => import('./GitBranchNamingValidator'), 'default'),
  'merge-conflict-resolver': createToolImport(() => import('./MergeConflictResolver'), 'editor'),
  'git-history-visualizer': createToolImport(() => import('./GitHistoryVisualizer'), 'default'),
  'changelog-generator-advanced': createToolImport(() => import('./ChangelogGeneratorAdvanced'), 'generator'),
  'git-tag-manager': createToolImport(() => import('./GitTagManager'), 'generator'),

  // Batch 54 - Office Tools - Document and Content Management (办公工具 - 文档和内容管理)
  'markdown-to-html-converter': createToolImport(() => import('./MarkdownToHtmlConverter'), 'converter'),
  'document-outline-generator': createToolImport(() => import('./DocumentOutlineGenerator'), 'generator'),
  'table-of-contents-generator': createToolImport(() => import('./TableOfContentsGenerator'), 'generator'),
  'document-word-counter': createToolImport(() => import('./DocumentWordCounter'), 'editor'),
  'document-formatter': createToolImport(() => import('./DocumentFormatter'), 'editor'),
  'citation-formatter': createToolImport(() => import('./CitationFormatter'), 'converter'),

  // Batch 54 - Office Tools - Project Management Tools (办公工具 - 项目管理工具)
  'project-estimation-calculator': createToolImport(() => import('./ProjectEstimationCalculator'), 'generator'),
  'sprint-velocity-calculator': createToolImport(() => import('./SprintVelocityCalculator'), 'generator'),
  'resource-allocation-planner': createToolImport(() => import('./ResourceAllocationPlanner'), 'generator'),
  'project-risk-analyzer': createToolImport(() => import('./ProjectRiskAnalyzer'), 'generator'),
  'milestone-tracker': createToolImport(() => import('./MilestoneTracker'), 'default'),
  'team-capacity-planner': createToolImport(() => import('./TeamCapacityPlanner'), 'generator'),

  // Batch 54 - Office Tools - Meeting and Schedule Tools (办公工具 - 会议和日程工具)
  'meeting-minutes-generator': createToolImport(() => import('./MeetingMinutesGenerator'), 'generator'),
  'timezone-meeting-scheduler': createToolImport(() => import('./TimezoneMeetingScheduler'), 'generator'),
  'meeting-agenda-builder': createToolImport(() => import('./MeetingAgendaBuilder'), 'generator'),
  'calendar-availability-finder': createToolImport(() => import('./CalendarAvailabilityFinder'), 'default'),
  'meeting-room-finder': createToolImport(() => import('./MeetingRoomFinder'), 'default'),

  // Batch 54 - Office Tools - Finance and Budget Tools (办公工具 - 财务和预算工具)
  'invoice-template-generator': createToolImport(() => import('./InvoiceTemplateGenerator'), 'generator'),
  'expense-report-generator': createToolImport(() => import('./ExpenseReportGenerator'), 'generator'),
  'budget-variance-analyzer': createToolImport(() => import('./BudgetVarianceAnalyzer'), 'generator'),
  'cost-benefit-analyzer': createToolImport(() => import('./CostBenefitAnalyzer'), 'generator'),
  'financial-forecast-calculator': createToolImport(() => import('./FinancialForecastCalculator'), 'generator'),

  // Batch 55 - Popular Tools
  'ip-geolocation': createToolImport(() => import('./IpGeolocation'), 'network'),
  'screen-recorder': createToolImport(() => import('./ScreenRecorder'), 'office'),
};




