import type { APIContext } from 'astro';
import scheduleData from '../../lib/data/world-cup-schedule.json';

export interface Match {
  id: string;
  stage: 'group' | 'r32' | 'r16' | 'qf' | 'sf' | 'third' | 'final';
  group: string | null;
  utcTime: string;
  stadium: string;
  homeTeam: string;
  awayTeam: string;
  homePlaceholder: string | null;
  awayPlaceholder: string | null;
  venueCity: string;
  sequence: number;
}

const schedule = scheduleData as Match[];

// 1. RFC 5545 Text Escaping Helper
export function escapeText(text: string): string {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\\\')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;')
    .replace(/\r?\n/g, '\\n');
}

// 2. RFC 5545 Safe Byte-Length Folding Helper (Limit line length to 75 bytes)
export function foldLine(line: string): string {
  const encoder = new TextEncoder();
  const decoder = new TextDecoder();
  const bytes = encoder.encode(line);
  
  if (bytes.length <= 75) {
    return line;
  }

  const chunks: string[] = [];
  let offset = 0;
  let limit = 75; // First line can occupy up to 75 bytes

  while (offset < bytes.length) {
    const end = offset + limit;
    if (end >= bytes.length) {
      const chunk = decoder.decode(bytes.subarray(offset));
      chunks.push(offset === 0 ? chunk : ' ' + chunk);
      break;
    }

    // Backtrack to find a valid UTF-8 character boundary (non-continuation byte)
    // Continuation bytes in UTF-8 start with binary 10xxxxxx, i.e., 128 (0x80) to 191 (0xBF)
    let cut = end;
    while (cut > offset && bytes[cut] >= 0x80 && bytes[cut] <= 0xbf) {
      cut--;
    }

    if (cut === offset) {
      cut = end; // Fallback to raw cut if boundary not found
    }

    const chunk = decoder.decode(bytes.subarray(offset, cut));
    chunks.push(offset === 0 ? chunk : ' ' + chunk);
    
    offset = cut;
    limit = 74; // Subsequent folded lines have a space prepended, consuming 1 byte
  }

  return chunks.join('\r\n');
}

// 3. Convert Date to iCalendar standard UTC string (YYYYMMDDTHHMMSSZ)
export function formatIcsDate(date: Date): string {
  return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
}

function getStageName(stage: string): string {
  switch (stage) {
    case 'r32': return '32';
    case 'r16': return '16';
    case 'qf': return 'Quarter-Finals';
    case 'sf': return 'Semi-Finals';
    case 'third': return 'Third Place';
    case 'final': return 'Final';
    default: return '';
  }
}

// 4. Generate RFC 5545 iCalendar content string
export function generateIcsContent(matches: Match[], alarmMinutes?: number): string {
  const dtstamp = formatIcsDate(new Date());
  
  let ics = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//U2Tool//World Cup 2026 Calendar//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:FIFA World Cup 2026',
    'X-WR-TIMEZONE:UTC'
  ];

  for (const match of matches) {
    const start = new Date(match.utcTime);
    // DTEND defaults to 2 hours after DTSTART
    const end = new Date(start.getTime() + 2 * 60 * 60 * 1000);

    const isHomeTba = match.homeTeam.startsWith('TBA');
    const isAwayTba = match.awayTeam.startsWith('TBA');

    let summary = '';
    if (match.stage === 'group') {
      summary = `🏆 ${match.homeTeam} vs ${match.awayTeam} (Group ${match.group})`;
    } else {
      const stageLabel = `[Round of ${getStageName(match.stage)}]`;
      const homeLabel = isHomeTba ? match.homePlaceholder : match.homeTeam;
      const awayLabel = isAwayTba ? match.awayPlaceholder : match.awayTeam;
      summary = `🏆 ${stageLabel} ${homeLabel} vs ${awayLabel}`;
    }

    const description = `FIFA World Cup 2026 - ${match.stage.toUpperCase()}\n` +
      `Venue: ${match.venueCity} (${match.stadium})\n` +
      `Generated by u2tool.com`;

    const location = `${match.venueCity}, ${match.stadium}`;

    const eventLines = [
      'BEGIN:VEVENT',
      `UID:${match.id}-2026-FIFA-U2TOOL`,
      `DTSTAMP:${dtstamp}`,
      `DTSTART:${formatIcsDate(start)}`,
      `DTEND:${formatIcsDate(end)}`,
      `SUMMARY:${escapeText(summary)}`,
      `DESCRIPTION:${escapeText(description)}`,
      `LOCATION:${escapeText(location)}`,
      `SEQUENCE:${match.sequence || 0}`
    ];

    if (alarmMinutes !== undefined && !isNaN(alarmMinutes)) {
      eventLines.push(
        'BEGIN:VALARM',
        `TRIGGER:-PT${alarmMinutes}M`,
        'ACTION:DISPLAY',
        'DESCRIPTION:Match Reminder',
        'END:VALARM'
      );
    }

    eventLines.push('END:VEVENT');

    // Fold each line of the event and push to calendar array
    for (const line of eventLines) {
      ics.push(foldLine(line));
    }
  }

  ics.push('END:VCALENDAR');
  
  // Connect lines with CRLF as required by RFC 5545
  return ics.join('\r\n') + '\r\n';
}

// 5. Astro GET Handler
export async function GET(context: APIContext) {
  const { url } = context;
  const teamsParam = url.searchParams.get('teams');
  const stadiumsParam = url.searchParams.get('stadiums');
  const alarmParam = url.searchParams.get('alarm');

  const selectedTeams = teamsParam ? teamsParam.split(',').filter(Boolean) : [];
  const selectedStadiums = stadiumsParam ? stadiumsParam.split(',').filter(Boolean) : [];
  const alarmMinutes = alarmParam ? Number(alarmParam) : undefined;

  let filtered = schedule;

  if (selectedTeams.length > 0) {
    filtered = filtered.filter(
      m => selectedTeams.includes(m.homeTeam) || selectedTeams.includes(m.awayTeam)
    );
  }

  if (selectedStadiums.length > 0) {
    filtered = filtered.filter(m => selectedStadiums.includes(m.stadium));
  }

  const icsContent = generateIcsContent(filtered, alarmMinutes);

  return new Response(icsContent, {
    status: 200,
    headers: {
      'Content-Type': 'text/calendar; charset=utf-8',
      'Content-Disposition': 'attachment; filename="world-cup-2026.ics"',
      'Cache-Control': 'public, max-age=3600'
    }
  });
}
