import type { Tool } from './types';

export const CHARTS_TOOLS: Tool[] = [
  { slug: 'bar-chart-generator', category: 'charts', icon: 'bar-chart-3', component: 'BarChartGenerator', popular: true },
  { slug: 'line-chart-generator', category: 'charts', icon: 'trending-up', component: 'LineChartGenerator', popular: true },
  { slug: 'pie-chart-generator', category: 'charts', icon: 'pie-chart', component: 'PieChartGenerator', popular: true },
  { slug: 'radar-chart-generator', category: 'charts', icon: 'radar', component: 'RadarChartGenerator' },
  { slug: 'scatter-chart-generator', category: 'charts', icon: 'scatter-chart', component: 'ScatterChartGenerator', popular: true },
  { slug: 'area-chart-generator', category: 'charts', icon: 'area-chart', component: 'AreaChartGenerator' },
  { slug: 'funnel-chart-generator', category: 'charts', icon: 'filter', component: 'FunnelChartGenerator', popular: true },
  { slug: 'gauge-chart-generator', category: 'charts', icon: 'gauge', component: 'GaugeChartGenerator', popular: true },
  { slug: 'heatmap-chart-generator', category: 'charts', icon: 'grid-3x3', component: 'HeatmapChartGenerator', popular: true },
  { slug: 'treemap-chart-generator', category: 'charts', icon: 'layout-grid', component: 'TreemapChartGenerator' },
  { slug: 'doughnut-chart-generator', category: 'charts', icon: 'circle-dot', component: 'DoughnutChartGenerator' },
  { slug: 'sankey-chart-generator', category: 'charts', icon: 'git-branch', component: 'SankeyChartGenerator' },
  { slug: 'sunburst-chart-generator', category: 'charts', icon: 'sun', component: 'SunburstChartGenerator' },
  { slug: 'candlestick-chart-generator', category: 'charts', icon: 'candlestick-chart', component: 'CandlestickChartGenerator', popular: true },
  { slug: 'boxplot-chart-generator', category: 'charts', icon: 'box-select', component: 'BoxplotChartGenerator' },
  { slug: 'wordcloud-generator', category: 'charts', icon: 'bar-chart-3', component: 'WordCloudGenerator', popular: true },
  { slug: 'graph-chart-generator', category: 'charts', icon: 'network', component: 'GraphChartGenerator', popular: true },
  { slug: 'calendar-heatmap-generator', category: 'charts', icon: 'calendar-days', component: 'CalendarHeatmapGenerator' },
  { slug: 'polar-bar-chart-generator', category: 'charts', icon: 'circle', component: 'PolarBarChartGenerator' },
  { slug: 'parallel-chart-generator', category: 'charts', icon: 'align-horizontal-justify-center', component: 'ParallelChartGenerator' },
  { slug: 'bubble-chart-generator', category: 'charts', icon: 'circle-dot', component: 'BubbleChartGenerator' },
  { slug: 'tree-chart-generator', category: 'charts', icon: 'git-fork', component: 'TreeChartGenerator', popular: true },
  { slug: 'theme-river-generator', category: 'charts', icon: 'waves', component: 'ThemeRiverGenerator' },
  { slug: 'gantt-chart-generator', category: 'charts', icon: 'gantt-chart', component: 'GanttChartGenerator', popular: true },
  { slug: 'venn-diagram-generator', category: 'charts', icon: 'circle', component: 'VennDiagramGenerator', popular: true },
  { slug: 'timeline-chart-generator', category: 'charts', icon: 'clock', component: 'TimelineChartGenerator', popular: true },
  { slug: 'nightingale-rose-chart-generator', category: 'charts', icon: 'flower-2', component: 'NightingaleRoseChartGenerator' },
  { slug: 'grouped-bar-chart-generator', category: 'charts', icon: 'bar-chart-3', component: 'GroupedBarChartGenerator' },
  { slug: 'stacked-bar-chart-generator', category: 'charts', icon: 'bar-chart-4', component: 'StackedBarChartGenerator' },
  { slug: 'grouped-line-chart-generator', category: 'charts', icon: 'trending-up', component: 'GroupedLineChartGenerator' },
  { slug: 'step-line-chart-generator', category: 'charts', icon: 'trending-up', component: 'StepLineChartGenerator' },
  { slug: 'waterfall-chart-generator', category: 'charts', icon: 'bar-chart-2', component: 'WaterfallChartGenerator' },
  { slug: 'stacked-area-chart-generator', category: 'charts', icon: 'area-chart', component: 'StackedAreaChartGenerator' },
  { slug: 'positive-negative-bar-chart-generator', category: 'charts', icon: 'bar-chart-horizontal', component: 'PositiveNegativeBarChartGenerator' },
  { slug: 'percentage-stacked-bar-chart-generator', category: 'charts', icon: 'percent', component: 'PercentageStackedBarChartGenerator' },
  { slug: 'mixed-chart-generator', category: 'charts', icon: 'combine', component: 'MixedChartGenerator' },
  { slug: 'ring-progress-chart-generator', category: 'charts', icon: 'loader', component: 'RingProgressChartGenerator' },
  { slug: 'liquid-fill-chart-generator', category: 'charts', icon: 'droplets', component: 'LiquidFillChartGenerator' },
  { slug: 'multi-ring-chart-generator', category: 'charts', icon: 'target', component: 'MultiRingChartGenerator' },
  { slug: 'half-doughnut-chart-generator', category: 'charts', icon: 'semicircle', component: 'HalfDoughnutChartGenerator', popular: true },
  { slug: 'nested-pie-chart-generator', category: 'charts', icon: 'pie-chart', component: 'NestedPieChartGenerator', popular: true },
  { slug: 'pictorial-bar-chart-generator', category: 'charts', icon: 'bar-chart-horizontal', component: 'PictorialBarChartGenerator' },
];
