import type { Tool } from './types';

export const CONVERTERS_TOOLS: Tool[] = [
  { slug: 'color-converter', category: 'converters', icon: 'pipette', component: 'ColorConverter', popular: true },
  { slug: 'timestamp-converter', category: 'converters', icon: 'clock', component: 'TimestampConverter', popular: true },
  { slug: 'json-to-csv', category: 'converters', icon: 'table-2', component: 'JsonToCsv', popular: true },
  { slug: 'unit-converter', category: 'converters', icon: 'scale', component: 'UnitConverter', popular: true },
  { slug: 'yaml-json', category: 'converters', icon: 'file-json', component: 'YamlJson' },
  { slug: 'date-calculator', category: 'converters', icon: 'calendar', component: 'DateCalculator' },
  { slug: 'color-blender', category: 'converters', icon: 'blend', component: 'ColorBlender' },
  { slug: 'json-to-typescript', category: 'converters', icon: 'file-type', component: 'JsonToTypescript', popular: true },
  { slug: 'markdown-to-html', category: 'converters', icon: 'code', component: 'MarkdownToHtml', popular: true },
  { slug: 'epoch-converter', category: 'converters', icon: 'timer', component: 'EpochConverter' },
  { slug: 'css-unit-converter', category: 'converters', icon: 'ruler', component: 'CssUnitConverter' },
  { slug: 'json-to-yaml', category: 'converters', icon: 'file-json-2', component: 'JsonToYaml', popular: true },
  { slug: 'json-to-go', category: 'converters', icon: 'arrow-left-right', component: 'JsonToGo' },
  { slug: 'html-to-jsx', category: 'converters', icon: 'arrow-left-right', component: 'HtmlToJsx' },
  { slug: 'json-to-xml', category: 'converters', icon: 'arrow-left-right', component: 'JsonToXml' },
  { slug: 'csv-to-json', category: 'converters', icon: 'arrow-left-right', component: 'CsvToJson' },
  { slug: 'number-formatter', category: 'converters', icon: 'arrow-left-right', component: 'NumberFormatter' },
  { slug: 'json-to-sql', category: 'converters', icon: 'arrow-left-right', component: 'JsonToSql' },
  { slug: 'toml-json', category: 'converters', icon: 'arrow-left-right', component: 'TomlJson' },
  { slug: 'json-to-java', category: 'converters', icon: 'arrow-left-right', component: 'JsonToJava' },
  { slug: 'json-to-python', category: 'converters', icon: 'arrow-left-right', component: 'JsonToPython' },
  { slug: 'json-to-kotlin', category: 'converters', icon: 'arrow-left-right', component: 'JsonToKotlin' },
  { slug: 'timezone-converter', category: 'converters', icon: 'arrow-left-right', component: 'TimezoneConverter', popular: true },
  { slug: 'json-to-graphql', category: 'converters', icon: 'arrow-left-right', component: 'JsonToGraphql' },
  { slug: 'sql-to-mongo', category: 'converters', icon: 'arrow-left-right', component: 'SqlToMongo' },
  { slug: 'json-to-csharp', category: 'converters', icon: 'arrow-left-right', component: 'JsonToCsharp' },
  { slug: 'json-to-rust', category: 'converters', icon: 'arrow-left-right', component: 'JsonToRust' },
  { slug: 'json-to-swift', category: 'converters', icon: 'arrow-left-right', component: 'JsonToSwift' },
  { slug: 'html-to-markdown', category: 'converters', icon: 'arrow-left-right', component: 'HtmlToMarkdown' },
  { slug: 'xml-to-json', category: 'converters', icon: 'arrow-left-right', component: 'XmlToJson' },
  { slug: 'json-to-php', category: 'converters', icon: 'arrow-left-right', component: 'JsonToPhp' },
  { slug: 'json-to-tsv', category: 'converters', icon: 'arrow-left-right', component: 'JsonToTsv' },
  { slug: 'csv-viewer', category: 'converters', icon: 'arrow-left-right', component: 'CsvViewer' },
  { slug: 'file-size-calculator', category: 'converters', icon: 'arrow-left-right', component: 'FileSizeCalculator' },
  { slug: 'color-name-finder', category: 'converters', icon: 'arrow-left-right', component: 'ColorNameFinder' },
  { slug: 'json-to-dart', category: 'converters', icon: 'arrow-left-right', component: 'JsonToDart' },
  { slug: 'sql-to-json', category: 'converters', icon: 'arrow-left-right', component: 'SqlToJson' },
  { slug: 'time-calculator', category: 'converters', icon: 'arrow-left-right', component: 'TimeCalculator' },
  { slug: 'batch-timestamp-converter', category: 'converters', icon: 'arrow-left-right', component: 'BatchTimestampConverter' },
  { slug: 'shoe-size-converter', category: 'converters', icon: 'arrow-left-right', component: 'ShoeSizeConverter' },
  { slug: 'ring-size-calculator', category: 'converters', icon: 'arrow-left-right', component: 'RingSizeCalculator' },
  { slug: 'bra-size-calculator', category: 'converters', icon: 'arrow-left-right', component: 'BraSizeCalculator' },
  { slug: 'number-system-converter', category: 'converters', icon: 'arrow-left-right', component: 'NumberSystemConverter' },
  { slug: 'metric-imperial-converter', category: 'converters', icon: 'arrow-left-right', component: 'MetricImperialConverter' },
  { slug: 'roman-numeral-converter', category: 'converters', icon: 'arrow-left-right', component: 'RomanNumeralConverter' },
  { slug: 'text-to-pdf', category: 'converters', icon: 'arrow-left-right', component: 'TextToPdf' },
  { slug: 'json-to-proto', category: 'converters', icon: 'arrow-left-right', component: 'JsonToProto' },
  { slug: 'html-to-pdf', category: 'converters', icon: 'arrow-left-right', component: 'HtmlToPdf' },
  { slug: 'json-to-table', category: 'converters', icon: 'arrow-left-right', component: 'JsonToTable' },
  { slug: 'css-to-tailwind', category: 'converters', icon: 'arrow-left-right', component: 'CssToTailwind' },
  { slug: 'tailwind-to-css', category: 'converters', icon: 'arrow-left-right', component: 'TailwindToCss' },
  { slug: 'json-to-zod', category: 'converters', icon: 'arrow-left-right', component: 'JsonToZod' },
  { slug: 'typescript-to-json', category: 'converters', icon: 'arrow-left-right', component: 'TypescriptToJson' },
  { slug: 'markdown-to-slides', category: 'converters', icon: 'arrow-left-right', component: 'MarkdownToSlides' },
  { slug: 'ical-parser', category: 'converters', icon: 'arrow-left-right', component: 'IcalParser' },
  { slug: 'vcard-parser', category: 'converters', icon: 'arrow-left-right', component: 'VcardParser' },
  { slug: 'json-to-protobuf-converter', category: 'converters', icon: 'arrow-left-right', component: 'JsonToProtobufConverter' },
  { slug: 'markdown-to-html-converter', category: 'converters', icon: 'arrow-left-right', component: 'MarkdownToHtmlConverter' },
  { slug: 'csv-to-vcard-converter', category: 'converters', icon: 'arrow-left-right', component: 'PopularUtilityTool', popular: true },
  { slug: 'vcard-to-csv-converter', category: 'converters', icon: 'arrow-left-right', component: 'PopularUtilityTool', popular: true },
];
