import type { Tool } from './types';

export const DEVELOPMENT_TOOLS: Tool[] = [
  { slug: 'regex-tester', category: 'development', icon: 'search', component: 'RegexTester', popular: true },
  { slug: 'json-path-tester', category: 'development', icon: 'route', component: 'JsonPathTester' },
  { slug: 'code-minifier', category: 'development', icon: 'minimize-2', component: 'CodeMinifier', popular: true },
  { slug: 'sql-formatter', category: 'development', icon: 'database', component: 'SqlFormatter', popular: true },
  { slug: 'color-picker', category: 'development', icon: 'crosshair', component: 'ColorPicker', popular: true },
  { slug: 'css-beautifier', category: 'development', icon: 'paintbrush', component: 'CssBeautifier' },
  { slug: 'js-beautifier', category: 'development', icon: 'file-code', component: 'JsBeautifier' },
  { slug: 'html-preview', category: 'development', icon: 'eye', component: 'HtmlPreview', popular: true },
  { slug: 'json-schema-validator', category: 'development', icon: 'check-circle', component: 'JsonSchemaValidator', popular: true },
  { slug: 'regex-patterns', category: 'development', icon: 'book-open', component: 'RegexPatterns' },
  { slug: 'html-minifier', category: 'development', icon: 'minimize-2', component: 'HtmlMinifier' },
  { slug: 'json-diff', category: 'development', icon: 'git-compare', component: 'JsonDiff', popular: true },
  { slug: 'gitignore-generator', category: 'development', icon: 'file-x', component: 'GitignoreGenerator', popular: true },
  { slug: 'docker-compose-generator', category: 'development', icon: 'box', component: 'DockerComposeGenerator' },
  { slug: 'package-json-generator', category: 'development', icon: 'package', component: 'PackageJsonGenerator' },
  { slug: 'color-contrast-checker', category: 'development', icon: 'contrast', component: 'ColorContrastChecker' },
  { slug: 'opengraph-preview', category: 'development', icon: 'share-2', component: 'OpenGraphPreview' },
  { slug: 'cron-explainer', category: 'development', icon: 'calendar-search', component: 'CronExplainer' },
  { slug: 'css-minifier', category: 'development', icon: 'file-digit', component: 'CssMinifier' },
  { slug: 'js-minifier', category: 'development', icon: 'zap', component: 'JsMinifier' },
  { slug: 'regex-generator', category: 'development', icon: 'wand-2', component: 'RegexGenerator' },
  { slug: 'uuid-validator', category: 'development', icon: 'check-square', component: 'UuidValidator' },
  { slug: 'json-path-finder', category: 'development', icon: 'compass', component: 'JsonPathFinder' },
  { slug: 'htaccess-generator', category: 'development', icon: 'settings-2', component: 'HtaccessGenerator' },
  { slug: 'nginx-config-generator', category: 'development', icon: 'server-cog', component: 'NginxConfigGenerator' },
  { slug: 'curl-converter', category: 'development', icon: 'terminal', component: 'CurlConverter' },
  { slug: 'mime-type-lookup', category: 'development', icon: 'file-search-2', component: 'MimeTypeLookup' },
  { slug: 'http-status-codes', category: 'development', icon: 'server', component: 'HttpStatusCodes' },
  { slug: 'sql-generator', category: 'development', icon: 'database-plus', component: 'SqlGenerator' },
  { slug: 'htaccess-to-nginx', category: 'development', icon: 'repeat', component: 'HtaccessToNginx' },
  { slug: 'css-variables-generator', category: 'development', icon: 'variable', component: 'CssVariablesGenerator' },
  { slug: 'regex-escape', category: 'development', icon: 'lock', component: 'RegexEscape' },
  { slug: 'crc32-calculator', category: 'development', icon: 'hash', component: 'Crc32Calculator' },
  { slug: 'env-parser', category: 'development', icon: 'binary', component: 'EnvParser' },
  { slug: 'json-schema-generator', category: 'development', icon: 'braces', component: 'JsonSchemaGenerator' },
  { slug: 'regex-visualizer', category: 'development', icon: 'eye', component: 'RegexVisualizer' },
  { slug: 'crontab-calendar', category: 'development', icon: 'calendar-days', component: 'CrontabCalendar' },
  { slug: 'screen-resolution-tester', category: 'development', icon: 'monitor', component: 'ScreenResolutionTester' },
  { slug: 'keyboard-tester', category: 'development', icon: 'keyboard', component: 'KeyboardTester' },
  { slug: 'graphql-formatter', category: 'development', icon: 'code-2', component: 'GraphqlFormatter' },
  { slug: 'code-screenshot-generator', category: 'development', icon: 'code-2', component: 'CodeScreenshotGenerator' },
  { slug: 'color-blindness-simulator', category: 'development', icon: 'code-2', component: 'ColorBlindnessSimulator' },
  { slug: 'yaml-validator', category: 'development', icon: 'code-2', component: 'YamlValidator' },
  { slug: 'xml-validator', category: 'development', icon: 'code-2', component: 'XmlValidator' },
  { slug: 'api-tester', category: 'development', icon: 'code-2', component: 'ApiTester' },
  { slug: 'dockerfile-generator', category: 'development', icon: 'code-2', component: 'DockerfileGenerator' },
  { slug: 'eslint-config-generator', category: 'development', icon: 'code-2', component: 'EslintConfigGenerator' },
  { slug: 'prettier-config-generator', category: 'development', icon: 'code-2', component: 'PrettierConfigGenerator' },
  { slug: 'tsconfig-generator', category: 'development', icon: 'code-2', component: 'TsconfigGenerator' },
  { slug: 'editorconfig-generator', category: 'development', icon: 'code-2', component: 'EditorconfigGenerator' },
  { slug: 'commit-message-generator', category: 'development', icon: 'code-2', component: 'CommitMessageGenerator' },
  { slug: 'typescript-playground', category: 'development', icon: 'code-2', component: 'TypescriptPlayground' },
  { slug: 'python-formatter', category: 'development', icon: 'code-2', component: 'PythonFormatter' },
  { slug: 'go-formatter', category: 'development', icon: 'code-2', component: 'GoFormatter' },
  { slug: 'rust-formatter', category: 'development', icon: 'code-2', component: 'RustFormatter' },
  { slug: 'yaml-formatter', category: 'development', icon: 'code-2', component: 'YamlFormatter' },
  { slug: 'curl-to-code-generator', category: 'development', icon: 'terminal', component: 'CurlToCodeGenerator' },
  { slug: 'request-header-builder', category: 'development', icon: 'list-plus', component: 'RequestHeaderBuilder' },
  { slug: 'webhook-tester', category: 'development', icon: 'webhook', component: 'WebhookTester' },
  { slug: 'websocket-tester', category: 'development', icon: 'radio', component: 'WebSocketTester', popular: true },
  { slug: 'api-response-formatter', category: 'development', icon: 'braces', component: 'ApiResponseFormatter' },
  { slug: 'sql-to-mongodb-converter', category: 'development', icon: 'database-zap', component: 'SqlToMongodbConverter' },
  { slug: 'regex-to-code-generator', category: 'development', icon: 'wand-2', component: 'RegexToCodeGenerator' },
  { slug: 'swagger-to-code-generator', category: 'development', icon: 'file-text', component: 'SwaggerToCodeGenerator' },
  { slug: 'database-migration-generator', category: 'development', icon: 'database-backup', component: 'DatabaseMigrationGenerator' },
  { slug: 'environment-variables-generator', category: 'development', icon: 'binary', component: 'EnvironmentVariablesGenerator' },
  { slug: 'docker-compose-generator-advanced', category: 'development', icon: 'code-2', component: 'DockerComposeGeneratorAdvanced' },
  { slug: 'kubernetes-manifest-generator', category: 'development', icon: 'ship', component: 'KubernetesManifestGenerator' },
  { slug: 'code-complexity-analyzer', category: 'development', icon: 'gauge', component: 'CodeComplexityAnalyzer' },
  { slug: 'performance-profiler', category: 'development', icon: 'timer', component: 'PerformanceProfiler' },
  { slug: 'memory-leak-detector', category: 'development', icon: 'activity', component: 'MemoryLeakDetector' },
  { slug: 'code-duplication-finder', category: 'development', icon: 'copy', component: 'CodeDuplicationFinder' },
  { slug: 'unused-imports-finder', category: 'development', icon: 'code-2', component: 'UnusedImportsFinder' },
  { slug: 'dead-code-analyzer', category: 'development', icon: 'code-2', component: 'DeadCodeAnalyzer' },
  { slug: 'sql-query-optimizer', category: 'development', icon: 'database-zap', component: 'SqlQueryOptimizer' },
  { slug: 'database-schema-visualizer', category: 'development', icon: 'layout', component: 'DatabaseSchemaVisualizer' },
  { slug: 'query-execution-planner', category: 'development', icon: 'code-2', component: 'QueryExecutionPlanner' },
  { slug: 'database-backup-scheduler', category: 'development', icon: 'code-2', component: 'DatabaseBackupScheduler' },
  { slug: 'git-commit-message-generator', category: 'development', icon: 'git-commit', component: 'GitCommitMessageGenerator' },
  { slug: 'git-branch-naming-validator', category: 'development', icon: 'code-2', component: 'GitBranchNamingValidator' },
  { slug: 'merge-conflict-resolver', category: 'development', icon: 'code-2', component: 'MergeConflictResolver' },
  { slug: 'git-history-visualizer', category: 'development', icon: 'history', component: 'GitHistoryVisualizer' },
  { slug: 'git-tag-manager', category: 'development', icon: 'code-2', component: 'GitTagManager' },
  { slug: 'docker-run-to-docker-compose-converter', category: 'development', icon: 'code-2', component: 'DockerRunToCompose', popular: true },
  { slug: 'llms-txt-generator', category: 'development', icon: 'file-text', component: 'LlmsTxtGenerator', popular: true },
  { slug: 'ai-token-calculator', category: 'development', icon: 'calculator', component: 'AiTokenCalculator', popular: true },
  { slug: 'json-to-prompt', category: 'development', icon: 'braces', component: 'JsonToPrompt', popular: true },
  { slug: 'rag-chunk-size-calculator', category: 'development', icon: 'database', component: 'RagChunkSizeCalculator', popular: true },
  { slug: 'llms-txt-validator', category: 'development', icon: 'file-text', component: 'PopularUtilityTool', popular: true },
  { slug: 'mcp-json-validator', category: 'development', icon: 'braces', component: 'PopularUtilityTool', popular: true },
  { slug: 'json-repair', category: 'development', icon: 'wrench', component: 'PopularUtilityTool', popular: true },
  { slug: 'jsonl-validator', category: 'development', icon: 'file-json', component: 'PopularUtilityTool', popular: true },
  { slug: 'har-file-viewer', category: 'development', icon: 'activity', component: 'HarFileViewer', popular: true },
];
