import type { Tool } from './types';

export const ENCODING_TOOLS: Tool[] = [
  { slug: 'json-formatter', category: 'encoding', icon: 'braces', component: 'JsonFormatter', popular: true },
  { slug: 'base64', category: 'encoding', icon: 'lock', component: 'Base64', popular: true },
  { slug: 'html-encoder', category: 'encoding', icon: 'file-code', component: 'HtmlEncoder', popular: true },
  { slug: 'jwt-decoder', category: 'encoding', icon: 'key-round', component: 'JwtDecoder', popular: true },
  { slug: 'xml-formatter', category: 'encoding', icon: 'file-code-2', component: 'XmlFormatter', popular: true },
  { slug: 'unicode-converter', category: 'encoding', icon: 'languages', component: 'UnicodeConverter', popular: true },
  { slug: 'morse-code', category: 'encoding', icon: 'radio', component: 'MorseCode' },
  { slug: 'string-escape', category: 'encoding', icon: 'shield', component: 'StringEscape' },
  { slug: 'json-sorter', category: 'encoding', icon: 'arrow-up-down', component: 'JsonSorter' },
  { slug: 'text-to-binary', category: 'encoding', icon: 'binary', component: 'TextToBinary' },
  { slug: 'base32', category: 'encoding', icon: 'hash', component: 'Base32' },
  { slug: 'hex-editor', category: 'encoding', icon: 'binary', component: 'HexEditor' },
  { slug: 'data-uri', category: 'encoding', icon: 'binary', component: 'DataUri' },
  { slug: 'html-entity', category: 'encoding', icon: 'binary', component: 'HtmlEntityConverter' },
  { slug: 'json-minifier', category: 'encoding', icon: 'binary', component: 'JsonMinifier' },
  { slug: 'base58', category: 'encoding', icon: 'hash', component: 'Base58' },
  { slug: 'json-flattener', category: 'encoding', icon: 'binary', component: 'JsonFlattener' },
  { slug: 'base85', category: 'encoding', icon: 'hash', component: 'Base85' },
  { slug: 'json-viewer', category: 'encoding', icon: 'binary', component: 'JsonViewer' },
  { slug: 'encoding-detector', category: 'encoding', icon: 'binary', component: 'EncodingDetector' },
  { slug: 'json-escape', category: 'encoding', icon: 'binary', component: 'JsonEscape' },
  { slug: 'hex-base64-converter', category: 'encoding', icon: 'binary', component: 'HexBase64Converter' },
  { slug: 'pdf-to-base64', category: 'encoding', icon: 'binary', component: 'PdfToBase64' },
  { slug: 'audio-to-base64', category: 'encoding', icon: 'binary', component: 'AudioToBase64' },
  { slug: 'video-to-base64', category: 'encoding', icon: 'binary', component: 'VideoToBase64' },
  { slug: 'ascii-table', category: 'encoding', icon: 'binary', component: 'AsciiTable' },
  { slug: 'text-to-hex', category: 'encoding', icon: 'binary', component: 'TextToHex' },
  { slug: 'json-merger', category: 'encoding', icon: 'binary', component: 'JsonMerger' },
  { slug: 'morse-code-player', category: 'encoding', icon: 'binary', component: 'MorseCodePlayer' },
  { slug: 'binary-to-text', category: 'encoding', icon: 'binary', component: 'BinaryToText' },
  { slug: 'rot13-encoder', category: 'encoding', icon: 'binary', component: 'Rot13Encoder' },
  { slug: 'caesar-cipher', category: 'encoding', icon: 'binary', component: 'CaesarCipher' },
  { slug: 'vigenere-cipher', category: 'encoding', icon: 'binary', component: 'VigenereCipher' },
];
