import type { Tool } from './types';

export const GENERATORS_TOOLS: Tool[] = [
  { slug: 'uuid-generator', category: 'generators', icon: 'fingerprint', component: 'UuidGenerator', popular: true },
  { slug: 'lorem-ipsum', category: 'generators', icon: 'text', component: 'LoremIpsum', popular: true },
  { slug: 'cron-generator', category: 'generators', icon: 'clock', component: 'CronGenerator' },
  { slug: 'gradient-generator', category: 'generators', icon: 'palette', component: 'GradientGenerator', popular: true },
  { slug: 'random-generator', category: 'generators', icon: 'dice-5', component: 'RandomGenerator' },
  { slug: 'html-table-generator', category: 'generators', icon: 'table', component: 'HtmlTableGenerator' },
  { slug: 'color-palette', category: 'generators', icon: 'paintbrush', component: 'ColorPalette', popular: true },
  { slug: 'markdown-table-generator', category: 'generators', icon: 'zap', component: 'MarkdownTableGenerator' },
  { slug: 'meta-tag-generator', category: 'generators', icon: 'zap', component: 'MetaTagGenerator' },
  { slug: 'utm-builder', category: 'generators', icon: 'link', component: 'UtmBuilder', popular: true },
  { slug: 'meta-description-generator', category: 'generators', icon: 'file-text', component: 'MetaDescriptionGenerator', popular: true },
  { slug: 'wifi-qr-code-generator', category: 'generators', icon: 'qr-code', component: 'WifiQrCodeGenerator', popular: true },
  { slug: 'robots-txt-generator', category: 'generators', icon: 'zap', component: 'RobotsTxtGenerator' },
  { slug: 'css-grid-generator', category: 'generators', icon: 'grid-3x3', component: 'CssGridGenerator' },
  { slug: 'css-flexbox-generator', category: 'generators', icon: 'layout-grid', component: 'CssFlexboxGenerator' },
  { slug: 'box-shadow-generator', category: 'generators', icon: 'copy', component: 'BoxShadowGenerator' },
  { slug: 'border-radius-generator', category: 'generators', icon: 'circle', component: 'BorderRadiusGenerator' },
  { slug: 'color-shades-generator', category: 'generators', icon: 'zap', component: 'ColorShadesGenerator' },
  { slug: 'css-gradient-text', category: 'generators', icon: 'type', component: 'CssGradientText' },
  { slug: 'sitemap-generator', category: 'generators', icon: 'zap', component: 'SitemapGenerator' },
  { slug: 'css-filter-generator', category: 'generators', icon: 'zap', component: 'CssFilterGenerator' },
  { slug: 'css-clip-path-generator', category: 'generators', icon: 'zap', component: 'CssClipPathGenerator' },
  { slug: 'css-animation-generator', category: 'generators', icon: 'zap', component: 'CssAnimationGenerator' },
  { slug: 'privacy-policy-generator', category: 'generators', icon: 'zap', component: 'PrivacyPolicyGenerator' },
  { slug: 'terms-generator', category: 'generators', icon: 'zap', component: 'TermsGenerator' },
  { slug: 'cookie-policy-generator', category: 'generators', icon: 'zap', component: 'CookiePolicyGenerator' },
  { slug: 'open-graph-generator', category: 'generators', icon: 'zap', component: 'OpenGraphGenerator' },
  { slug: 'twitter-card-generator', category: 'generators', icon: 'zap', component: 'TwitterCardGenerator' },
  { slug: 'fake-data-generator', category: 'generators', icon: 'zap', component: 'FakeDataGenerator' },
  { slug: 'chinese-lorem-ipsum', category: 'generators', icon: 'zap', component: 'ChineseLoremIpsum' },
  { slug: 'gdpr-consent-generator', category: 'generators', icon: 'zap', component: 'GdprConsentGenerator' },
  { slug: 'random-color-generator', category: 'generators', icon: 'zap', component: 'RandomColorGenerator' },
  { slug: 'fake-name-generator', category: 'generators', icon: 'zap', component: 'FakeNameGenerator' },
  { slug: 'invisible-character-generator', category: 'generators', icon: 'zap', component: 'InvisibleCharacterGenerator' },
  { slug: 'json-to-form', category: 'generators', icon: 'zap', component: 'JsonToForm' },
  { slug: 'github-readme-generator', category: 'generators', icon: 'zap', component: 'GithubReadmeGenerator' },
  { slug: 'changelog-generator', category: 'generators', icon: 'zap', component: 'ChangelogGenerator' },
  { slug: 'license-generator', category: 'generators', icon: 'zap', component: 'LicenseGenerator' },
  { slug: 'hashtag-generator', category: 'generators', icon: 'zap', component: 'HashtagGenerator' },
  { slug: 'email-signature-generator', category: 'generators', icon: 'zap', component: 'EmailSignatureGenerator' },
  { slug: 'glassmorphism-generator', category: 'generators', icon: 'zap', component: 'GlassmorphismGenerator' },
  { slug: 'neumorphism-generator', category: 'generators', icon: 'zap', component: 'NeumorphismGenerator' },
  { slug: 'blob-generator', category: 'generators', icon: 'zap', component: 'BlobGenerator' },
  { slug: 'wave-generator', category: 'generators', icon: 'zap', component: 'WaveGenerator' },
  { slug: 'mesh-gradient-generator', category: 'generators', icon: 'zap', component: 'MeshGradientGenerator' },
  { slug: 'noise-texture-generator', category: 'generators', icon: 'zap', component: 'NoiseTextureGenerator' },
  { slug: 'text-shadow-generator', category: 'generators', icon: 'zap', component: 'TextShadowGenerator' },
  { slug: 'svg-pattern-generator', category: 'generators', icon: 'zap', component: 'SvgPatternGenerator' },
  { slug: 'css-triangle-generator', category: 'generators', icon: 'zap', component: 'CssTriangleGenerator' },
  { slug: 'aspect-ratio-box-generator', category: 'generators', icon: 'zap', component: 'AspectRatioBoxGenerator' },
  { slug: 'changelog-generator-advanced', category: 'generators', icon: 'zap', component: 'ChangelogGeneratorAdvanced' },
  { slug: 'document-outline-generator', category: 'generators', icon: 'zap', component: 'DocumentOutlineGenerator' },
  { slug: 'table-of-contents-generator', category: 'generators', icon: 'zap', component: 'TableOfContentsGenerator' },
  { slug: 'youtube-title-generator', category: 'generators', icon: 'text', component: 'YoutubeTitleGenerator', popular: true },
  { slug: 'email-subject-line-generator', category: 'generators', icon: 'text', component: 'EmailSubjectLineGenerator', popular: true },
  { slug: 'instagram-bio-generator', category: 'generators', icon: 'text', component: 'InstagramBioGenerator', popular: true },
  { slug: 'youtube-description-generator', category: 'generators', icon: 'text', component: 'YoutubeDescriptionGenerator', popular: true },
  { slug: 'midjourney-prompt-generator', category: 'generators', icon: 'wand-2', component: 'MidjourneyPromptGenerator', popular: true },
  { slug: 'stable-diffusion-prompt-generator', category: 'generators', icon: 'wand-2', component: 'StableDiffusionPromptGenerator', popular: true },
  { slug: 'youtube-tags-generator', category: 'generators', icon: 'hash', component: 'YoutubeTagsGenerator', popular: true },
  { slug: 'tiktok-hashtag-generator', category: 'generators', icon: 'hash', component: 'TiktokHashtagGenerator', popular: true },
  { slug: 'instagram-caption-generator', category: 'generators', icon: 'text', component: 'InstagramCaptionGenerator', popular: true },
  { slug: 'linkedin-post-generator', category: 'generators', icon: 'file-text', component: 'LinkedinPostGenerator', popular: true },
  { slug: 'blog-title-generator', category: 'generators', icon: 'text', component: 'BlogTitleGenerator', popular: true },
  { slug: 'product-description-generator', category: 'generators', icon: 'file-text', component: 'ProductDescriptionGenerator', popular: true },
  { slug: 'email-preview-text-generator', category: 'generators', icon: 'text', component: 'EmailPreviewTextGenerator', popular: true },
  { slug: 'faq-generator', category: 'generators', icon: 'file-text', component: 'FaqGenerator', popular: true },
  { slug: 'seo-title-generator', category: 'generators', icon: 'file-text', component: 'SeoTitleGenerator', popular: true },
  { slug: 'tweet-generator', category: 'generators', icon: 'text', component: 'TweetGenerator', popular: true },
];
