import type { Tool } from './types';

export const IMAGE_TOOLS: Tool[] = [
  { slug: 'qr-generator', category: 'image', icon: 'qr-code', component: 'QrGenerator', popular: true },
  { slug: 'image-to-base64', category: 'image', icon: 'image', component: 'ImageToBase64', popular: true },
  { slug: 'placeholder-image', category: 'image', icon: 'image-plus', component: 'PlaceholderImage' },
  { slug: 'svg-optimizer', category: 'image', icon: 'pen-tool', component: 'SvgOptimizer' },
  { slug: 'barcode-generator', category: 'image', icon: 'image', component: 'BarcodeGenerator' },
  { slug: 'image-compressor', category: 'image', icon: 'image', component: 'ImageCompressor', popular: true },
  { slug: 'image-converter', category: 'image', icon: 'image', component: 'ImageConverter', popular: true },
  { slug: 'favicon-generator', category: 'image', icon: 'image', component: 'FaviconGenerator', popular: true },
  { slug: 'image-cropper', category: 'image', icon: 'image', component: 'ImageCropper' },
  { slug: 'canvas-drawing', category: 'image', icon: 'image', component: 'CanvasDrawing' },
  { slug: 'image-resizer', category: 'image', icon: 'image', component: 'ImageResizer' },
  { slug: 'image-watermark', category: 'image', icon: 'image', component: 'ImageWatermark' },
  { slug: 'svg-to-image', category: 'image', icon: 'image', component: 'SvgToImage' },
  { slug: 'lorem-picsum', category: 'image', icon: 'image', component: 'LoremPicsum' },
  { slug: 'image-collage', category: 'image', icon: 'image', component: 'ImageCollage' },
  { slug: 'image-splitter', category: 'image', icon: 'image', component: 'ImageSplitter' },
  { slug: 'image-rounder', category: 'image', icon: 'image', component: 'ImageRounder' },
  { slug: 'image-border', category: 'image', icon: 'image', component: 'ImageBorder' },
  { slug: 'image-flip-rotate', category: 'image', icon: 'image', component: 'ImageFlipRotate' },
  { slug: 'image-adjustment', category: 'image', icon: 'image', component: 'ImageAdjustment' },
  { slug: 'image-frosted-glass', category: 'image', icon: 'image', component: 'ImageFrostedGlass' },
  { slug: 'image-to-ico', category: 'image', icon: 'image', component: 'ImageToIco' },
  { slug: 'gif-maker', category: 'image', icon: 'image', component: 'GifMaker' },
  { slug: 'gif-splitter', category: 'image', icon: 'image', component: 'GifSplitter' },
  { slug: 'gif-compressor', category: 'image', icon: 'image', component: 'GifCompressor' },
  { slug: 'image-to-webp', category: 'image', icon: 'image', component: 'ImageToWebp' },
  { slug: 'exif-viewer', category: 'image', icon: 'image', component: 'ExifViewer' },
  { slug: 'color-extractor', category: 'image', icon: 'image', component: 'ColorExtractor' },
  { slug: 'text-to-image', category: 'image', icon: 'image', component: 'TextToImage' },
  { slug: 'text-to-handwriting', category: 'image', icon: 'image', component: 'TextToHandwriting' },
  { slug: 'social-media-size-guide', category: 'image', icon: 'image', component: 'SocialMediaSizeGuide' },
  { slug: 'aspect-ratio-resizer', category: 'image', icon: 'image', component: 'AspectRatioResizer' },
  { slug: 'svg-to-png', category: 'image', icon: 'image', component: 'SvgToPng' },
  { slug: 'webp-to-png', category: 'image', icon: 'image', component: 'WebpToPng' },
  { slug: 'png-to-svg', category: 'image', icon: 'image', component: 'PngToSvg' },
  { slug: 'svg-editor', category: 'image', icon: 'image', component: 'SvgEditor' },
  { slug: 'pixel-density-calculator', category: 'image', icon: 'image', component: 'PixelDensityCalculator' },
  { slug: 'dpi-calculator', category: 'image', icon: 'image', component: 'DpiCalculator' },
  { slug: 'base64-image-converter', category: 'image', icon: 'image', component: 'Base64ImageConverter' },
];
