import type { Tool } from './types';

export const MATH_TOOLS: Tool[] = [
  { slug: 'number-base-converter', category: 'math', icon: 'calculator', component: 'NumberBaseConverter', popular: true },
  { slug: 'aspect-ratio', category: 'math', icon: 'ratio', component: 'AspectRatioCalculator' },
  { slug: 'chmod-calculator', category: 'math', icon: 'calculator', component: 'ChmodCalculator' },
  { slug: 'percentage-calculator', category: 'math', icon: 'calculator', component: 'PercentageCalculator', popular: true },
  { slug: 'statistics-calculator', category: 'math', icon: 'calculator', component: 'StatisticsCalculator' },
  { slug: 'scientific-calculator', category: 'math', icon: 'calculator', component: 'ScientificCalculator', popular: true },
  { slug: 'binary-to-decimal', category: 'math', icon: 'calculator', component: 'BinaryToDecimal' },
  { slug: 'octal-converter', category: 'math', icon: 'calculator', component: 'OctalConverter' },
  { slug: 'base-calculator', category: 'math', icon: 'calculator', component: 'BaseCalculator' },
  { slug: 'loan-calculator', category: 'math', icon: 'calculator', component: 'LoanCalculator', popular: true },
  { slug: 'bmi-calculator', category: 'math', icon: 'calculator', component: 'BmiCalculator', popular: true },
  { slug: 'age-calculator', category: 'math', icon: 'calculator', component: 'AgeCalculator' },
  { slug: 'tip-calculator', category: 'math', icon: 'calculator', component: 'TipCalculator' },
  { slug: 'discount-calculator', category: 'math', icon: 'calculator', component: 'DiscountCalculator' },
  { slug: 'compound-interest-calculator', category: 'math', icon: 'calculator', component: 'CompoundInterestCalculator' },
  { slug: 'binary-calculator', category: 'math', icon: 'calculator', component: 'BinaryCalculator' },
  { slug: 'hex-calculator', category: 'math', icon: 'calculator', component: 'HexCalculator' },
  { slug: 'aspect-ratio-calculator-enhanced', category: 'math', icon: 'calculator', component: 'AspectRatioCalculatorEnhanced' },
  { slug: 'gpa-calculator', category: 'math', icon: 'calculator', component: 'GpaCalculator' },
  { slug: 'concrete-calculator', category: 'math', icon: 'calculator', component: 'ConcreteCalculator' },
  { slug: 'paint-calculator', category: 'math', icon: 'calculator', component: 'PaintCalculator' },
  { slug: 'tile-calculator', category: 'math', icon: 'calculator', component: 'TileCalculator' },
  { slug: 'fraction-calculator', category: 'math', icon: 'calculator', component: 'FractionCalculator' },
  { slug: 'percentage-change-calculator', category: 'math', icon: 'calculator', component: 'PercentageChangeCalculator' },
  { slug: 'unit-price-calculator', category: 'math', icon: 'calculator', component: 'UnitPriceCalculator' },
  { slug: 'screen-time-calculator', category: 'math', icon: 'calculator', component: 'ScreenTimeCalculator' },
  { slug: 'typing-time-calculator', category: 'math', icon: 'calculator', component: 'TypingTimeCalculator' },
  { slug: 'download-time-calculator', category: 'math', icon: 'calculator', component: 'DownloadTimeCalculator' },
];
