import type { Tool } from './types';

export const NETWORK_TOOLS: Tool[] = [
  { slug: 'url-encoder', category: 'network', icon: 'link', component: 'UrlEncoder', popular: true },
  { slug: 'ip-lookup', category: 'network', icon: 'globe', component: 'IpLookup', popular: true },
  { slug: 'http-status', category: 'network', icon: 'server', component: 'HttpStatus' },
  { slug: 'url-parser', category: 'network', icon: 'globe', component: 'UrlParser' },
  { slug: 'user-agent-parser', category: 'network', icon: 'globe', component: 'UserAgentParser' },
  { slug: 'cidr-calculator', category: 'network', icon: 'globe', component: 'CidrCalculator', popular: true },
  { slug: 'http-header-parser', category: 'network', icon: 'globe', component: 'HttpHeaderParser' },
  { slug: 'url-shortener-preview', category: 'network', icon: 'globe', component: 'UrlShortenerPreview' },
  { slug: 'ip-address-generator', category: 'network', icon: 'globe', component: 'IpAddressGenerator' },
  { slug: 'dns-lookup', category: 'network', icon: 'globe', component: 'DnsLookup' },
  { slug: 'ssl-checker', category: 'network', icon: 'globe', component: 'SslChecker', popular: true },
  { slug: 'whois-lookup', category: 'network', icon: 'globe', component: 'WhoisLookup' },
  { slug: 'port-reference', category: 'network', icon: 'globe', component: 'PortScanner' },
  { slug: 'mac-address-generator', category: 'network', icon: 'globe', component: 'MacAddressGenerator' },
  { slug: 'ip-validator', category: 'network', icon: 'globe', component: 'IpValidator' },
  { slug: 'ip-subnet-calculator', category: 'network', icon: 'globe', component: 'IpSubnetCalculator' },
  { slug: 'subnet-calculator-enhanced', category: 'network', icon: 'globe', component: 'SubnetCalculatorEnhanced' },
  { slug: 'email-validator', category: 'network', icon: 'globe', component: 'EmailValidator' },
  { slug: 'cors-tester', category: 'network', icon: 'globe', component: 'CorsTester' },
  { slug: 'bandwidth-calculator', category: 'network', icon: 'globe', component: 'BandwidthCalculator' },
  { slug: 'data-transfer-calculator', category: 'network', icon: 'globe', component: 'DataTransferCalculator' },
  { slug: 'http-status-code-reference', category: 'network', icon: 'globe', component: 'HttpStatusCodeReference' },
  { slug: 'url-query-string-parser', category: 'network', icon: 'globe', component: 'UrlQueryStringParser' },
  { slug: 'database-connection-tester', category: 'network', icon: 'globe', component: 'DatabaseConnectionTester', popular: true },
  { slug: 'ip-geolocation', category: 'network', icon: 'globe', component: 'IpGeolocation', popular: true },
];
