import type { Tool } from './types';

export const OFFICE_TOOLS: Tool[] = [
  { slug: 'invoice-generator', category: 'office', icon: 'file-text', component: 'InvoiceGenerator' },
  { slug: 'resume-builder', category: 'office', icon: 'file-text', component: 'ResumeBuilder' },
  { slug: 'signature-pad', category: 'office', icon: 'file-text', component: 'SignaturePad' },
  { slug: 'pomodoro-timer', category: 'office', icon: 'file-text', component: 'PomodoroTimer' },
  { slug: 'meeting-notes', category: 'office', icon: 'file-text', component: 'MeetingNotes' },
  { slug: 'business-days-calculator', category: 'office', icon: 'file-text', component: 'BusinessDaysCalculator' },
  { slug: 'salary-calculator', category: 'office', icon: 'file-text', component: 'SalaryCalculator' },
  { slug: 'excel-to-json', category: 'office', icon: 'file-text', component: 'ExcelToJson' },
  { slug: 'json-to-excel', category: 'office', icon: 'file-text', component: 'JsonToExcel' },
  { slug: 'excel-viewer', category: 'office', icon: 'file-text', component: 'ExcelViewer' },
  { slug: 'excel-merger', category: 'office', icon: 'file-text', component: 'ExcelMerger' },
  { slug: 'pdf-to-image', category: 'office', icon: 'file-text', component: 'PdfToImage' },
  { slug: 'image-to-pdf', category: 'office', icon: 'file-text', component: 'ImageToPdf' },
  { slug: 'pdf-merger', category: 'office', icon: 'file-text', component: 'PdfMerger' },
  { slug: 'pdf-splitter', category: 'office', icon: 'file-text', component: 'PdfSplitter' },
  { slug: 'pdf-compressor', category: 'office', icon: 'file-text', component: 'PdfCompressor' },
  { slug: 'pdf-rotator', category: 'office', icon: 'file-text', component: 'PdfRotator' },
  { slug: 'world-clock', category: 'office', icon: 'file-text', component: 'WorldClock' },
  { slug: 'stopwatch', category: 'office', icon: 'file-text', component: 'Stopwatch' },
  { slug: 'countdown-timer', category: 'office', icon: 'file-text', component: 'CountdownTimer' },
  { slug: 'note-pad', category: 'office', icon: 'file-text', component: 'NotePad' },
  { slug: 'pdf-to-text', category: 'office', icon: 'file-text', component: 'PdfToText' },
  { slug: 'word-to-txt', category: 'office', icon: 'file-text', component: 'WordToTxt' },
  { slug: 'word-to-html', category: 'office', icon: 'file-text', component: 'WordToHtml' },
  { slug: 'excel-to-csv', category: 'office', icon: 'file-text', component: 'ExcelToCsv' },
  { slug: 'csv-to-excel', category: 'office', icon: 'file-text', component: 'CsvToExcel' },
  { slug: 'markdown-to-pdf', category: 'office', icon: 'file-text', component: 'MarkdownToPdf' },
  { slug: 'speech-timer', category: 'office', icon: 'file-text', component: 'SpeechTimer' },
  { slug: 'document-formatter', category: 'office', icon: 'file-text', component: 'DocumentFormatter' },
  { slug: 'citation-formatter', category: 'office', icon: 'file-text', component: 'CitationFormatter' },
  { slug: 'project-estimation-calculator', category: 'office', icon: 'file-text', component: 'ProjectEstimationCalculator' },
  { slug: 'sprint-velocity-calculator', category: 'office', icon: 'file-text', component: 'SprintVelocityCalculator' },
  { slug: 'resource-allocation-planner', category: 'office', icon: 'file-text', component: 'ResourceAllocationPlanner' },
  { slug: 'project-risk-analyzer', category: 'office', icon: 'file-text', component: 'ProjectRiskAnalyzer' },
  { slug: 'milestone-tracker', category: 'office', icon: 'file-text', component: 'MilestoneTracker' },
  { slug: 'team-capacity-planner', category: 'office', icon: 'file-text', component: 'TeamCapacityPlanner' },
  { slug: 'meeting-minutes-generator', category: 'office', icon: 'file-text', component: 'MeetingMinutesGenerator' },
  { slug: 'timezone-meeting-scheduler', category: 'office', icon: 'file-text', component: 'TimezoneMeetingScheduler' },
  { slug: 'meeting-agenda-builder', category: 'office', icon: 'file-text', component: 'MeetingAgendaBuilder' },
  { slug: 'calendar-availability-finder', category: 'office', icon: 'file-text', component: 'CalendarAvailabilityFinder' },
  { slug: 'meeting-room-finder', category: 'office', icon: 'file-text', component: 'MeetingRoomFinder' },
  { slug: 'screen-recorder', category: 'office', icon: 'file-text', component: 'ScreenRecorder', popular: true },
  { slug: 'cover-letter-generator', category: 'office', icon: 'file-text', component: 'PopularUtilityTool', popular: true },
  { slug: 'linkedin-headline-generator', category: 'office', icon: 'file-text', component: 'PopularUtilityTool', popular: true },
  { slug: 'linkedin-summary-generator', category: 'office', icon: 'file-text', component: 'PopularUtilityTool', popular: true },
];
