import type { Tool } from './types';

export const TEXT_TOOLS: Tool[] = [
  { slug: 'word-counter', category: 'text', icon: 'text-cursor-input', component: 'WordCounter', popular: true },
  { slug: 'case-converter', category: 'text', icon: 'a-large-small', component: 'CaseConverter', popular: true },
  { slug: 'markdown-preview', category: 'text', icon: 'book-open', component: 'MarkdownPreview', popular: true },
  { slug: 'diff-checker', category: 'text', icon: 'git-compare', component: 'DiffChecker', popular: true },
  { slug: 'text-to-slug', category: 'text', icon: 'minus', component: 'TextToSlug', popular: true },
  { slug: 'chinese-converter', category: 'text', icon: 'languages', component: 'ChineseConverter', popular: true },
  { slug: 'pinyin-converter', category: 'text', icon: 'languages', component: 'PinyinConverter' },
  { slug: 'text-reverser', category: 'text', icon: 'refresh-cw', component: 'TextReverser' },
  { slug: 'line-counter', category: 'text', icon: 'list-ordered', component: 'LineCounter' },
  { slug: 'text-deduplicator', category: 'text', icon: 'filter', component: 'TextDeduplicator' },
  { slug: 'byte-counter', category: 'text', icon: 'ruler', component: 'ByteCounter' },
  { slug: 'text-statistics', category: 'text', icon: 'bar-chart-2', component: 'TextStatistics', popular: true },
  { slug: 'text-compare', category: 'text', icon: 'type', component: 'TextCompare' },
  { slug: 'text-to-speech', category: 'text', icon: 'type', component: 'TextToSpeech' },
  { slug: 'text-wrapper', category: 'text', icon: 'type', component: 'TextWrapper' },
  { slug: 'text-sorter', category: 'text', icon: 'type', component: 'TextSorter' },
  { slug: 'text-extractor', category: 'text', icon: 'type', component: 'TextExtractor' },
  { slug: 'emoji-picker', category: 'text', icon: 'type', component: 'EmojiPicker' },
  { slug: 'text-to-ascii-art', category: 'text', icon: 'type', component: 'TextToAsciiArt' },
  { slug: 'text-diff-patch', category: 'text', icon: 'type', component: 'TextDiffPatch' },
  { slug: 'text-case-counter', category: 'text', icon: 'type', component: 'TextCaseCounter' },
  { slug: 'reading-time-calculator', category: 'text', icon: 'type', component: 'ReadingTimeCalculator' },
  { slug: 'text-cleaner', category: 'text', icon: 'type', component: 'TextCleaner' },
  { slug: 'list-randomizer', category: 'text', icon: 'type', component: 'ListRandomizer' },
  { slug: 'html-to-text', category: 'text', icon: 'type', component: 'HtmlToText' },
  { slug: 'text-to-nato', category: 'text', icon: 'type', component: 'TextToNato' },
  { slug: 'text-template', category: 'text', icon: 'type', component: 'TextTemplate' },
  { slug: 'char-frequency', category: 'text', icon: 'type', component: 'CharFrequency' },
  { slug: 'markdown-editor', category: 'text', icon: 'type', component: 'MarkdownEditor' },
  { slug: 'typing-speed-test', category: 'text', icon: 'type', component: 'TypingSpeedTest' },
  { slug: 'instagram-font-generator', category: 'text', icon: 'type', component: 'InstagramFontGenerator' },
  { slug: 'keyword-density-checker', category: 'text', icon: 'type', component: 'KeywordDensityChecker' },
  { slug: 'ai-prompt-generator', category: 'text', icon: 'sparkle', component: 'AiPromptGenerator', popular: true },
  { slug: 'ai-prompt-optimizer', category: 'text', icon: 'sparkle', component: 'AiPromptOptimizer', popular: true },
  { slug: 'ai-prompt-template-generator', category: 'text', icon: 'sparkle', component: 'AiPromptTemplateGenerator', popular: true },
  { slug: 'title-capitalization-tool', category: 'text', icon: 'type', component: 'TitleCapitalizationTool' },
  { slug: 'text-summarizer', category: 'text', icon: 'type', component: 'TextSummarizer' },
  { slug: 'paraphrase-tool', category: 'text', icon: 'type', component: 'ParaphraseTool' },
  { slug: 'phone-formatter', category: 'text', icon: 'type', component: 'PhoneFormatter' },
  { slug: 'flip-text', category: 'text', icon: 'type', component: 'FlipText' },
  { slug: 'strikethrough-text', category: 'text', icon: 'type', component: 'StrikethroughText' },
  { slug: 'small-text-generator', category: 'text', icon: 'type', component: 'SmallTextGenerator' },
  { slug: 'anagram-solver', category: 'text', icon: 'type', component: 'AnagramSolver' },
  { slug: 'word-unscrambler', category: 'text', icon: 'type', component: 'WordUnscrambler' },
  { slug: 'bionic-reading-converter', category: 'text', icon: 'type', component: 'BionicReadingConverter' },
  { slug: 'palindrome-checker', category: 'text', icon: 'type', component: 'PalindromeChecker' },
  { slug: 'character-map', category: 'text', icon: 'type', component: 'CharacterMap' },
  { slug: 'text-repeater', category: 'text', icon: 'type', component: 'TextRepeater' },
  { slug: 'ai-text-humanizer', category: 'text', icon: 'type', component: 'AiTextHumanizer' },
  { slug: 'text-spinner', category: 'text', icon: 'type', component: 'TextSpinner' },
  { slug: 'readability-checker', category: 'text', icon: 'type', component: 'ReadabilityChecker' },
  { slug: 'grammar-checker', category: 'text', icon: 'type', component: 'GrammarChecker', popular: true },
  { slug: 'document-word-counter', category: 'text', icon: 'type', component: 'DocumentWordCounter' },
];
