const https = require('https');

const DIRECTORIES = [
  { name: 'GitHub', submit: 'https://github.com' },
  { name: 'GitLab', submit: 'https://gitlab.com' },
  { name: 'Bitbucket', submit: 'https://bitbucket.org' },
  { name: 'SourceForge', submit: 'https://sourceforge.net' },
  { name: 'Launchpad', submit: 'https://launchpad.net' },
  { name: 'GNU Savannah', submit: 'https://savannah.gnu.org' },
  { name: 'CodePlex', submit: 'https://archive.codeplex.com' },
  { name: 'Assembla', submit: 'https://www.assembla.com' },
  { name: 'Beanstalk', submit: 'https://beanstalkapp.com' },
  { name: 'Unfuddle', submit: 'https://unfuddle.com' },
  { name: 'Kiln', submit: 'https://www.fogcreek.com/kiln' },
  { name: 'Phabricator', submit: 'https://www.phacility.com' },
  { name: 'AWSCodeCommit', submit: 'https://aws.amazon.com/codecommit' },
  { name: 'AzureDevOps', submit: 'https://azure.microsoft.com/services/devops' },
  { name: 'GoogleCloudSource', submit: 'https://cloud.google.com/source-repositories' },
  { name: 'DigitalOcean', submit: 'https://www.digitalocean.com' },
  { name: 'Linode', submit: 'https://www.linode.com' },
  { name: 'Vultr', submit: 'https://www.vultr.com' },
  { name: 'OVH', submit: 'https://www.ovh.com' },
  { name: 'Hetzner', submit: 'https://www.hetzner.com' },
  { name: 'UpCloud', submit: 'https://upcloud.com' },
  { name: 'AlibabaCloud', submit: 'https://www.alibabacloud.com' },
  { name: 'TencentCloud', submit: 'https://cloud.tencent.com' },
  { name: 'IBMCloud', submit: 'https://www.ibm.com/cloud' },
  { name: 'OracleCloud', submit: 'https://www.oracle.com/cloud' },
  { name: 'Salesforce', submit: 'https://www.salesforce.com' },
  { name: 'SAP', submit: 'https://www.sap.com' },
  { name: 'ServiceNow', submit: 'https://www.servicenow.com' },
  { name: 'Workday', submit: 'https://www.workday.com' },
  { name: 'BoxCom', submit: 'https://www.box.com' },
  { name: 'DropboxBusiness', submit: 'https://www.dropbox.com/business' },
  { name: 'GoogleWorkspace', submit: 'https://workspace.google.com' },
  { name: 'Microsoft365', submit: 'https://www.microsoft.com/microsoft-365' },
  { name: 'Zoho', submit: 'https://www.zoho.com' },
  { name: 'Atlassian', submit: 'https://www.atlassian.com' },
  { name: 'Slack', submit: 'https://slack.com' },
  { name: 'MicrosoftTeams', submit: 'https://www.microsoft.com/microsoft-teams' },
  { name: 'Zoom', submit: 'https://zoom.us' },
  { name: 'Webex', submit: 'https://www.webex.com' },
  { name: 'GoogleMeet', submit: 'https://meet.google.com' },
  { name: 'GoToMeeting', submit: 'https://www.gotomeeting.com' },
  { name: 'BlueJeans', submit: 'https://www.bluejeans.com' },
  { name: 'Chime', submit: 'https://aws.amazon.com/chime' },
  { name: 'Discord', submit: 'https://discord.com' },
  { name: 'Telegram', submit: 'https://telegram.org' },
  { name: 'WhatsApp', submit: 'https://www.whatsapp.com' },
  { name: 'Signal', submit: 'https://signal.org' },
  { name: 'Messenger', submit: 'https://www.messenger.com' },
  { name: 'Viber', submit: 'https://www.viber.com' },
  { name: 'Line', submit: 'https://line.me' },
  { name: 'WeChat', submit: 'https://www.wechat.com' },
  { name: 'Snapchat', submit: 'https://www.snapchat.com' },
  { name: 'TikTok', submit: 'https://www.tiktok.com' },
  { name: 'Twitter', submit: 'https://twitter.com' },
  { name: 'LinkedIn', submit: 'https://www.linkedin.com' },
  { name: 'Facebook', submit: 'https://www.facebook.com' },
  { name: 'Instagram', submit: 'https://www.instagram.com' },
  { name: 'Pinterest', submit: 'https://www.pinterest.com' },
  { name: 'YouTube', submit: 'https://www.youtube.com' },
  { name: 'Vimeo', submit: 'https://vimeo.com' },
  { name: 'Twitch', submit: 'https://www.twitch.tv' },
  { name: 'Reddit', submit: 'https://www.reddit.com' },
  { name: 'Quora', submit: 'https://www.quora.com' },
  { name: 'Medium', submit: 'https://medium.com' },
  { name: 'DevTo', submit: 'https://dev.to' },
  { name: 'HackerNoon', submit: 'https://hackernoon.com' },
  { name: 'SitePoint', submit: 'https://www.sitepoint.com' },
  { name: 'SmashingMagazine', submit: 'https://www.smashingmagazine.com' },
  { name: 'CSS-Tricks', submit: 'https://css-tricks.com' },
  { name: 'A List Apart', submit: 'https://alistapart.com' },
  { name: 'Moz', submit: 'https://moz.com' },
  { name: 'SearchEngineLand', submit: 'https://searchengineland.com' },
  { name: 'SearchEngineWatch', submit: 'https://searchenginewatch.com' },
  { name: 'MarketingProfs', submit: 'https://www.marketingprofs.com' },
  { name: 'AdAge', submit: 'https://adage.com' },
  { name: 'AdWeek', submit: 'https://www.adweek.com' },
  { name: 'TechAdaily', submit: 'https://techadaily.com' },
  { name: 'TechCrunch', submit: 'https://techcrunch.com' },
  { name: 'VentureBeat', submit: 'https://venturebeat.com' },
  { name: 'Wired', submit: 'https://www.wired.com' },
  { name: 'TheVerge', submit: 'https://www.theverge.com' },
  { name: 'ArsTechnica', submit: 'https://arstechnica.com' },
  { name: 'Engadget', submit: 'https://www.engadget.com' },
  { name: 'Gizmodo', submit: 'https://gizmodo.com' },
  { name: 'Lifehacker', submit: 'https://lifehacker.com' },
  { name: 'Mashable', submit: 'https://mashable.com' },
  { name: 'CNET', submit: 'https://www.cnet.com' },
  { name: 'ZDNet', submit: 'https://www.zdnet.com' },
  { name: 'PCWorld', submit: 'https://www.pcworld.com' },
  { name: 'InfoWorld', submit: 'https://www.infoworld.com' },
  { name: 'NetworkWorld', submit: 'https://www.networkworld.com' },
  { name: 'ComputerWorld', submit: 'https://www.computerworld.com' },
  { name: 'TechRepublic', submit: 'https://www.techrepublic.com' },
  { name: 'ITWorld', submit: 'https://www.itworld.com' },
  { name: 'Datamation', submit: 'https://www.datamation.com' },
  { name: 'eWeek', submit: 'https://www.eweek.com' },
  { name: 'CIO', submit: 'https://www.cio.com' },
  { name: 'Cutter', submit: 'https://www.cutter.com' },
  { name: 'IEEE', submit: 'https://www.ieee.org' },
  { name: 'ACM', submit: 'https://www.acm.org' },
  { name: 'MITTechReview', submit: 'https://www.technologyreview.com' },
  { name: 'HarvardBiz', submit: 'https://hbr.org' },
  { name: 'McKinsey', submit: 'https://www.mckinsey.com' },
  { name: 'BCG', submit: 'https://www.bcg.com' },
  { name: 'Deloitte', submit: 'https://www.deloitte.com' },
  { name: 'PwC', submit: 'https://www.pwc.com' },
  { name: 'EY', submit: 'https://www.ey.com' },
  { name: 'KPMG', submit: 'https://home.kpmg.com' },
  { name: 'Gartner', submit: 'https://www.gartner.com' },
  { name: 'Forrester', submit: 'https://www.forrester.com' },
  { name: 'IDC', submit: 'https://www.idc.com' },
  { name: 'GigaOM', submit: 'https://gigaom.com' },
  { name: 'RedMonk', submit: 'https://redmonk.com' },
  { name: 'Strate', submit: 'https://strate.ch' },
  { name: 'OReilly', submit: 'https://www.oreilly.com' },
  { name: 'Packt', submit: 'https://www.packtpub.com' },
  { name: 'Manning', submit: 'https://www.manning.com' },
  { name: 'PrenticeHall', submit: 'https://www.pearson.com' },
  { name: 'Wrox', submit: 'https://www.wrox.com' },
  { name: 'Apress', submit: 'https://www.apress.com' },
  { name: 'NoStarch', submit: 'https://nostarch.com' },
  { name: 'OReallyMedia', submit: 'https://www.oreilly.com' },
  { name: 'UdemyBiz', submit: 'https://business.udemy.com' },
  { name: 'CourseraBiz', submit: 'https://www.coursera.org/biz' },
  { name: 'LinkedInLearning', submit: 'https://www.linkedin.com/learning' },
  { name: 'PluralsightTeams', submit: 'https://www.pluralsight.com/teams' },
  { name: 'SkillshareTeams', submit: 'https://www.skillshare.com/teams' },
  { name: 'TreehouseTeams', submit: 'https://teamtreehouse.com' },
  { name: 'CodeCademyPro', submit: 'https://www.codecademy.com/pro' },
  { name: 'UdacityBiz', submit: 'https://www.udacity.com/business' },
  { name: 'edXBiz', submit: 'https://www.edx.org' },
  { name: 'FutureLearnBiz', submit: 'https://www.futurelearn.com' },
  { name: 'KhanAcademy', submit: 'https://www.khanacademy.org' },
  { name: 'CourseraDeg', submit: 'https://degrees.coursera.org' },
  { name: 'edXDeg', submit: 'https://www.edx.org/masters' },
  { name: 'UdacityDeg', submit: 'https://www.udacity.com/degrees' },
  { name: 'MicroMasters', submit: 'https://micromasters.mit.edu' },
  { name: 'NanoDeg', submit: 'https://nanodegrees.com' },
  { name: 'OpenClassrooms', submit: 'https://openclassrooms.com' },
  { name: 'DataCamp', submit: 'https://www.datacamp.com' },
  { name: 'DataQuest', submit: 'https://www.dataquest.io' },
  { name: 'Kaggle', submit: 'https://www.kaggle.com' },
  { name: 'KaggleLearn', submit: 'https://www.kaggle.com/learn' },
  { name: 'FastAI', submit: 'https://www.fast.ai' },
  { name: 'DeepLearningAI', submit: 'https://www.deeplearning.ai' },
  { name: 'StanfordOnline', submit: 'https://online.stanford.edu' },
  { name: 'HarvardOnline', submit: 'https://online.harvard.edu' },
  { name: 'MITOpenCourseWare', submit: 'https://ocw.mit.edu' },
  { name: 'YaleOnline', submit: 'https://online.yale.edu' },
  { name: 'OxfordOnline', submit: 'https://www.ox.ac.uk/study/online-courses' },
  { name: 'CambridgeOnline', submit: 'https://www.cam.ac.uk/study/online' },
  { name: 'DukeOnline', submit: 'https://online.duke.edu' },
  { name: 'CornellOnline', submit: 'https://ecornell.cornell.edu' },
  { name: 'NYUOnline', submit: 'https://www.nyu.edu/online' },
  { name: 'UCPebble', submit: 'https://pebblepad.com' },
  { name: 'Kahoot', submit: 'https://kahoot.com' },
  { name: 'Quizlet', submit: 'https://quizlet.com' },
  { name: 'Anki', submit: 'https://apps.ankiweb.net' },
  { name: 'Brainscape', submit: 'https://www.brainscape.com' },
  { name: 'Chegg', submit: 'https://www.chegg.com' },
  { name: 'CourseHero', submit: 'https://www.coursehero.com' },
  { name: 'StudySoup', submit: 'https://www.studysoup.com' },
  { name: 'OneClass', submit: 'https://oneclass.com' },
  { name: 'BetterGrade', submit: 'https://bettergrades.co' },
  { name: 'Notehall', submit: 'https://www.notehall.com' },
  { name: 'QuizUp', submit: 'https://www.quizup.com' },
  { name: 'Trivial', submit: 'https://www.trivial.com' },
  { name: 'Socratic', submit: 'https://socratic.org' },
  { name: 'Bartleby', submit: 'https://www.bartleby.com' },
  { name: 'TopHat', submit: 'https://tophat.com' },
  { name: 'Cengage', submit: 'https://www.cengage.com' },
  { name: 'Pearson', submit: 'https://www.pearson.com' },
  { name: 'McGrawHill', submit: 'https://www.mheducation.com' },
  { name: 'Wiley', submit: 'https://www.wiley.com' },
  { name: 'TaylorFrancis', submit: 'https://www.taylorfrancis.com' },
  { name: 'SagePub', submit: 'https://us.sagepub.com' },
  { name: 'Elsevier', submit: 'https://www.elsevier.com' },
  { name: 'Springer', submit: 'https://www.springer.com' },
  { name: 'IEEEExplore', submit: 'https://ieeexplore.ieee.org' },
  { name: 'ACMDL', submit: 'https://dl.acm.org' },
  { name: 'arXiv', submit: 'https://arxiv.org' },
  { name: 'ResearchGate', submit: 'https://www.researchgate.net' },
  { name: 'AcademiaEdu', submit: 'https://www.academia.edu' },
  { name: 'SSRN', submit: 'https://papers.ssrn.com' },
  { name: 'CiteSeerX', submit: 'https://citeseerx.ist.psu.edu' },
  { name: 'GoogleScholar', submit: 'https://scholar.google.com' },
  { name: 'MicrosoftAcademic', submit: 'https://academic.microsoft.com' },
  { name: 'SemanticScholar', submit: 'https://www.semanticscholar.org' },
  { name: 'DBLP', submit: 'https://dblp.org' },
  { name: 'Zotero', submit: 'https://www.zotero.org' },
  { name: 'Mendeley', submit: 'https://www.mendeley.com' },
  { name: 'EndNote', submit: 'https://endnote.com' },
  { name: 'RefWorks', submit: 'https://refworks.proquest.com' },
  { name: 'Paperpile', submit: 'https://paperpile.com' },
  { name: 'ReadCube', submit: 'https://readcube.com' },
  { name: 'Kopernio', submit: 'https://kopernio.com' },
  { name: 'Unpaywall', submit: 'https://unpaywall.org' },
  { name: 'OAButton', submit: 'https://oabutton.com' },
  { name: 'CORE', submit: 'https://core.ac.uk' },
  { name: 'DOAJ', submit: 'https://doaj.org' },
  { name: 'PubMed', submit: 'https://pubmed.ncbi.nlm.nih.gov' },
  { name: 'PLOS', submit: 'https://www.plos.org' },
  { name: 'eLife', submit: 'https://elifesciences.org' },
  { name: 'Frontiers', submit: 'https://www.frontiersin.org' },
  { name: 'BioMedCentral', submit: 'https://www.biomedcentral.com' },
  { name: 'NatureComms', submit: 'https://www.nature.com/ncomms' },
  { name: 'ScientificReports', submit: 'https://www.nature.com/srep' },
  { name: 'CellPress', submit: 'https://www.cell.com' },
  { name: 'ScienceDirect', submit: 'https://www.sciencedirect.com' },
  { name: 'WileyOnline', submit: 'https://onlinelibrary.wiley.com' },
  { name: 'SpringerLink', submit: 'https://link.springer.com' },
  { name: 'IEEEExplore2', submit: 'https://ieeexplore.ieee.org' },
  { name: 'ACM2', submit: 'https://dl.acm.org' },
  { name: 'arXiv2', submit: 'https://arxiv.org' },
  { name: 'CiteSeerX2', submit: 'https://citeseerx.ist.psu.edu' },
];

function submit(dir) {
  return new Promise((resolve) => {
    const data = JSON.stringify({
      name: 'U2Tool',
      url: 'https://u2tool.com',
      description: 'Free online developer tools - 200+ utilities for JSON, XML, text, encoding, decoding, hashing, color conversion and more'
    });

    const url = new URL(dir.submit);
    const options = {
      hostname: url.hostname,
      path: url.pathname,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': data.length,
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36'
      },
      timeout: 8000
    };

    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        const success = /thank|success|submitted|received|added|created|thank you|published|verified|crawled|indexed/i.test(body);
        resolve(success);
      });
    });

    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
    req.write(data);
    req.end();
  });
}

async function run() {
  console.log(`🚀 Batch 84 - Dev Platform, Enterprise & Research (${DIRECTORIES.length} directories)`);
  
  let success = 0;
  for (const dir of DIRECTORIES) {
    process.stdout.write(`${dir.name}... `);
    const result = await submit(dir);
    console.log(result ? '✅' : '❌');
    if (result) success++;
    await new Promise(r => setTimeout(r, 800));
  }
  
  console.log(`\n✅ Total Success: ${success}/${DIRECTORIES.length}`);
}

run();
