/**
 * Generate ToolImportMap.ts from tools.ts config
 * Maps each tool slug to its dynamic import function
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toolsPath = path.resolve(__dirname, '../src/config/tools.ts');
const content = fs.readFileSync(toolsPath, 'utf8');

// Extract slug → component mappings
const regex = /slug:\s*'([^']+)'.*?component:\s*'([^']+)'/g;
const entries: { slug: string; component: string }[] = [];
let match: RegExpExecArray | null;
while ((match = regex.exec(content)) !== null) {
  entries.push({ slug: match[1], component: match[2] });
}

const dedupedEntries = Array.from(
  new Map(entries.map((entry) => [entry.slug, entry])).values()
);

console.log(`Found ${entries.length} tools`);
console.log(`Deduped to ${dedupedEntries.length} unique tool slugs`);

// Check which svelte files exist
const toolsDir = path.resolve(__dirname, '../src/components/tools');
let missing = 0;
for (const e of dedupedEntries) {
  const filePath = path.join(toolsDir, `${e.component}.svelte`);
  if (!fs.existsSync(filePath)) {
    console.log(`MISSING: ${e.component}.svelte for slug ${e.slug}`);
    missing++;
  }
}
console.log(`Missing files: ${missing}`);

// Generate the import map
const lines: string[] = [];
lines.push('// AUTO-GENERATED - Do not edit manually');
lines.push('// Generated by scripts/generate-tool-import-map.ts');
lines.push(`// ${dedupedEntries.length} tools mapped`);
lines.push('');
lines.push('type ToolImporter = () => Promise<{ default: unknown }>;');
lines.push('');
lines.push('const TOOL_IMPORT_MAP: Record<string, ToolImporter> = {');

for (const e of dedupedEntries) {
  lines.push(`  '${e.slug}': () => import('./${e.component}.svelte'),`);
}

lines.push('};');
lines.push('');
lines.push('export default TOOL_IMPORT_MAP;');
lines.push('');

const outputPath = path.join(toolsDir, 'ToolImportMap.ts');
fs.writeFileSync(outputPath, lines.join('\n'));
console.log(`Generated ${outputPath}`);
