import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';

type AliasSpec = {
  slug?: unknown;
  aliases?: unknown;
  search_intent?: unknown;
};

function normalizeAlias(value: unknown): string | null {
  if (typeof value !== 'string') {
    return null;
  }

  const normalized = value.replace(/\s+/g, ' ').trim();
  return normalized.length > 0 ? normalized : null;
}

function readJson(filePath: string): unknown {
  return JSON.parse(fs.readFileSync(filePath, 'utf8')) as unknown;
}

export function collectSpecs(value: unknown): AliasSpec[] {
  if (Array.isArray(value)) {
    return value as AliasSpec[];
  }

  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    if (Array.isArray(record.tools)) {
      return record.tools as AliasSpec[];
    }
    return [record as AliasSpec];
  }

  return [];
}

export function buildAliases(specs: AliasSpec[]): Record<string, string[]> {
  const aliasesBySlug: Record<string, string[]> = {};

  for (const spec of specs) {
    if (typeof spec.slug !== 'string' || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(spec.slug)) {
      continue;
    }

    const aliases = new Set<string>();
    const searchIntent = normalizeAlias(spec.search_intent);
    if (searchIntent) {
      aliases.add(searchIntent);
    }

    if (Array.isArray(spec.aliases)) {
      for (const alias of spec.aliases) {
        const normalized = normalizeAlias(alias);
        if (normalized) {
          aliases.add(normalized);
        }
      }
    }

    if (aliases.size > 0) {
      aliasesBySlug[spec.slug] = Array.from(aliases).sort((left, right) => left.localeCompare(right));
    }
  }

  return Object.fromEntries(
    Object.entries(aliasesBySlug).sort(([left], [right]) => left.localeCompare(right))
  );
}

export function renderAliases(aliasesBySlug: Record<string, string[]>): string {
  const body = JSON.stringify(aliasesBySlug, null, 2);

  return `// AUTO-GENERATED - Do not edit manually\n// Generated by scripts/generate-ai-discovery-aliases.ts\n\nexport const GENERATED_DISCOVERY_ALIASES: Record<string, string[]> = ${body};\n`;
}

function parseArgs(argv: string[]) {
  const args = {
    inputPath: '',
    outputPath: 'src/lib/ai-discovery/generated-aliases.ts',
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--input') {
      args.inputPath = argv[index + 1] || '';
      index += 1;
      continue;
    }
    if (arg.startsWith('--input=')) {
      args.inputPath = arg.slice('--input='.length);
      continue;
    }
    if (arg === '--output') {
      args.outputPath = argv[index + 1] || args.outputPath;
      index += 1;
      continue;
    }
    if (arg.startsWith('--output=')) {
      args.outputPath = arg.slice('--output='.length);
      continue;
    }
    if (!arg.startsWith('-') && !args.inputPath) {
      args.inputPath = arg;
      continue;
    }
    throw new Error(`Unknown argument: ${arg}`);
  }

  if (!args.inputPath) {
    throw new Error('Usage: npx tsx scripts/generate-ai-discovery-aliases.ts --input path/to/tool-launch-batch.json [--output src/lib/ai-discovery/generated-aliases.ts]');
  }

  return {
    inputPath: path.resolve(process.cwd(), args.inputPath),
    outputPath: path.resolve(process.cwd(), args.outputPath),
  };
}

export function main() {
  const args = parseArgs(process.argv.slice(2));
  const specs = collectSpecs(readJson(args.inputPath));
  const aliasesBySlug = buildAliases(specs);
  fs.mkdirSync(path.dirname(args.outputPath), { recursive: true });
  fs.writeFileSync(args.outputPath, renderAliases(aliasesBySlug));
  console.log(`Generated ${path.relative(process.cwd(), args.outputPath)} with ${Object.keys(aliasesBySlug).length} aliased tools`);
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (invokedPath === import.meta.url) {
  main();
}
