/**
 * Generate ToolImportMap.ts from the split tools config.
 * Existing map order is preserved to keep generated diffs reviewable.
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { tools } from '../src/config/tools/index';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

type ToolImportEntry = { slug: string; component: string };

const configuredEntries: ToolImportEntry[] = tools.map((tool) => ({
  slug: tool.slug,
  component: tool.component,
}));

const configuredBySlug = new Map(
  configuredEntries.map((entry) => [entry.slug, entry])
);
const outputPath = path.join(__dirname, '../src/components/tools/ToolImportMap.ts');
const existingEntries: ToolImportEntry[] = [];

if (fs.existsSync(outputPath)) {
  const existingContent = fs.readFileSync(outputPath, 'utf8');
  const existingRegex = /'([^']+)':\s*\(\)\s*=>\s*import\('\.\/([^']+)\.svelte'\)/g;
  let existingMatch: RegExpExecArray | null;
  while ((existingMatch = existingRegex.exec(existingContent)) !== null) {
    existingEntries.push({ slug: existingMatch[1], component: existingMatch[2] });
  }
}

const seenSlugs = new Set<string>();
const orderedEntries: ToolImportEntry[] = [];

for (const existingEntry of existingEntries) {
  const configuredEntry = configuredBySlug.get(existingEntry.slug);
  if (!configuredEntry || seenSlugs.has(existingEntry.slug)) {
    continue;
  }
  orderedEntries.push(configuredEntry);
  seenSlugs.add(configuredEntry.slug);
}

for (const configuredEntry of configuredEntries) {
  if (seenSlugs.has(configuredEntry.slug)) {
    continue;
  }
  orderedEntries.push(configuredEntry);
  seenSlugs.add(configuredEntry.slug);
}

const dedupedEntries = orderedEntries;

console.log(`Found ${configuredEntries.length} tools`);
console.log(`Deduped to ${dedupedEntries.length} unique tool slugs`);

// Check which svelte files exist
const toolsDir = path.resolve(__dirname, '../src/components/tools');
let missing = 0;
for (const e of dedupedEntries) {
  const filePath = path.join(toolsDir, `${e.component}.svelte`);
  if (!fs.existsSync(filePath)) {
    console.log(`MISSING: ${e.component}.svelte for slug ${e.slug}`);
    missing++;
  }
}
console.log(`Missing files: ${missing}`);

// Generate the import map
const lines: string[] = [];
lines.push('// AUTO-GENERATED - Do not edit manually');
lines.push('// Generated by scripts/generate-tool-import-map.ts');
lines.push(`// ${dedupedEntries.length} tools mapped`);
lines.push('');
lines.push('type ToolImporter = () => Promise<{ default: unknown }>;');
lines.push('');
lines.push('const TOOL_IMPORT_MAP: Record<string, ToolImporter> = {');

for (const e of dedupedEntries) {
  lines.push(`  '${e.slug}': () => import('./${e.component}.svelte'),`);
}

lines.push('};');
lines.push('');
lines.push('export default TOOL_IMPORT_MAP;');
lines.push('');

fs.writeFileSync(outputPath, lines.join('\n'));
console.log(`Generated ${outputPath}`);
